youtube_dl/extractor/xhamster.py

xHamster can be browsed in HTTPS even though the downloads are HTTP. This patch adds support for the HTTPS URLs.

[xhamster] Add HTTPS support

---

youtube_dl/YoutubeDL.py
youtube_dl/__init__.py
youtube_dl/options.py

As explained in https://github.com/rg3/youtube-dl/issues/3610, https://github.com/rg3/youtube-dl/issues/2765 there are cases when downloading separate video and audio and then merging when the video container (usually webm containing VP8/VP9) is incompatible with the audio codec (aac/mp3). By default, youtube-dl attempts to create a merge in the container format of the video file.
This is a redo of pull request https://github.com/rg3/youtube-dl/pull/4577. This time around I've added a video option called "merge-ouput-format" that specifies what container format the merge output should be put into. It is only used if merging is required (something like "-f best" will not use it for instance). If you provide nothing for it, the video part's container format will be used, just like before.

Merge output format

---

youtube_dl/extractor/eighttracks.py

because we cant to predict the real download links without the server, we must play by the 8tracks rules:
* max 3 skip in hour. but playlist contains min 8 tracks, so 3 isn't enough
* continue to the next song after the current track done. but we don't know the exact length of track
so, some is better than nothing, and currently the exiting plugin is useless.
I calculate the average track length from playlist length and track count, then sleep after download failed until that new request be considered as legitimate.
ugly, takes a long time, but works!

Fix #2310. Play by the 8tracks rules

---

youtube_dl/postprocessor/ffmpeg.py

This fixes #4245.
I tested this with Python 2.7.8 and Python 3.4.1 on Windows 7.  The mtime is now correctly set when using `-f bestvideo+bestaudio`.
`--no-mtime` still works as expected.

Copy the mtime from the oldest source file to the file created by ffmpeg

---

youtube_dl/extractor/youtube.py

Looks like Google switched to a new JS compiler that includes dollar signs in function names.

Fix Youtube encrypted sigs.

---

youtube_dl/postprocessor/ffmpeg.py

Description is one of the MP4 tags honored by ffmpeg, looks like a good place to store the video description when embedding metadata. I believe the source URL is useful information to keep as well, the comment tag seems like a good place to record it.
While I don't see the description becoming long enough to significantly affect the size of the output video, it can be long and unwieldy, for example while reading mediainfo dumps. Should including it be dependant on another option in addition to --add-metadata, perhaps --add-description?

Embed description and URL as MP4 tags

---

youtube_dl/utils.py

The dict of headers of request objects in urllib has its keys always
capitalized.
This causes the lookup to fail and overwrite the header. If for example
a Extractor tries to add a "User-Agent" header the internal
representation in the request object is "User-agent". The header is
therefore clobbered by the "User-Agent" in std_headers, because the
strings are not equal.

[utils] Prevent override of custom headers.

---

youtube_dl/extractor/fc2.py

Maybe not the best way to deal with those issues (#2912 and #3171)
but I tested it for more than month (also got some feedback from others) and it works almost flawlessly.
As a side note, most of the times video can still be downloaded even if error code is 403 but after login it shouldn't even be returned.
Also sometimes there are error codes 601,602 returned - I think thats a views limit (hourly/daily) but as this patch don't respect those error codes, but checks for media link one can as side effect download videos even if on website he reached his views limit :)
Also in .netrc machine for credentials is: fc2

[fc2] Add user login (Fixes #2912 and #3171)

---

youtube_dl/extractor/generic.py
youtube_dl/extractor/viddler.py

This fixes the Viddler extractor. There  were a couple of issues: 
1. The API call needed a Referer header or else would get a 403 response code
2. The cdn url does not work over https (SSL) - would result in a 404, so have to specify the scheme to be http.
This resolves #2466 and #3897

fixed viddler support; also added a viddler generic extractor 

---

youtube_dl/utils.py

With this change the '--no-check-certificate' works again (#4807).
/cc @phihag.

[utils] YoutubeDLHTTPSHandler.https_open: pass all required arguments to to do_open

---

youtube_dl/downloader/rtmp.py
youtube_dl/extractor/__init__.py
youtube_dl/extractor/dctp.py

Needs --realtime flag for rtmpdump, otherwise the downloaded video is broken.
The fetched json file has more meta data. Not sure what it is used for, other than bookkeeping, so I leave this as a TODO.

added extractor for dctp.tv

---

youtube_dl/YoutubeDL.py
youtube_dl/extractor/appletrailers.py
youtube_dl/extractor/cinchcast.py
youtube_dl/extractor/generic.py
youtube_dl/extractor/grooveshark.py
youtube_dl/extractor/smotri.py

* Opening curly brace removed from regexes where it was found (it's a control character)
* Removed dead code (duplicate dictionary keys, two return statements in a row)

Fix regex syntax ambiguity in two info extractors & remove unreachable code

---

README.md

required a .md at the end of the link.

supported sites link was not opening from README

---

youtube_dl/downloader/http.py

"Connection Reset By Peer" error is frequent in when connecting through a firewall and retrying download often is a workaround for this.

Handling Connection Reset by Peer Error

---

youtube_dl/downloader/external.py

Currently Youtube-dl is not passing the `source-address` to external downloaders like wget, curl and aria2c.
This pull request adds that support

Passing source address option to external downloaders

---

youtube_dl/extractor/gamekings.py

When trying to download some GameKings videos, not all worked. This was
because not all videos had a "/large"-URL available. The extractor
checks now if the /large URL is available, if it isn't, it tries to get
the normal URL.

[Gamekings] Fix 404 when large isn't available

---

youtube_dl/extractor/rtlnow.py

this fixes the rtlnow (voxnow, rtl2now, ...) plugin for new series, which are currently broken because of DRM
samples:
"Der Bachelor" season 5: http://rtl-now.rtl.de/der-bachelor/folge-4.php?film_id=188729&player=1&season=5
"Die Pferdeprofis" season 3: http://www.voxnow.de/die-pferdeprofis/stute-lotta-noriker-wallach-hui-buh.php?film_id=188989&player=1&season=3
"Berlin - Tag und Nacht" some new episode: http://rtl2now.rtl2.de/berlin-tag-nacht/berlin-tag-nacht-folge-858.php?film_id=189039&player=1&season=5

fix rtlnow for new series and episodes

---

youtube_dl/YoutubeDL.py
youtube_dl/downloader/common.py
youtube_dl/downloader/f4m.py
youtube_dl/downloader/http.py
youtube_dl/downloader/rtmp.py

Instead of every downloader calling two helper functions, let our progress report be an ordinary progress hook like everyone else's. Amend the documentation and add a new "error" case.
Closes #4875.

[YoutubeDL] Use a progress hook for progress reporting

---

youtube_dl/extractor/imgur.py

Just one minor improvement to 3bf5705. It should support extracting a video from imgur's normal URL format: e.g. https://imgur.com/A61SaA1

[imgur] Support regular URL

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/airmozilla.py

Air Mozilla is where Mozilla's live videos are saved. This extractor doesn't attempt to grab the live streams yet, just the archived videos.

[airmozilla] Add new extractor

---

youtube_dl/extractor/rtlnow.py

Fix the RTL (Vox, ...) extractor for new episodes again.
Examples:
http://rtl2now.rtl2.de/berlin-tag-nacht/berlin-tag-nacht-folge-871.php?film_id=191349&player=1&season=5
http://www.voxnow.de/die-pferdeprofis/tinker-andy-fohlen-chaotic-crumble.php?film_id=191011&player=1&season=3
http://rtl-now.rtl.de/der-bachelor/folge-7.php?film_id=191373&player=1&season=5

Fix the RTL extractor for new episodes by using a different hostname

---

youtube_dl/downloader/f4m.py
youtube_dl/extractor/common.py
youtube_dl/extractor/wdr.py

This adds basic support for live streams to the F4M downloader.
Specifically, this is needed for downloading the WDR live stream, but I think other sites will benefit as well. WDR live example:
> python -m youtube_dl --no-part http://www1.wdr.de/mediathek/video/livestream/index.html

Live F4M streams and support for WDR live TV

---

youtube_dl/extractor/comedycentral.py

Persuant to [issue 5046](https://github.com/rg3/youtube-dl/issues/5046), pulls in subtitles for The Daily Show extractor.

Adding subtitles

---

youtube_dl/extractor/lynda.py

Ajax subtitle request returns text captions with new line characters in the beginning and the end.
'\nIn the next several chapters of this\ncourse, we're going to be going over the \n'
Result .srt file has bad format and ignored by VLC and some other players.
Example:
1
00:00:00.025 --> 00:00:04.939
In the next several chapters of this 
course, we're going to be going over the 
To fix this bug, we need to remove empty line after timecode
1
00:00:00.025 --> 00:00:04.939    
In the next several chapters of this 
course, we're going to be going over the 
This is done with **strip** function

[lynda] Fixed subtitles broken file

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/oppetarkiv.py

Some, if not all, of the videos appear to be geo-blocked (Sweden).
Test might fail (403 Forbidden) if not run through a Swedish connection.

[oppetarkiv] Add new extractor

---

youtube_dl/extractor/lynda.py

We can't use **lstrip** for subtitles. Not every subtitle line in the response contains two "new line" characters. And in some cases .srt files can be invalid.
Example: http://www.lynda.com/ajax/player?videoId=159736&courseId=123563&type=transcript
There are lines with only one "new line" and there are empty lines.
We should skip empty lines and add \r\n\r\n after each subtitle line.
Also sequence counter was updated.

[lynda] Check for the empty subtitles

---

youtube_dl/extractor/youporn.py

This fixes the "Youporn stop working" issue.
https://github.com/rg3/youtube-dl/issues/5078
The problem is that the js code that YouPorn uses to pass a video's json has been changed.
I've updated the extractor's search regex correspondingly.

fix youporn extractor's json search regex

---

youtube_dl/extractor/funnyordie.py

See, for example, http://www.funnyordie.com/videos/224829ff6d/judd-apatow-will-direct-your-vine
So far I have only seen WebVTT format subtitles, and the pattern is somewhat ambiguous, as they are usually added via the <track> element and lack MIME/type info separate of the filename.

Add subtitles for Funny Or Die

---

youtube_dl/extractor/globo.py

Globo.com download did not work with old flash version. Using Chrome-dev flash version.
Probe:  leonardo  dora  ~  $  youtube-dl "http://g1.globo.com/globo-reporter/noticia/2015/03/globo-reporter-mostra-pessoas-que-descobriram-como-viver-com-menos.html"
[Globo] globo-reporter/noticia/2015/03/globo-reporter-mostra-pessoas-que-descobriram-como-viver-com-menos.html: Downloading webpage
[Globo] 4028409: Downloading JSON metadata
[Globo] 4028409: Downloading security hash for 5500f59b9214470f1d0058e4
[Globo] 4028409: Downloading security hash for 5500f59b921447071c004ae0
[Globo] 4028409: Downloading security hash for 5500f59b92144739e3004c92
[Globo] 4028409: Downloading security hash for 5500f59b9214470f1d0058e2
[download] Destination: Globo Repórter mostra pessoas que descobriram como …

* Change globo.py flash ver to 17.0.0.132 - Chrome 42.0.2311.22

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/beatportpro.py

This extractor is for Beatport's 2-minute, low-quality track previews
only.  To obtain an entire track, you obviously have to purchase and
download it normally through the Beatport store!
Possible future improvements:
- Playlists for albums or other track-list pages
- User login to play from My Beatport, Hold Bin, or Cart

[BeatportPro] Add new extractor

---

youtube_dl/extractor/niconico.py

You couldn't download *nm* URL videos when you authenticated (you were able to when *not* authenticated)
I changed the download URL a bit; It shouldn't affect other than *nm* URLs.
for test
- *sm* URLs
http://www.nicovideo.jp/watch/sm25798024
- *nm* URLs
http://www.nicovideo.jp/watch/nm14296458

[niconico] fixed bug for nm URLs when logged in

---

youtube_dl/extractor/xuite.py

base64.b64decode() accept only binary types in Python 3.2
This patch should fix failed tests with Python 3.2 on Travis-CI

[Xuite] Fix extraction on python 3.2

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/spankbang.py

Add an extractor for spankbang.com.

[SpankBang] Add new extractor

---

youtube_dl/postprocessor/ffmpeg.py

Related to previous pull request.
https://github.com/rg3/youtube-dl/pull/5241
Debian running on Android VM, downloads video fine. When extracting audio to mp3 and calling ffmpeg, postprocessor/ffmpeg.py calls os.utime, which is not permitted under the sandboxed app.
Latest mainline verbose output
[debug] Command-line args: [u'--extract-audio', u'--audio-format', u'mp3', u'-k', u'-a', u'/sdcard/clipboard', u'--verbose']
[debug] Batch file urls: [u'http://youtu.be/teGhgwGq2hc']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.3 - Linux-3.4.42-gb89c9dd-armv7l-with-debian-7.5
[debug] exe versions: avconv 10.1-6, avprobe 10.1-6, ffmpeg 0.8.17-6 …

[ffmpeg] adding exception catching for call to os.utime in run_ffmpeg_multiple_files

---

youtube_dl/extractor/wat.py

line 116, modify 'Downloding' to 'Downloading'.
It looks like nothing, but it is very annoying when youtube-dl command's output is parsed to find progress on a php (or other language) website for example.

Update wat.py misspelling 'downloding'

---

README.md
test/parameters.json
test/test_YoutubeDL.py
youtube_dl/YoutubeDL.py
youtube_dl/__init__.py
youtube_dl/options.py
youtube_dl/utils.py

It doesn't work well with 'bestvideo' and 'bestaudio' because they are usually before the max quality.
Format filters should be used instead, they are more flexible and don't require the requested quality to exist for each video.

Remove the --max-quality option

---

test/test_YoutubeDL.py
youtube_dl/YoutubeDL.py

Otherwise it's impossible to only download non-DASH formats, for example `best[height=?480]/best` would download a DASH video if it's the only one with height=480, instead for falling back to the second format specifier.
For audio only urls (soundcloud, bandcamp ...), the best audio will be downloaded as before.

Make 'best' format only match non-DASH formats (closes #5554)

---

youtube_dl/extractor/bild.py

Currently the BildIE test case fails for the following reasons:
1/ The XML downloaded contains raw ampersands in attributes
2/ The expected thumbnail has changed.
This pull request fixes these 2 issues

[BildIE] Fix ampersands in xml attributes & update test thumbnails

---

youtube_dl/YoutubeDL.py
youtube_dl/__init__.py
youtube_dl/postprocessor/embedthumbnail.py

Current ```EmbedThumbnailPP``` first downloads the necessary thumbnail, and then merges it into the audio file. Thus in the following invocation:
```
youtube-dl --verbose --embed-thumbnail --no-overwrite --write-all-thumbnails test:xuite
```
Thumbnails are downloaded twice. One in ```YoutubeDL``` and another in ```EmbedThumbnailPP```. I try to fix the scenario in this PR.
There's a deeper advantage from this fix. I believe all resources needed by postprocessors should be downloaded by ```YoutubeDL```, and my implementation conforms to the principle. I think this principle is helpful for solving the problem mentioned by @dstftw in https://github.com/rg3/youtube-dl/commit/1c7e2e64f6328024711d5fa999d4498396f4cb5c#commitcomment-11157068
There are 2 potential issues in my implementation:
1. …

Use thumbnails downloaded by YoutubeDL in EmbedThumbnailPP

---

youtube_dl/extractor/empflix.py
youtube_dl/extractor/tnaflix.py

URLs with dots were raising a "UnsupportedError: Unsupported URL" error.

[TNAFlix] Allow dot (and more) in cat_id and display_id

---

youtube_dl/extractor/youtube.py

Since we use fixed values for some fields like width and height they can be wrong, and would get picked by some formats filters.
For example for https://www.youtube.com/watch?v=EQCrhbBxsjA the biggest height is 720 and for nondash formats it's set to 1440, so -f 'bestvideo[height>=1200]+bestaudio' would incorrectly pick the nondash format, instead it should report that the requested format is not available.

[youtube] Remove the nondash formats (fixes #5774)

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/soompi.py

tv.soompi.com is a video streaming site focused on South Korean television shows.
Many of the videos are geo-restricted to Canada and the US, but the selected video should pass tests.

[soompi] Add new extractor for tv.soompi.com

---

youtube_dl/extractor/liveleak.py

some (old?) videos use `...mp4.h264_270p.mp4...` instead of `...mp4.h264_base.mp4...` in their URLs.
This is an addition to #4768.

LiveLeak: support more original videos

---

youtube_dl/extractor/niconico.py

Niconico serves two different quality levels; source quality, and what they call 'eco.' This isn't an entirely complete way of listing the qualities as distinct. This patch does show either 'src' or 'low' under the quality note when run with -F. This way, users can at least tell which quality they will get. This resolves #5838 partially, or at least gives a bit more info to avoid the pitfalls of low quality. I can't go any further with this code, since I don't have a premium account to test anything further with. I've verified that the (minor) changes work and are non-invasive, so including it shouldn't be a big deal.

Quality note for niconico

---

youtube_dl/extractor/safari.py

It seems IDs can contain letters as well as numbers - e.g. https://www.safaribooksonline.com/library/view/create-a-nodejs/100000006A0210 - so just match any characters that aren't `/` (although `\w+` would probably be sufficient).

[safari] make url regex more lenient

---

youtube_dl/extractor/noco.py

Fixes error using `compat_str()` when the title is only a number (interpreted as integer instead of string):
`TypeError: Can't convert 'int' object to str implicitly`
More details in issue

[noco.tv] Fix issue #6066: title interpreted as integer

---

youtube_dl/YoutubeDL.py
youtube_dl/__init__.py
youtube_dl/extractor/generic.py
youtube_dl/options.py

For some extractors that are hard to workout a good `_VALID_URL` we use very vague and unrestrictive ones, e.g. just allowing anything after hostname and capturing part of URL as id.
If some of these extractors happen to have a video embed of some different hoster or platform
and this scenario was not handled in extractor itself we end up with inability to download this embed
until extractor is fixed to support embeds of this kind.
Forcing downloader to use the generic extractor can be a neat temporary solution for this problem.
**Example:**
[5-tv](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/fivetv.py) extractor with [Tvigle](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/generic.py#L1324-L1328) embed (may be georestricted to Russia) …

Add --force-generic-extractor

---

youtube_dl/extractor/youtube.py
youtube_dl/options.py

DASH manifest pointed by dashmpd from the video webpage and one pointed by get_video_info may
be different (namely different itag set) - some itags are missing from DASH manifest pointed by
webpage's dashmpd, some - from DASH manifest pointed by get_video_info's dashmpd).
The general idea is to take a union of itags of both DASH manifests (for example video with such
'manifest behavior' see https://github.com/rg3/youtube-dl/issues/6093).

[youtube] Extract formats from multiple DASH manifests (Closes #6093)

---

youtube_dl/extractor/ina.py

The extractor for ina.fr does not handle HTTPS URLs. I add this support.
alarig@airmure ~/tmp $ yt-dl https://www.ina.fr/video/RCC9712053545/la-canicule-et-la-biere-video.html
[generic] la-canicule-et-la-biere-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] la-canicule-et-la-biere-video: Downloading webpage
[generic] la-canicule-et-la-biere-video: Extracting information
ERROR: Unsupported URL: https://www.ina.fr/video/RCC9712053545/la-canicule-et-la-biere-video.html
alarig@airmure ~/tmp $ yt-dl http://www.ina.fr/video/RCC9712053545/la-canicule-et-la-biere-video.html
[Ina] RCC9712053545: Downloading XML
[Ina] RCC9712053545: Extracting information
[download] La canicule et la bière-RCC9712053545.mp4 has already been downloaded
[download] 100% of …

Add support of HTTPS for ina.fr

---

youtube_dl/extractor/qqmusic.py

The old webpage based extraction method was not working for new albums. A json endpoint is now available for extracting album info and songs.

[qqmusic] Fix album extraction

---

youtube_dl/extractor/qqmusic.py

Some songs do not have hq (320k) versions available. This fixes it by checking if the url is valid before adding to formats.
Also includes a small change to get the thumbnail url for a song based on the album mid.

[qqmusic] Fix song extraction when certain formats are unavailable

---

README.md
youtube_dl/YoutubeDL.py
youtube_dl/__init__.py
youtube_dl/options.py
youtube_dl/postprocessor/common.py
youtube_dl/postprocessor/ffmpeg.py

As the "LG Time Machine" (a (not so) smart TV) has a limitation for video dimensions (as for codecs), I take to implement an extra parameter `--pp-params` where we can send extra parameterization for the video converter (post-processor).
Example:
```
$ youtube-dl --recode-video=xvid --pp-params='-s 720x480' -c https://www.youtube.com/watch?v=BE7Qoe2ZiXE
```
That works fine on a 4yo LG Time Machine.
Closes #5733

Adds support for XviD output with extra parametrization

---

youtube_dl/extractor/common.py
youtube_dl/extractor/prosiebensat1.py

1. `_extract_f4m_formats` now handles malformed f4m manifests (97f4aec).
2. URLs starting with `https?://` in 2.0 maniests are now handled properly (cc357c4).
3. Child f4m manifests are now extracted recursively (70f0f5a) in order to prevent format by requested bitrate resolve problem when parent and child manifest's bitrates differ.
4. prosiebensat1 switched to generic f4m extraction (f01f731).

[f4m] Improvements

---

youtube_dl/extractor/howstuffworks.py

make the extractor works with url that does not contain a number in the url like that:
http://shows.howstuffworks.com/stuff-to-blow-your-mind/optical-illusions-video.htm

[howstuffwoks] fix _VALID_URL regex

---

youtube_dl/extractor/sbs.py

The SBS website format has changed. I didn't see an issue for it (should I have created one??). This change fixes the SBS extractor.  
NB 1 - The thumbnail and description are now missing.
NB 2 - There is an existing problem with the SBS extractor #3811. youtube-dl now fails when it gets to this point.
Here is the output from the latest youtube-dl 
```
[debug] Command-line args: [u'--verbose', u'http://www.sbs.com.au/news/video/471395907773/The-Feed-July-9']
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.9 - Linux-3.19.0-15-generic-i686-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.6-0ubuntu0.15.04.1, ffprobe …
```

[SBS] fixes due to website changes

---

youtube_dl/extractor/iqiyi.py

Update the md5 salt (enc_key) to iqiyi lastest (2015-07-17) flash player. 
Recently iqiyi changes its md5 salt (the enc_key) frequently. 
But iqiyi tries to hide the salt with some complex methods. And auto extracting the salt is impossible. :-(
So just return the salt in `get_enc_key()` function. 
+ Before fix
```
$ python test/test_download.py TestDownload.test_Iqiyi
[iqiyi] temp_id: download video page
[iqiyi] 9c1fb1b99d192b21c559e5a1a2cb3c73: download swf content
ERROR: Unable to extract enc_key; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
File …
```

[iqiyi] fix iqiyi (2015-07-17), update the md5 salt (enc_key)

---

youtube_dl/extractor/tagesschau.py

When I try to view the old URL, I only get a 404, so I guess the video was
depublished :-( This patch adds a new video URL for the test, which is now
working fine for me :-)

[tagesschau] fix test which links to nonexisting video

---

youtube_dl/downloader/__init__.py
youtube_dl/downloader/dash.py
youtube_dl/downloader/http.py
youtube_dl/extractor/youtube.py

In some videos from youtube, the DASH manifest contains multiple segments URLs for each itag. Existing reports are #5884, #5703, #5702 (the first video is not accessible now, but I remember its DASH manifest contains segments), and I believe #5545, #5754 are affected by the same problem. In fact, downloading any DASH format from a currently live youtube video causes an error.
There are some issues:
1. Is it really needed? For all videos in aforementioned issues, ```-f best``` works fine.
2. My implementation is based on ```NativeHlsFD```, and the two looks similar. Maybe moving common codes to some base class is better.
3. Is it necessary to document ```initialization_url``` and ```segment_urls``` explicitly, in ```common.py``` or so?

[YoutubeDL] Support DASH manifest downloading

---

youtube_dl/YoutubeDL.py

As proposed by @yan12125 in https://github.com/rg3/youtube-dl/pull/5886#issuecomment-110210601.

[YoutubeDL] don't default to 'bestvideo+bestaudio/best' for live videos

---

youtube_dl/extractor/pbs.py

Many videos are given the title 'Full Episode' or 'Episode x', etc;
in the info json 'title' is the episode title (for oneshots this is
'Full Episode') while the program name is 'program':{'title'. This
changes the title from '(episode title)' to
'(program name) - (episode title)'
The following urls demonstrate useless titles
http://video.pbs.org/video/2365367186/
http://video.pbs.org/video/2365519307/
http://video.pbs.org/video/2365527039/
http://video.pbs.org/video/2365530605/
Before change
Full Episode
Episode 5 | Preview
Season 3 | Episode 4 Preview
July 17, 2015
After change
To Catch A Comet - Full Episode
The Crimson Field - Episode 5 | Preview
Last Tango in Halifax - Season 3 | Episode 4 Preview
Charlie Rose The Week - July 17, 2015

pbs: fix vague 'Full Episode' titles; prepend name of show

---

youtube_dl/extractor/tagesschau.py

I found that currently only tagesschau videos are played. There are some
more shows hosted on tagesschau.de (see [0] for example) which are
easily playable by adjusting the regex. So this patch adds support for:
* tagesthemen
* tagesschau vor 20 Jahren
* tagesschau (mit Gebärdensprache)
* nachtmagazin
Note that some videos don't provide a description, so in order for the
tests to succeed, an ExtractorError needs to get caught.
[0]: http://www.tagesschau.de/multimedia/video/videoarchiv2~_date-20150714.html

[tagesschau] add support for more video types

---

youtube_dl/extractor/common.py
youtube_dl/extractor/youtube.py

From the 't=*' in the url.
Currently youtube-dl doesn't use the value, but it was requested for the mpv plugin (https://github.com/mpv-player/mpv/issues/1519).

[youtube] Extract start_time

---

youtube_dl/utils.py

I just stumpled upon those two lines which are absolutely redundant, as the parameters are set in the constructor for every class instance. At the same time, class parameters and instance parameters are very different things in python so this might even cause harm :)

Remove redundant (and wrong) class parameters

---

youtube_dl/extractor/bbc.py

Prior to merge BBCNewsIE from pr #6026 was rewritten into BBCIE in 9afa177. Support was added for non-news
sites (/travel, /sports), however support for the news mediaselector was removed to support these sites.
This removed support for .mp4.
pr #6026 ( news site, news mediaseletor : http://open.live.bbc.co.uk/mediaselector/4/mtis/stream/ )
format code                                          extension  resolution note
journalism_nonuk_stream_h264_flv_200_akamai          flv        400x224    h264@ 176k, 1001.77KiB
journalism_nonuk_stream_h264_flv_400_akamai          flv        400x224    h264@ 512k, 2.85MiB
journalism_nonuk_stream_h264_flv_med_akamai          flv        640x360    h264@ 800k, 4.43MiB
journalism_nonuk_stream_h264_flv_hi_akamai           flv        688x384    h264@1500k, …

BBCIE: Fix missing .mp4 formats on news sites

---

youtube_dl/downloader/f4m.py
youtube_dl/downloader/fragment.py
youtube_dl/downloader/hls.py

* Adds a base file downloader class to be used by fragmented media file downloaders (e.g. f4m/m3u8 manifests).
* Rewrites `F4mFD` and `NativeHlsFD` in terms of `FragmentFD`.
* Adds generic progress output and resume for `NativeHlsFD`.

Generalized fragmented media file downloader

---

test/test_YoutubeDL.py
youtube_dl/YoutubeDL.py

Alternative to #6461, it's quite more complex but it handles all unused operators, not just '-'.

[YoutubeDL] format spec: correctly handle dashes and other unused operators

---

youtube_dl/extractor/youtube.py

It seems that youtube-dl prefers the second (yes, I tested it) v= argument in an URL, while python `parse_qs` and the youtube site itself seem to prefer the first one, which could cause discrepancies in the shown video. This could cause unwanted rickrolling, and who wants that?
This seems to be caused due to the `(?:.*?&)` part of the regex, that does the pre-`v=` arguments handling, is greedy and causes it to match the first `v=`, while the second match is then used to match the plain `v=` afterwards.

[youtube] Use the first v= argument in the URL

---

README.md

These two links no longer point to the the part of the file they originally referenced. This commit updates them.

Updated line numbers in the fragment portion of README links.

---

youtube_dl/extractor/youtube.py

It was always extracting 'new' as the version, breaking the cache system.
(see https://github.com/rg3/youtube-dl/pull/6671#issuecomment-134999601)
Probably, it should fix #6451.

[youtube] Adapt player version regex to handle urls ending in '/html5player-new.js'

---

youtube_dl/downloader/f4m.py

When opening a fragment file for reading, we must apply the same encoding to the filename as http_dl.download() that wrote the file. Trying to open an unencoded fragment file name may raise an UnicodeEncodeError if the filename contains characters that can't be encoded on the current locale.
This test case attempts to download a video whose title contains UTF-8 characters on C locale:
```
export LOCALE=C
export LC_CTYPE=C
python -m youtube_dl 'http://www.svtplay.se/video/2662623/ett-harligare-liv/ett-harligare-liv-sasong-1-avsnitt-20'
```
Without this patch the downloading fails with the following backtrace:
```
[SVTPlay] 2662623: Downloading JSON metadata
[SVTPlay] 2662623: Downloading f4m manifest
[SVTPlay] 2662623: Downloading m3u8 information
[download] Downloading f4m manifest …
```

[f4m] Fix encode error by sanitizing fragment filenames

---

youtube_dl/utils.py

Working around [python 2 bug](http://bugs.python.org/issue17849) by limiting expected HTTP responses to meet HTTP/1.0 or later.

[utils] Strict HTTP responses (Closes #6727)

---

youtube_dl/downloader/external.py

if i didn't set `--no-check-certificate` the value of `param` is `False` then it pass this condition:
```python
if isinstance(param, bool):
```
that makes it apply regardless of setting it or not.
so i added this condition to fix it:
```python
or param is False
```

[downloader/external] Respect --no-check-certificate for curl and aria2c and --proxy for curl

---

youtube_dl/extractor/aljazeera.py

the video is working it just not accessible from travis-ci
```
http://www.aljazeera.com/programmes/the-slum/2014/08/deliverance-201482883754237240.html
[AlJazeera] deliverance-201482883754237240: Downloading webpage
[Brightcove] 3792260579001: Downloading webpage
[Brightcove] 3792260579001: Extracting information
[download] Destination: The Slum - Episode 1 - Deliverance-3792260579001.mp4
[#8402c7 8.0MiB/1.5GiB(0%) CN:16 DL:238KiB ETA:1h49m14s]
```
in travis-ci log:
```
======================================================================
ERROR: test_AlJazeera (test.test_download.TestDownload)
----------------------------------------------------------------------
File "/home/travis/build/rg3/youtube-dl/test/test_download.py", line 141, in test_template …
```

[ajazzera] skip test

---

youtube_dl/extractor/shahid.py

fix the HTTP Error 401 in python 3:
```
[Shahid] 90389: Downloading webpage
[Shahid] 90389: Downloading player JSON
[Shahid] 90389: Downloading m3u8 information
[Shahid] 90389: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
it happens because encoding url arguments result in urls like that:
```
http://api.shahid.net/api/v1_1/episode/90389?b'apiKey=sh%40hid0nlin3&hash=b2wMCTHpSmyxGqQjJFOycRmLSex%2BBpTK%2Fooxy6vHaqs%3D'
```

[shahid] fix api request url and change test ext

---

youtube_dl/extractor/xhamster.py

xHamster does not just use “Free Porn”. The fix for #6944 in 4395ca2 is not complete. If you look at the titles from the `_TESTS` in the extractor file you will find:
* (%title), HD Porn: xHamster
* (%title), Free Celebrity Porn: xHamster
* (%title), Free Amateur Porn: xHamster
Some others I have seen:
* (%title), Free Asian Porn: xHamster
* (%title), Porn: xHamster
The new title structure is “Porn: xHamster” with an **optional** one or 2 word descriptor. I think this pull should cover all possible titles.

More title extraction fixing.

---

youtube_dl/extractor/ruutu.py

Fixes issue #7037.
If there's no resolution attribute in xml, only width gets a
value, height doesn't and ValueError is raised.

[ruutu] Fix ruutu extractor bug #7037

---

youtube_dl/extractor/vimeo.py

It seems that Vimeo has a new page design, that is served only by some servers. Which makes this super hard to debug, but you repeat extracting info for a Vimeo video, you will get an error like this:
```
$ PYTHONPATH=`pwd`  ./bin/youtube-dl --verbose --list-formats 'https://vimeo.com/72895266'
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://vimeo.com/72895266']
[debug] youtube-dl version 2015.10.16
[debug] Git HEAD: 350c948
[debug] Python version 2.7.9 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[vimeo] 72895266: …
```

Extract config URL from (new?) React-based Vimeo's page

---

youtube_dl/extractor/vidme.py

```
$ PYTHONPATH=`pwd`  ./bin/youtube-dl --verbose --list-formats 'https://vid.me/dzGJ'
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://vid.me/dzGJ']
[debug] youtube-dl version 2015.10.16
[debug] Git HEAD: dd84175
[debug] Python version 2.7.9 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[Vidme] dzGJ: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call …
```

[vidme] Better error message for suspended vidme videos

---

youtube_dl/extractor/dailymotion.py

Fixes this:
```
$ PYTHONPATH=`pwd`  ./bin/youtube-dl --verbose --list-formats 'http://www.dailymotion.com/video/xhza0o'
[debug] Command-line args: [u'--verbose', u'--list-formats', u'http://www.dailymotion.com/video/xhza0o']
[debug] youtube-dl version 2015.10.16
[debug] Git HEAD: 59fe482
[debug] Python version 2.7.9 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[dailymotion] xhza0o: Downloading webpage
{u'duration': 68,
u'error': {u'code': u'DM007',
u'message': u'Search for <a target="_top" …
```

[dailymotion] Report errors from player v5

---

youtube_dl/extractor/neteasemusic.py

Switching to http://m5.music.126.net (original http://m1.music.126.net) fixes the download problem.

[neteasemusic] Fixes #7301

---

youtube_dl/extractor/youtube.py

YouTube video Q39EVAstoRM can't be downloaded because it contains the `yt:stretch` attribute with zero height:
```
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://www.youtube.com/watch?v=Q39EVAstoRM']
[debug] youtube-dl version 2015.11.27.1
[debug] Git HEAD: 78a55d7
[debug] Python version 2.7.10 - Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.3-0ubuntu0.15.10.1, ffprobe 2.7.3-0ubuntu0.15.10.1, rtmpdump 2.4
[youtube] Q39EVAstoRM: Downloading webpage
[youtube] Q39EVAstoRM: Downloading video info webpage
[youtube] Q39EVAstoRM: Extracting video information
[youtube] Q39EVAstoRM: Downloading DASH …
```

[youtube] Ignore yt:stretch with zero width/height

---

Makefile

If "python" is python 2.5 (or presumably older), building youtube-dl fails, even if the PYTHON environment variable has been set to a newer version of python, such as 2.7. See [this MacPorts bug report](https://trac.macports.org/ticket/49840). The solution is to fix the Makefile so that it always uses the PYTHON environment variable rather than sometimes calling "python".

Always use PYTHON env var in Makefile

---

youtube_dl/postprocessor/ffmpeg.py

When no `downloader` is passed to `FFmpegPostProcessor`
an exception was raised trying to get the prefer ffmpeg param.
AttributeError: 'NoneType' object has no attribute 'params'
This fixes and defaults to `False`.

[FFmpegPostProcessor] Default of prefer ffmpeg

---

youtube_dl/extractor/common.py

instead of:
```
m3u8_formats = self._extract_m3u8_formats(m3u8_url, video_id, 'mp4', m3u8_id='hls', fatal=False)
if m3u8_formats:
formats.extend(m3u8_formats)
f4m_formats = self._extract_f4m_formats(f4m_url, video_id, f4m_id='hds', fatal=False)
if f4m_formats:
formats.extend(f4m_formats)
```
just use:
```
formats.extend(self._extract_m3u8_formats(m3u8_url, video_id, 'mp4', m3u8_id='hls', fatal=False))
formats.extend(self._extract_f4m_formats(f4m_url, video_id, f4m_id='hds', fatal=False))
```
and may be even making mp4 as the default ext and hls as the default id for m3u8_formats
and hds as the default id for f4m_formats
if this acceptable i will change all the parts that use this two methods in the other extractors.

[common] simplify the use of _extract_m3u8_formats and _extract_f4m_formats

---

youtube_dl/extractor/common.py

a lot of times i see m3u8 formats have lower preference even if they have the same quality or better.
with this change i try to lower the preference only if required program is not available.

[common] lower (m3u8,rtmp,rtsp) format preference only if required program is not available

---

youtube_dl/extractor/common.py
youtube_dl/extractor/udemy.py
youtube_dl/extractor/videomore.py

This PR proposes some new optional fields to video info dictionary in order to cover the gap for videos organized to logical chapters and video episodes belonging to season of a series or a programme.
Field | Usage | Description
------------ | ------------- | -------------
`chapter` | chapter-only | Name or title of the chapter the video belongs to.
`chapter_number` | chapter-only | Number of the chapter the video belongs to, as an integer.
`chapter_id` | chapter-only | Id of the chapter the video belongs to, as a unicode string.
`series` | series-only | Title of the series or programme the video episode belongs to.
`season` | series-only | Title of the season the video episode belongs to.
`season_number` | series-only | Number of the season the video episode belongs to, as an integer. …

Introduce chapter and series fields

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/rte.py

While here, correct RteIE filename extension to .flv as this is the
container format F4mFD outputs.

[extractor/rte.py] Add support for RTE radio player

---

youtube_dl/extractor/xhamster.py

After #6955, I am back with another fix.
I ran into a page with the title `(%title), Free Amateur Porn Video 92`. I have no idea why the xHamster brand was dropped there completely. As I did not want to overflow the `title` tag parser, I updated the regex targetting the `h1`. It had become outdated.
I haven’t done any long time testing to see if *all* `h1` tags have been changed, so I made the change optional.

Extract xHamster title fix

---

test/test_YoutubeDL.py
youtube_dl/YoutubeDL.py

If someone is running youtube-dl on a server to deliver files, the user could input 'file:///some/important/file' and youtube-dl would save that file as a video giving access to sensitive information to the user.
'file:' urls can be filtered, but the user can use an URL to a crafted m3u8 manifest like:
#EXTM3U
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.0
file:///etc/passwd
#EXT-X-ENDLIST
With this patch 'file:' URLs raise URLError like for unknown protocols.

[YoutubeDL] urlopen: disable the 'file:' protocol (#8227)

---

youtube_dl/YoutubeDL.py

Auto generate title fields corresponding to the *_number fields when missing in order to always have clean titles. This is very common for TV series.

[YoutubeDL] Auto generate title fields corresponding to the *_number fields

---

youtube_dl/YoutubeDL.py

As pointed out by #8130, codec names like ```avc1.640028``` is difficult for format selection. I borrow some ideas from [CSS3 selectors](http://www.w3.org/TR/css3-selectors/#selectors). Here's an usage example:
```
$ youtube-dl -j -f 'worstvideo[vcodec^=avc1]' test:youtube | jq .format
"160 - 256x144 (DASH video)"
```
Currently there are no tests. I'll fill them up if this idea is acceptable.

[WIP] Introduce CSS3 like string operators

---

test/test_update.py
test/versions.json
youtube_dl/update.py

The rsa_verify code was vulnerable to a BB'06 attack, allowing to forge
signatures for arbitrary messages if and only if the public key exponent is
3.  Since the updates key is hardcoded to 65537, there is no risk for
youtube-dl, but I don't want vulnerable code in the wild.
The new function adopts a way safer approach of encoding-and-comparing to
replace the dangerous parsing code.

[update] fix (unexploitable) BB'06 vulnerability in rsa_verify

---

youtube_dl/extractor/common.py

fixes the broblem with smil manifests that contain m3u8 media playlists:
```
python2 __main__.py -F 'http://link.theplatform.com/s/dJ5BDC/eSDhwOPqdCjD?format=SMIL&mbr=true'
[ThePlatform] eSDhwOPqdCjD: Downloading SMIL data
[ThePlatform] eSDhwOPqdCjD: Downloading m3u8 information
[ThePlatform] eSDhwOPqdCjD: Downloading m3u8 information
[ThePlatform] eSDhwOPqdCjD: Downloading m3u8 information
[ThePlatform] eSDhwOPqdCjD: Downloading m3u8 information
[ThePlatform] eSDhwOPqdCjD: Downloading m3u8 information
[ThePlatform] eSDhwOPqdCjD: Downloading m3u8 information
[ThePlatform] eSDhwOPqdCjD: Downloading m3u8 information
[ThePlatform] eSDhwOPqdCjD: Downloading JSON metadata
[info] Available formats for eSDhwOPqdCjD:
format code  extension  resolution note
hls-meta-0   mp4        multiple …
```

[extractor/common] detect media playlist in _extract_m3u8_formats

---

test/test_YoutubeDL.py
youtube_dl/YoutubeDL.py

Added dot '.' for regex pattern to match more codecs, as pointed out by @aktau: https://github.com/rg3/youtube-dl/issues/6858

Regex pattern update to match more codecs (fixes #6858)

---

youtube_dl/extractor/gamekings.py

Some old videos that aren't on Vimeo are being uploaded to YouTube under the
'Gamekings Vault' channel. They use YouTube now for some videos as video
hosting instead of Vimeo or their own hosting. The first test failed to
succeed under the existing code, but works now by using the YouTube
extractor.
The Regex is changed to find the new gogoVideo JavaScript line with the
YouTube embed. Checking if there is a YouTube embed is done by a String
find, which is probably not the best method of checking this.
The URLs are also updated. Gamekings uses the `.nl` TLD now instead of `.tv`.

[Gamekings] Fix failed extraction and update URL

---

youtube_dl/postprocessor/ffmpeg.py

```
python2 __main__.py --add-metadata https://vimeo.com/70668043
[vimeo] 70668043: Downloading webpage
[vimeo] 70668043: Extracting information
[vimeo] 70668043: Downloading webpage
[vimeo] 70668043: Downloading JSON metadata
[vimeo] 70668043: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 9
[download] Destination: Ask Ash No. 1-70668043.mp4
[download] 100% of 9.83MiB in 00:41
[ffmpeg] Adding metadata to 'Ask Ash No. 1-70668043.mp4'
```
```
ffprobe Ask\ Ash\ No.\ 1-70668043.mp4 
ffprobe version 2.8.5 Copyright (c) 2007-2016 the FFmpeg developers
built with gcc 5.3.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl …
```

[ffmpeg] fix adding metadata when using m3u8_native(fixes #8350)

---

youtube_dl/downloader/dash.py
youtube_dl/extractor/common.py
youtube_dl/extractor/facebook.py
youtube_dl/extractor/vevo.py
youtube_dl/extractor/youtube.py

the implementation is based on the information from the ISO/IEC 23009-1:2014.
i added support for vevo.
it can also the segments from kaltura and bbc and concatenate the audio segments.
but there is a problem with video concatenation:
for bbc ffmpeg complain about an unsupported codec.
and for kaltura it said: `could not find corresponding track id 1`

Add generic support for mpd manifests(dash formats)

---

youtube_dl/extractor/mtv.py

RSS used instead of manifest files because it's exact to the millisecond
with the video I tested while in manifest it's only exact to the second.

[mtv] Extract duration from each playlist item

---

youtube_dl/extractor/twitch.py

Added the `allow_audio_only` tag to queries to support Audio_Only format for the Twitch extractor.
Requested in #8731.

[twitch] Support for "Audio_Only" format

---

youtube_dl/extractor/common.py
youtube_dl/utils.py

youtube-dl reports wrong file extensions for the video mentioned in #8764:
```
$ youtube-dl -vF https://twitter.com/INJO/status/705585226186149888
[debug] Command-line args: ['-vF', 'https://twitter.com/INJO/status/705585226186149888']
[debug] youtube-dl version 2016.03.01
[debug] Git HEAD: 845817a
[debug] Python version 3.5.1 - Linux-4.4.3-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: avconv v12_dev0-2434-gf6ccee9, avprobe v12_dev0-2434-gf6ccee9, ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[twitter] 705585226186149888: Downloading webpage
[twitter:card] 705585226186149888: Downloading webpage
[twitter:card] 705585226186149888: Downloading m3u8 …
```

Detect file extensions of DASH formats from their codecs

---

Makefile

It's the portable version of BSD make: http://crufty.net/help/sjg/bmake.html
The syntax for conditionals is different in GNU make and BSD make, so we use the shell
Since we don't use any other special feature of GNU make, I think it's nice to support both.

Makefile: make it compatible with bmake

---

youtube_dl/__init__.py
youtube_dl/downloader/common.py
youtube_dl/downloader/dash.py
youtube_dl/downloader/fragment.py
youtube_dl/options.py

**Abstract**
Introduces a new option `--fragment-retries` for retrying fragments in fragment based downloaders (yet DASH segments only) with default value of 10 retry attemps.
**Rationale**
YouTube may often return 404 HTTP error for a fragment in DASH segments downloader causing the whole download to fail. However if the same fragment is immediately retried with the same request data this usually succeeds (1-2 attemps is usually enough for success) thus allowing to download the whole file successfully. So, we will retry all fragments that fail with 404 HTTP error for now.
**Example URLs**
Example videos I've been able to reproduce failing fragments with: RTwddp2uIu0 ImiqwgpbQuQ. Videos uploaded to YouTube in a last hour are also very likely to be DASH segments with failing fragments. …

Add --fragment-retries option (Fixes #8466)

---

youtube_dl/downloader/external.py
youtube_dl/postprocessor/ffmpeg.py

proposed the solution 14 days ago in https://github.com/rg3/youtube-dl/issues/2124#issuecomment-204072217.
as i understand from the issue the problem was that HLS live or AES encrypted streams can't be streamed to external software this should fix this problem.

[downloader/external] enable piping for FFmpegFD(closes #2124)

---

youtube_dl/extractor/common.py

this is related to this issue https://github.com/rg3/youtube-dl/issues/4142 it should prevent the 403 problem.
do not extract formats from manifest that need to decrypt the playerVerificationChallenge
for example this manifest from this url http://pluzz.francetv.fr/videos/des_jours_et_des_vies_ep3799_,125800219.html contain this pv-2.0:
```
ZXhwPTE0MzgzNTM0MTh+YWNsPSUyZip+ZGF0YT1wdmMsc35obWFjPWQ0NjJhNTBmYTQ3NjY3YTNhOTNjNmFmYjkyMTZkMzY5Y2Y2ODE5MjJlOTVlMWQ4NmU1MGM1OTZjY2MxMDcwYWU=;hdntl=exp=1438353418~acl=%2fz%2fstreaming-adaptatif_media-secure_france-dom-tom%2f2015%2fS31%2fJ3%2f125800219-55b882629a8d2-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil*~data=hdntl~hmac=df6e06dc773f6b93d80e9352b4eef4048d138c88c68416b37b20ae0f027d29e3
```
the first part before the `;` is the …

[extractor/common] do not process f4m manifest that contain akamai playerVerificationChallenge

---

youtube_dl/extractor/common.py
youtube_dl/extractor/vlive.py

Fixes #9321 
This is WIP, I don't know how to handle HLS subtitles yet. But otherwise everything seems to be working.

[vlive] Add support for live videos

---

youtube_dl/extractor/liveleak.py

Added support for fetching the video thumbnails, the only issue is concerning the third extractor test. When I run youtube-dl on that url using the --get-thumbnail flag it warns me that it is falling back to the default extractor. I'm not sure if this is an issue with the extractor or if this is expected. I didn't add the thumbnail url into that test but it seems the rest work just fine.

[liveleak] Adds support for thumbnails and updates tests

---

youtube_dl/extractor/eporner.py

Recently eporner slightly changed the URL layout, the ID that used to
be digits only are now digits and letters, so youtube-dl falls back to the
generic extractor that doesn't work.
Fix the matching regex to allow letters in ID.

[eporner] fix for the new URL layout

---

test/test_utils.py
youtube_dl/utils.py

The recently introduced support for replacing accented characters with non-accented ones covers Hungarian language almost completely, missed only these letters.
A test case would be (with --restrict-filenames, of course): https://www.youtube.com/watch?v=XygJiqezhU8

Added sanitization support for Hungarian letters Ő and Ű

---

README.md

The README already mentions that youtube-dl can be installed using Homebrew (one of the third-party OS X package managers). This pull request adds information on how to install youtube-dl using MacPorts (another OS X package manager).
(I am the maintainer of the youtube-dl port in MacPorts.)

Update README.md to mention MacPorts

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/wdr.py

The WDR relaunched their site on 2016-02-23 which not only changed the
URL-schema completely but also the layout of their pages.
Apparently the whole "mediathek" now runs on the wdr-domain, so no
separate URL for funkhauseuropa anymore.
There seems to be no explicit handling of video-sizes on the page or in
the URLs anymore. There seems to be only one size for HTML5, but still
several sizes for flash. The new extractor adds all to the list of formats.
There is no metadata for the HTML5-stream, so that the best flash-stream
will always be considered as the "best" format. At least in my tests
this seemed to be true anyway.
As this is my first extractor please let my know if I did anything wrong or
missed something.
I was not sure about the tests, currently they are of course working, but …

[WDR] complete overhaul after relaunch of the site (also fixes #8562)

---

youtube_dl/extractor/afreecatv.py
youtube_dl/extractor/extractors.py

afreecatv.com is a Korean streaming service. This adds support for handling afreeca VODs but it does not handle any live stream URLs.
This resolves #2026, #3611, #2054, but the videos for all three of those issues no longer exist.

[afreecatv] Add new extractor for afreecatv.com VODs

---

youtube_dl/extractor/facebook.py

youtube-dl expects the format items to be returned as a list,
but when there's only one item Facebook returns a dict instead,
this wraps the dict in a list if necessary

Fix issue #9854 with downloading Facebook videos

---

youtube_dl/extractor/polskieradio.py

---
This is a simple change to extract thumbnails from Polskie Radio auditions.

[polskieradio] Add thumbnails.

---

youtube_dl/postprocessor/ffmpeg.py

Change command line parameters for ffmpeg when embedding subtitles.
Change to ‘-map 0:v -c:v copy -map 0:a -c:a copy’

[ffmpeg] Fix embedding subtitles (#9063)

---

youtube_dl/extractor/xiami.py

---
Before applying this patch, when downloading resources from xiami.com, it crashes with these:
```
File "/home/phi/.local/bin/youtube-dl", line 11, in <module>
sys.exit(main())
File "/home/phi/.local/lib/python3.5/site-packages/youtube_dl/__init__.py", line 433, in main
_real_main(argv)
File "/home/phi/.local/lib/python3.5/site-packages/youtube_dl/__init__.py", line 423, in _real_main
retcode = ydl.download(all_urls)
File "/home/phi/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1786, in download
url, force_generic_extractor=self.params.get('force_generic_extractor', False))
File "/home/phi/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
ie_result = ie.extract(url)
File …
```

[xiami] bug fix for extractor xiami.py

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/polskieradio.py

This extends the Polskie Radio (the Polish national radio) extractor to enable the user to download all the broadcasts of a single programme at once.

[polskieradio] Add support for downloading whole programmes

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/polskieradio.py

A continuation of #10443.
This extends the Polskie Radio (the Polish national radio) extractor to enable the user to download all the broadcasts of a single programme at once.

[polskieradio] Add support for downloading whole programmes.

---

youtube_dl/extractor/instagram.py

---
---
This adds support for comments extraction for Instagram

[Instagram] Extract comments

---

youtube_dl/postprocessor/ffmpeg.py

If the converted audio file already exists, the `FFmpegExtractAudioPP.run` method returns the original video filepath instead of the converted audio filepath and ext which is the expected behavior, so if we set the filepath and the ext before checking if the file already exists it will return the correct values:
```python
information['filepath'] = new_path
information['ext'] = extension
if (new_path == path or
(self._nopostoverwrites and os.path.exists(encodeFilename(new_path)))):
self._downloader.to_screen('[ffmpeg] Post-process file %s exists, skipping' % new_path)
return [], information
```

[FFmpegExtractAudioPP] info dict return audio filepath and ext instead of the video filepath if file already exists

---

youtube_dl/extractor/adobepass.py

---
---
Add support for --ap-mso Comcast_SSO. Comcast varies the page flow depending on the site you are visiting and whether or not you are using Comcast's network. If you are on Comcast's network some sites allow auto-login but some present a login form. There are at least 2 flavors of redirect in use to get to the login page. If you are logging in from outside the Comcast network, you may or may not be required to respond to a confirmation page after the login. 
Partially addresses issue #10803

[adobepass] Add Comcast

---

youtube_dl/extractor/openload.py

---
They changed "decryption" code a little. Here is current one. 
``` js
var y = $("#yJ7n4OuuU7").text();
var magic = y.slice(-1).charCodeAt(0);
y = y.split(String.fromCharCode(magic - 1)).join("	");
y = y.split(y.slice(-1)).join(String.fromCharCode(magic - 1));
y = y.split("	").join(String.fromCharCode(magic));
var s = [];
for (var i = 0; i < y.length; i++) {
var j = y.charCodeAt(i);
if ((j >= 33) && (j <= 126)) {
s[i] = String.fromCharCode(33 + ((j + 14) % 94));
} else {
s[i] = String.fromCharCode(j);
}
}
var tmp = s.join("");
var str = tmp.substring(0, tmp.length - 1) + String.fromCharCode(tmp.slice(-1).charCodeAt(0) + 2);
```
They've added (funny code if you ask me) 
``` js
var magic = y.slice(-1).charCodeAt(0);
y = y.split(String.fromCharCode(magic - 1)).join("  ");
y = …
```

[openload] Fix extraction.

---

youtube_dl/utils.py

---
youtube-dl hangs when backgrounded because ffmpeg -version tries to read from stdin:
```
pb3:youtube-dl jhawk$ python -m youtube_dl -v 'BaW_jenozKc' &
[1] 4263
pb3:youtube-dl jhawk$ [debug] System config: []
[debug] Command-line args: [u'-v', u'BaW_jenozKc']
[debug] youtube-dl version 2016.10.21.1
[debug] Git HEAD: 69c2d42
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[1]+  Stopped                 python -m youtube_dl -v 'BaW_jenozKc'
pb3:youtube-dl jhawk$ jobs -l
[1]+  4263 Stopped (tty output): 22python -m youtube_dl -v 'BaW_jenozKc'
pb3:youtube-dl jhawk$ pstree 4263
-+= 04263 jhawk python -m youtube_dl -v BaW_jenozKc
\--- 04271 jhawk ffmpeg -version
pb3:youtube-dl jhawk$ …
```

Fix hang when backgrounded

---

youtube_dl/extractor/vessel.py

---
---
Fix for Vessel videos including '-' and '_' characters in their ID. 
Youtube-dl would improperly extract video IDs with a '-' and/or '_' characters in their URL like such as
https://www.vessel.com/videos/F01_dsLj1
https://www.vessel.com/videos/RRX-sir-J

[Vessel] Fix for Vessel video IDs

---

youtube_dl/YoutubeDL.py
youtube_dl/downloader/__init__.py
youtube_dl/downloader/ism.py
youtube_dl/extractor/common.py
youtube_dl/extractor/microsoftvirtualacademy.py
youtube_dl/extractor/msn.py
youtube_dl/extractor/onet.py
youtube_dl/extractor/tvp.py

add only a basic support for the protocol.
it does not support:
- live streams.
- downloading manifests that contain codecs other than AVC and AAC(support for other codecs has a lower priority as most of the manifests contain the supported codecs).
- some of the manifests doesn't produce valid files like in arkena extractor(not sure what's the problem).
- some of the cases where not tested as i don't have examples(like manifests with segment repeat attribute, audio with more than 2 channels...).

add Basic support for Smooth Streaming protocol(#8118)

---

youtube_dl/extractor/vlive.py

---
The extractor was using language e.g. ``zh`` as the subtitle language, this doesn't distinguish between variants like ``zh_CN`` and ``zh_TW``.
```
$ # Before
$ python -m youtube_dl --list-subs "http://www.vlive.tv/video/16937"
[vlive] 16937: Downloading webpage
[vlive] 16937: Downloading JSON metadata
Available subtitles for 16937:
Language formats
el       vtt
en       vtt
zh       vtt
pt       vtt
vi       vtt
ko       vtt
th       vtt
in       vtt
ja       vtt
es       vtt
$ # After
$ python -m youtube_dl --list-subs "http://www.vlive.tv/video/16937"
[vlive] 16937: Downloading webpage
[vlive] 16937: Downloading JSON metadata
Available subtitles for 16937:
Language formats
th_TH    vtt
ko_KR    vtt
pt_BR    vtt
zh_CN    vtt
zh_TW    vtt
vi_VN    vtt
ja_JP    vtt
en_US    vtt
el_GR …
```

[vlive] Use locale as subtitles language key instead

---

youtube_dl/__init__.py

---
---
Avoid striping urls read from batch files as they are already striped.

Strip only args urls

---

youtube_dl/extractor/mtv.py
youtube_dl/extractor/spike.py

---
---
Currently, trying to use `youtube-dl` (version 2016.11.27) to download a full episode from Spike results in the exception:
```RegexNotFoundError: Unable to extract video url```
I've added some code so that if the conventional MGID detection fails, it falls back to searching for the mobile app's custom URL format (`spikenetworkapp://$video_type/$episode_uuid`) - both variables from the URL can be used to generate a valid MGID.

[spike] Extract MGID via custom mobile URL

---

youtube_dl/extractor/liveleak.py

- Put an `x` into all the boxes [ ] relevant to your _pull request_ (like that [x])
- Use _Preview_ tab to see how your _pull request_ will actually look like
---
---
Example Post Link : http://m.liveleak.com/view?i=763_1473349649
Earlier youtube-dl was throwing error as it was not able to recognise embedded youtube video. I have updated the corresponding regex to support youtube as well.

Add support for youtube embedded post in LiveLeak IE

---

youtube_dl/extractor/pandoratv.py

---
Apparently, pandora.tv has changed the way the data is retrieved, so previous extractor is not completely usable. This pull request adds the necessary steps to get the direct media link. Specifically, this link must have a timestamp and hash code which the code added now obtains. More info can be found here #11023

Pandoratv extractor fix

---

devscripts/buildserver.py

---
`HTTPError` extends `BuildError`, so it will always be caught by the above `except` block, never reaching the more specific one. The `BuildError` handler appears to behave in functionally the same way as the one for `HTTPError` so the one for `HTTPError` can be removed.

Remove unreachable except block.

---

README.md

Hi! :)
It's not always a default behaviour, but when you use `sudo pip` you most likely may want to use `-H` flag to set HOME value to directory of the target user. :)

Update Readme: Set HOME properly in install command

---

youtube_dl/extractor/brightcove.py

Found using [pydiatra](https://github.com/jwilk/pydiatra).

[brightcove] Fix misplaced backslash in a regexp

---

youtube_dl/extractor/naver.py

---
Naver switched to `tv.naver.com` links (also redirects from `tvcast.naver.com` to `tv.`).
Example link: http://tv.naver.com/v/1379289

[naver] Support tv.naver.com links

---

youtube_dl/extractor/youtube.py

---
---
This pull request fixes bug #11604.
The issue at hand is the fact that YouTube's page structure has changed such that the previous method of checking whether the playlist exists/is private ceased working. The notice now looks like this:
```html
<div class="yt-alert-message" tabindex="0">
This playlist is private.
</div>
```
the old method only checks for `<div class="yt-alert-message">` and thus broke.

[youtube:playlist] Fix 'this playlist doesn't exist/is private' error not working (#11604)

---

youtube_dl/extractor/npo.py

NPO websites changed the domain they used for subtitles, from e.omroep.nl to tt888.omroep.nl.
I have:
---
I noticed I couldn't download subtitles anymore with the npo extractor. In the browser I noticed the subtitles were there in the video. So I just inspected my network, found out the new URL, tested on youtube-dl, and it worked.
Example before my patch:
````
$ youtube-dl -v --all-subs http://www.npo.nl/jinek/25-01-2017/KN_1687315
[debug] Command-line args: [u'-v', u'--all-subs', u'http://www.npo.nl/jinek/25-01-2017/KN_1687315']
[debug] youtube-dl version 2017.01.02
[debug] Python version 2.7.13 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe …
```

[npo] Update subtitles url

---

youtube_dl/extractor/common.py
youtube_dl/extractor/infoq.py

Refactor cookie code into a function.
Renamed formats to http_video, http_audio, rtmp_video
Renamed extract functions to video instead of videos as they return
one or no video.
---
---
Add audio only format for InfoQ extractor if available

[infoq] Add audio only format if available

---

youtube_dl/extractor/piksel.py

Support alternative api token found as
<video ... data-de-api-key="bd1863e1-a59e-11e3-bfa8-005056865f49" ...>
in addition to extraction from the flashvars JSON.
This supports the player as invoked from uscourts.gov, e.g. [http://www.uscourts.gov/cameras-courts/state-washington-vs-donald-j-trump-et-al](http://www.uscourts.gov/cameras-courts/state-washington-vs-donald-j-trump-et-al)
Add test case for same.

[Piksel] app token in <video> (uscourts.gov)

---

youtube_dl/utils.py

---
Fixes #11540 
More exactly it's a workaround, not a fix, but people shouldn't be forced to use a months old version just because of a TypeError in a LoadLibrary that isn't even relevant in Windows.
Also recommend using Python2 for the official builds, since using 3.4.4 (more than a year old) is probably one of the bigger reasons why [this error](https://github.com/rg3/youtube-dl/issues?q=is%3Aissue+CERTIFICATE_VERIFY_FAILED+is%3Aclosed) is so prevalent in Windows lately.

utils.py: Workaround TypeError with Python 2.7.13 in Windows

---

youtube_dl/extractor/vidzi.py

---
Vidzi also uses the `vidzi.cc` domain. It appears to work exactly like `vidzi.tv`.

also allow vidzi.cc videos

---

test/test_YoutubeDL.py
youtube_dl/YoutubeDL.py
youtube_dl/compat.py

Just not to forget.
This was an implementation for #5185 made some time ago. The main concern is ugly and brittle approach of patching output templates for missing fields. However not sure what are the alternatives if any.

String formatting operations in output template

---

youtube_dl/extractor/crunchyroll.py

---
---
Provide the Crunchyroll extractor with the ability to extract uploader
names that aren't links. Add a test for this new functionality.
This fixes #12267.

[Crunchyroll] Allow extractor to extract uploader name that's not a link

---

youtube_dl/downloader/external.py

Otherwise, if you screw up a playlist test by including a playlist
dictionary key, you'll be there for eons while it downloads all the
files before erroring out.
Other downloaders check for running under the test harness and enforce a 10k limit.
Found while working on  #12361, where this test:
```
_TEST = {
'url': 'http://www.cbs.com/shows/the-late-show-with-stephen-colbert',
'info_dict': {
'id': 61456254,
'title': 'The Late Show with Stephen Colbert',
},
'playlist_mincount': 14,
'playlist': [{
'info_dict': {
'id': 'xxx',
'ext': 'xxx.mp4',
},
}],
}
```
would download hours and hours of video before erroring out (or maybe succeeding).

[external:ffmpeg] In test harness, Limit to 10k download size

---

youtube_dl/extractor/wdr.py

---
---
This only fixes existing extractors for WDR.
The first commit enables youtube-dl to download videos from http://www.wdrmaus.de/aktuelle-sendung/index.php5 . The breakage was not detected because the test is marked as "skip". If you adapt the ID temporarily + remove the skip you will see that the first commit fixes the test.
The 2nd+3rd commits fix breaking tests which are visible in all travis builds.

[wdr] fix two failing tests (and a skipped one)

---

youtube_dl/extractor/bostonglobe.py
youtube_dl/extractor/common.py
youtube_dl/extractor/extractors.py
youtube_dl/extractor/generic.py

BrightcoveNewIE.extract_urls(): Handle player data when it is all in
attributes of the <video> tag, and also the id is
data-brightcove-video-id not data-video-id.
Add test to generic extractor, note HEAD gives 404, no checksum computed(?).
---
Can someone explain to me why md5 checksums do not appear to be computed by the test harness in this case? Is this an issue with playlists, and can we document that?  I don't see an open issue, but it seems problematic if playlist tests can't be checksummed.

[Bostonglobe] New. Nonstandard version of Brightcove

---

test/test_download.py

It's rather inconvenient that the test run Travis uses gives output like this:
```
test_Generic (test.test_download.TestDownload) ... ok
test_Generic_1 (test.test_download.TestDownload) ... ok
test_Generic_10 (test.test_download.TestDownload) ... ok
test_GameSpot_1 (test.test_download.TestDownload) ... ok
test_Generic_100 (test.test_download.TestDownload) ... ERROR
test_Gazeta_1 (test.test_download.TestDownload) ... FAIL
test_Generic_103 (test.test_download.TestDownload) ... FAIL
test_Generic_101 (test.test_download.TestDownload) ... ok
test_Generic_104 (test.test_download.TestDownload) ... ok
test_Generic_106 (test.test_download.TestDownload) ... ok
test_Generic_102 (test.test_download.TestDownload) ... ERROR
```
This patch changes the test identifer to include the `add_ie` test …

[test_download] print additional IEs in summary output

---

youtube_dl/extractor/common.py
youtube_dl/extractor/generic.py
youtube_dl/extractor/tvnoe.py

_find_jwplayer_data() assumes setup() is called with JSON, but it (sometimes?)
gets a variable that contains that expected JSON object.
This commit detects that by check for the first character being "{" and, if not,
resolving the variable to the JSON string.

Fix "'str' object does not support item assignment"

---

youtube_dl/extractor/openload.py

---
---
Fixes #10408, for now. I've translated [deobfuscated](https://gist.github.com/Tithen-Firion/7ecd8cf00cfcde1955e0be7027d4bf23) JavaScript to Python and tweaked it a bit. Problematic part was `parseInt` since it can return `NaN` from empty string. Python's `int` will just throw `ValueError`. I've solved it with `or '0'` but it wont work in this case:
```javascript
var a = parseInt(''); // NaN
var b = a + 3;        // NaN again, same for `3 + a`
var c = b & 1;        // 0, same for `1 & b`
```
```python
a = int('' or '0') # 0
b = a + 3 …
```

[openload] fix extractor

---

test/test_download.py

As a relatively new contributor, I find it's easy to get confused when you write a test and don't specify the 'id' field correctly. E.g., if `id` is given as `1` instead of `1_1jc2y3e4`:
```
[download] Destination: test_Kaltura_1_1jc2y3e4.mp4
[download] 100% of 10.00KiB in 00:00
F
======================================================================
FAIL: test_Kaltura (__main__.TestDownload):
----------------------------------------------------------------------
File "test/test_download.py", line 205, in test_template
self.assertTrue(os.path.exists(tc_filename), msg='Missing file ' + tc_filename)
AssertionError: Missing file test_Kaltura_1.mp4
```
Whereas for most other fields, you get something much more intelligible:
```
Traceback (most recent call …
```

[test_download] Improve diagnostic on wrong 'id'

---

youtube_dl/extractor/generic.py
youtube_dl/extractor/kaltura.py

Note that these need to back to through the Generic extractor because
the iframe URLs may be redirects that cannot be parsed by `KalturaIE`
without being followed (as in this test), and Generic checks for such redirects and
follows them. Hence dropping the IE from `url_result()`.
---

[kaltura] Support iframe embeds, with test

---

youtube_dl/extractor/rbmaradio.py

It's been rebranded as "Red Bull Radio".
---
---
Fix downloads from Red Bull Radio (was Red Bull Music Academy).
They weren't being recognised by the extractor regex as the URL has changed.
Current master (90e3f18fc1cff2c12361cbbd85303774bf7d59f7) falls back to generic information
extractor and fails with …

Update RBMA Radio URL

---

youtube_dl/extractor/generic.py

Fixes #12637. Trivial.
**BUT** something is wrong with the #12680 test harness corrections, with or without the additional 80b2fdf9ac99ebcbd6eec87670aa6d646da7dac4 fixup.
```
pb3:extractor jhawk$ python ../../test/test_download.py -v TestDownload.test_Generic_44
test_Generic_44 (__main__.TestDownload) [Youtube]: ... [generic] untrained-modern-youths-and-ancient-masters-in-selfie-portraits: Requesting header
[generic] untrained-modern-youths-and-ancient-masters-in-selfie-portraits: Downloading webpage
[generic] untrained-modern-youths-and-ancient-masters-in-selfie-portraits: Extracting information
[download] Downloading playlist: Improbable Research » Blog Archive
[generic] playlist Improbable Research » Blog Archive: Collected 1 video ids (downloading 1 of them)
[download] Downloading …
```

[Generic] Youtube <object> embed

---

test/test_utils.py
youtube_dl/utils.py

adds support for converting ttml styles to html tags supported in srt subtitles(ffmpeg implementation https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/htmlsubtitles.c), tested mainly on bbc iplayer videos(most of the subtitles has different styles for the main characters).

[utils] add support for ttml styles

---

test/test_utils.py
youtube_dl/utils.py

---
---
---
`\s` in Python 2.x doesn't match unicode whitespace characters by default.
Closes #12903.

[utils] Fix inconsistent output of clean_html

---

youtube_dl/extractor/bandcamp.py

---
Add a new type of link to _VALID_URL with a test. I was not sure whether all those info_dict fields are needed for the second test, but just added them.

[Aljazeera] improve _VALID_URL

---

youtube_dl/extractor/adobepass.py

---
---
Bright House Networks was the third company in the creation of Spectrum, but while Charter and Time Warner both had entries added to adobepass.py, Bright House hadn't.  Trying to use the Bright House credentials grandfathered into Charter fail to authenticate.
I've tested with FOX to verify that episodes requiring cable provider login to view work with this change.  I couldn't verify on ABC Go or Discovery Go, as it looks like they're either not set up to handle Adobe Pass or require more than that to access locked videos.

adobepass.py: add Bright House (Spectrum)

---

youtube_dl/extractor/youtube.py

---
---
Fixes Issue #8944 - ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError());  
The get_video_info API endpoint requires the 'sts' parameter be included, otherwise the decoding of the signature will fail.
Adding this parameter doesn't affect other videos without encoded signatures. 
If the sts regex doesn't match, then the code will fail like it currently does.

[youtube] Fixes issue with not being able to decode signatures on DASH MPD URLs (#8944)

---

youtube_dl/YoutubeDL.py

---
---
WinNT can have the TERM variable set for various reasons such as msys, cygwin, WSL, and in the future perhaps more reasons and complications, and if so, youtube-dl will print non-compatible ansi sequences that produce garbage on the command prompt.  This adds an os check before trying to print ansi sequences to save and restore the console title.

Check if OS is NT before checking TERM variable

---

youtube_dl/extractor/watchindianporn.py

---
Fix #13411. Note that uploader, upload_info and comment_count  infos are no more present in the service.

[watchindianporn] Fix parser

---

youtube_dl/extractor/cbsnews.py

---
- [x ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ x] Bug fix
---
Updated the regex for the [CBSNews] extractor to …

[CBSNews] Fixed regex for news videos (fixes issue #13284)

---

youtube_dl/extractor/espn.py

---
- [x ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ x] Bug fix
---
Updated the regex for the [ESPN] extractor to …

[ESPN] Include additional URL formats (fixes issue #13244)

---

youtube_dl/extractor/npo.py

NPO Live has a new page with the ID stored somewhere else. The regex for
fetching the ID is now updated for the new site.
Fixes #13568
---
---
This fixes issue #13568 
The regex has been updated to fix the extraction issue which was caused by a site update.

[npo] fix live stream id regex

---

youtube_dl/extractor/veoh.py

---
---
Fixes several previous bug reports (that all get closed) about veoh extractor not working. Specifically it allows veoh extractor to recognize and download this link: http://www.veoh.com/watch/e152215AJxZktGS

Add support for older-style veoh links

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/vlive.py

---
---
A couple more examples of vlive playlists:
```
http://www.vlive.tv/video/24371/playlist/24384
http://www.vlive.tv/video/20928/playlist/20933
http://www.vlive.tv/video/16181/playlist/17079
```
The reason why there are two tests is because the webpages for the two are slightly different. The webpage for the video in the first test contains playlist information even if you remove the 'playlist' and playlist id segments of the URL. Whereas the second video doesn't contain playlist information if you remove the 'playlist' and playlist id …

[vlive:playlist] Add new extractor

---

youtube_dl/extractor/nick.py

---
---
This makes youtube-dl automatically bypass geo-restrictions for nick.com, without having to use `--geo-bypass-country US`. The other sites in this extractor do not appear to have geo-restrictions, I tried playing full episodes from them with a Hungarian IP.
Example URL: http://www.nick.com/the-thundermans/videos/parks-t-rex-s4-ep409-full-episode/

[nick] Automate geo-restriction bypass

---

youtube_dl/extractor/twentymin.py

---
Embedded videos for 20min.ch stopped working, because a change on their site:
```
youtube-dl -F "http://www.20min.ch/sport/dossier/superleague/story/-Was-hat-Pickel-dort-ueberhaupt-zu-suchen---23224018"
[generic] -Was-hat-Pickel-dort-ueberhaupt-zu-suchen---23224018: Requesting header
WARNING: Falling back on generic information extractor.
[generic] -Was-hat-Pickel-dort-ueberhaupt-zu-suchen---23224018: Downloading webpage
[generic] -Was-hat-Pickel-dort-ueberhaupt-zu-suchen---23224018: Extracting information
ERROR: Unsupported URL: http://www.20min.ch/sport/dossier/superleague/story/-Was-hat-Pickel-dort-ueberhaupt-zu-suchen---23224018
```
With this commit it works again as expected:
```
python -m youtube_dl -F "http://www.20min.ch/sport/dossier/superleague/story/-Was-hat-Pickel-dort-uebe …
```

[20min] Fix extractions for 20min embeds.

---

Makefile

to make build reproducible.
See https://reproducible-builds.org/ for why this is good.
Copying files to not interfere with freshness detection.

[build] Override timestamps in zip file

---

Makefile

---
---
The old version of BSD `cp` on the old Mac OS X 10.5 Leopard does not understand the `-a` flag. This PR changes the Makefile to use the equivalent `-pPR` flags.
Similarly, the old version of `zip` on Leopard does not understand the `--quiet` flag. This PR changes the Makefile to use the equivalent `-q` flag.
It builds on Leopard with these changes.

Fix build failures with old cp and zip

---

youtube_dl/extractor/radiocanada.py

---
RadioCanada extractor wasn't able to download videos from shows that had no titles in the metadata. A `len()` on a `NoneType` would be called raising an exception. I added a test. See it fail:
```
$ python test/test_download.py TestDownload.test_RadioCanada_1[radiocanada] 7754998: Downloading metadata XML
[radiocanada] 7754998: Downloading ipad XML
[radiocanada] 7754998: Downloading m3u8 information
[radiocanada] 7754998: Downloading flash XML
[radiocanada] 7754998: Downloading android XML
[radiocanada] 7754998: Downloading m3u8 information
[radiocanada] 7754998: Downloading f4m manifest
[radiocanada] 7754998: Downloading m3u8 information
[radiocanada] 7754998: Downloading f4m manifest
[radiocanada] 7754998: Downloading m3u8 information
[radiocanada] 7754998: Downloading f4m manifest …
```

[RadioCanada] Added support for TV shows without titles like evening news

---

youtube_dl/YoutubeDL.py

---
subtitles in `itv`(may be other websites as well) are encoded as `UTF-16`, encoding them as `UTF-8` causes problem when trying to use them.

[YoutubeDL] write raw subtitle files

---

devscripts/check-porn.py

---
---
check-porn was trying to import get_testcases from test.helper, but it does not exist in this package. gettestcases exists instead, which works when the code is run.

[generic] ImportError fix - change get_testcases to gettestcases in check-porn.py

---

youtube_dl/extractor/generic.py

Previously, multiple HTML5 videos on one page would lead to title conflicts, where every video had the same title and thereby only the first one would be downloaded ('video already downloaded').
This fixes #14080.

[generic] Fix support for multiple HTML5 videos on one page (#14080)

---

youtube_dl/extractor/nbc.py

Added fixes according to #13651 and user @remitamine
---
The code was initially posted by user @remitamine. @remitamine Please give you approval in this Pull Request.
---
Fixes the generic extraction problem of JSON data from NBC sites by adding a prefix to the URL to be downloaded. The code was first introduced by user @remitamine in the #13651 discussion.

Fix for JSON meta data download

---

youtube_dl/extractor/tvn24.py

---
Some TVN24 URLs, such as <https://www.tvn24.pl/magazyn-tvn24/angie-w-jednej-czwartej-polka-od-szarej-myszki-do-cesarzowej-europy,119,2158>, don't have the `.html` suffix. This PR makes the suffix optional.
This PR also relaxes the test regexp to allow HTTPS thumbnails. This fixes download test failure.

[tvn24] Don't require ".html" suffix

---

youtube_dl/extractor/common.py

---
This patch checks for missing data for the segment duration calculation, and if it's missing, raises a more specific error than just the generic type conversion failure.
Example of original error message from #14388:
```text
File "/…/ytdl-rg3/youtube_dl/extractor/common.py", line 1753, in _extract_mpd_formats
formats_dict=formats_dict, mpd_url=mpd_url)
File "/…/ytdl-rg3/youtube_dl/extractor/common.py", line 1925, in _parse_mpd_formats
representation_ms_info['total_number'] = int(math.ceil(float(period_duration) / segment_duration))
TypeError: float() argument must be a string or a number
```
NB [line 1923 of the old `youtube_dl/extractor/common.py`](https://github.com/rg3/youtube-dl/blob/bfd484ccff4ea9d16af9515416d4f35d14d5b41d/youtube_dl/extractor/common.py#L1923):
As far as I can …

MPD manifests: improve errmsg for missing duration

---

youtube_dl/extractor/pornflip.py

[PornFlip] Bug Fix (Closes #14405)

---

youtube_dl/extractor/hrti.py

* New URLs don't have `#`
Not sure if they kept the old ones, as a safe bet making the part of the regex just optional.

[HRTi] new urls are wihout #

---

youtube_dl/extractor/kaltura.py

---
---
There is currently no public method to decrypt this, and there may be other streams available that can be downloaded.
Example URL, has `.wvm` and `.mp4` formats: https://www.voot.com/shows/bigg-boss-s11/11/538936/bigg-boss-extra-dose-arshi-s-quirky-demand/541700

[kaltura] Ignore Widevine encrypted video (.wvm)

---

youtube_dl/extractor/niconico.py

---
---
Niconico may return JSON where owner is set to null. In that case, api_data.get will return None even though a default is provided. Fix the check so that we always change None into an empty dict.
To run the tests, comment out the "skip" and put your Niconico account into in `test/parameters.json`.
Fixes #14135

[niconico] Fix downloading videos with null owner

---

youtube_dl/extractor/twitch.py

---
When downloading clips from Twitch, the clip title used to be part of the filename. That broke within the last month or so, and now the filename only has generic information like "channel name playing some game". This PR restores the ability to detect the clip title.

[twitch] Fix clip title detection.

---

youtube_dl/extractor/nbc.py

---
---
Adds `(?:classic-tv/|)` to the valid URL regex as suggested by a user in the IRC channel. An example is http://www.nbc.com/classic-tv/charles-in-charge/video/charles-in-charge-pilot/n3310. A US IP is required.

[nbc] Fix downloading classic-tv videos

---

youtube_dl/extractor/generic.py
youtube_dl/extractor/vshare.py

---
The VShare extractor is broken, I've rewritten it to depack the code in the page and get the video url from there.
I've also added the `_extract_urls` method.
This should close issue #14473.

[vshare] extractor rewritten

---

youtube_dl/extractor/francetv.py

---
---
Simple fix of the regex only looking for http

[FranceTV] Fix video url regex for Culturebox (Closes #14827)

---

youtube_dl/extractor/generic.py
youtube_dl/extractor/jwplatform.py

---
Support iframe embeds for JWPlatform.  Include test.
Code such as:
```
<div class="jwvideo" style="position:relative; padding-bottom:56.25%; overflow:hidden;">
<iframe
src="//content.jwplatform.com/players/O0c5JcKT-zffGtjRq.html"
width="100%" height="100%" frameborder="0" scrolling="auto"
allowfullscreen style="position:absolute;">
</iframe>
</div>
```
Implementation as simple as going from `<script` to `<(script|iframe)`.
Example failure without this change:
```
pb3:youtube-dl jhawk$ youtube-dl -v 'https://www.mediaite.com/tv/dem-senator-claims-gary-cohn-faked-a-bad-connection-during-trump-call-to-get-him-off-the-phone/'
[debug] Command-line args: [u'-v', …
```

[JWPlatform] support iframes

---

youtube_dl/extractor/openload.py

---
---
Allows a broader range of Openload links to be understood by the _VALID_URL regex and fixes the only error raised by flake8, which complained about using bare `except` at line 143.

[openload] Support [www.]openload.link URLs and make flake8 pass

---

youtube_dl/extractor/youku.py

Change-Id: Id397e814e81ff560506d68563b7409eebbe5943d
---
PR https://github.com/rg3/youtube-dl/pull/14887 has solved issue https://github.com/rg3/youtube-dl/issues/14880 , however there is still a bug in which the length of downloaded video is about 10 minutes actually 20+ minutes.

[youku] Update ccode

---

youtube_dl/extractor/playtvak.py

---
Some live streams from Playtvak.cz now use `Misc.video({` instead of `Misc.videoFLV({`. This PR fixes it while also fixing failing tests.

[playtvak] fix video regex

---

youtube_dl/extractor/pluralsight.py

---
---
If the first subtitle phrase starts at offset 0.0, it is skipped (incorrectly) when doing conversion from json to srt format. This is a fix for issue #11118.

[pluralsight] Fixes #11118

---

youtube_dl/extractor/common.py

---
This fixes issue #3681 and other similar for non-YouTube video sites that use MPEG-DASH. Without specifying container type, the automatic fixup of MPEG-DASH container from commit 62cd676c7474f696804eda653558ada94c5953a0 don't take place.

[common] indicate DASH container in _parse_mpd_formats function

---

youtube_dl/extractor/twitch.py

---
Using the `--download-archive` parameter, youtube-dl can skip videos that it has already downloaded, as soon as it determines that the extractor and video ID match an existing video. For Twitch, the video ID for a VOD is determined as part of a JSON request in `_real_extract(...)`. However, the video ID can also be reliably determined from the URL; the ID is part of the URL, with a leading `v`. The Twitch extractor already relies on this behaviour for downloading rechat subtitles.
With this pull request, when extracting a playlist, the URL is checked against `_match_id(...)` for the VOD extractor. If it matches, we now return the video ID alongside the URL, so that the video can be skipped if desired without needing to make a JSON request. This makes it significantly faster to check …

[twitch] Determine ids from URLs when extracting playlist

---

youtube_dl/extractor/soundcloud.py

---
---
Updated the extractor for the Soundcloud.com website to use the avatar picture when the album artwork is not available - issue #12878.  Apparently a number of tracks on this site do not feature any album art.
Cheers,
Parmjit V.

[Soundcloud] Also use avatar picture for thumbnail (fixes issue #12878)

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/motherless.py

---
Add support for group URLs to be downloaded as playlists.

[motherless] Add support for groups

---

test/test_utils.py
youtube_dl/utils.py

---
---
Fix for #14789 
js_to_json() wrongly recognizes the `e`&`E` of scientific notation literals as start of a new JS identifier and encloses it in quotation marks (`4.2e1 -> 4.2"e1"`).
Using a lookbehind assertion to disallow digits directly in front of identifiers fixes this behavior.

[util] improve scientific notation handling in js_to_json()

---

youtube_dl/extractor/franceinter.py

---
---
FranceInter.fr added, possibly by mistake, a space after the `cover-emission-period` class:
```html
<p class="cover-emission-period ">jeudi 14 décembre 2017</p>
^
```
The date extraction regex in `franceinter.py` was not accounting for this, and caused youtube_dl to emit a warning *(WARNING: unable to extract upload date …)*.
The only change in this PR is that extra space (optional, so it keeps working if they remove/fix it again on the website).
Closes #14996.

[franceinter] Fix upload date extraction (again)

---

test/test_download.py

---
---
Fixes #13757 
An alternative approach to PR #13757, instead of extending the LazyExtractor template we just instance the IE before using it, much like the main YoutubeDL module itself. Hopefully lazy extractors can be enabled by default soon.

Fix tests with lazyloading extractors

---

youtube_dl/extractor/dvtv.py

(I can no longer play that "Live" video in browsers either.)
---
---
"Live" video that I used for test of #15442 is no longer available and that breaks the tests. Worked around that by disabling the test since I suspect this is eventually going to be the case for all their "live" vids.

[dvtv] skip download on failing test

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/pornhub.py

---
---
Updated the extractor for Pornhub.com to also provide support for channel videos as playlists - issue #15613.
Cheers and thank you!
Parmjit V.

[PornHub] Added support for channel video collections (fixes issue #15613)

---

youtube_dl/extractor/abcnews.py

---
Fixed both test case ids for AbcNews extractor

[AbcNews] fixed extractor ids

---

youtube_dl/postprocessor/embedthumbnail.py

---
---
This will allow the postprocessor(s) to continue and other downloads (if a playlist is being downloaded) if a thumbnail cannot be found when used with `--embed-thumbnail` flag. `FFmpegEmbedSubtitlePP` does not stop the process when there are no subtitles, so neither should `EmbedThumbnailPP`.
Related to #9289

[postprocessor/embedthumbnail] Continue if there is no thumbnail

---

youtube_dl/extractor/heise.py

---
Fixes #14961.
The fix delegates the webpage to KalturaIE, when no jwplayer container ID was found.
I also added a test.

[heise] delegate to KalturaIE when necessary (#14961)

---

youtube_dl/extractor/prosiebensat1.py

---
Galileo.tv is just a part of ProSiebenSat1, so it was easy to add the support for it requested in #15894.
I also tested downloading with the URL provided in the issue (https://www.galileo.tv/video/diese-emojis-werden-oft-missverstanden/), since I'm in germany and thereby do not experience the geo restriction, but made the test only matching.
Regards

[prosiebensat1] add support for galileo content (#15894)

---

youtube_dl/extractor/vrv.py

---
---
Fixed a bug where the quote function was incorrectly assumed to be in a different module, leading to an AttributeError when calling it was attempted.

[vrv] fix incorrect URL quote function reference (closes #15928)

---

youtube_dl/extractor/openload.py

---
Openload has another site clone oload.site, this PR adds this site to the _VALID_URL regex.

[openload] add oload.site domain

---

youtube_dl/extractor/medialaan.py

---
---
Long video id's like ```vtm_20180328_VM067D2E9_vtmwatch``` do not work.
Example of such links are `https://vtm.be/video/volledige-afleveringen/id/vtm_20180328_VM067D2E9_vtmwatch` and `https://vtm.be/video?f%5B0%5D=sm_field_program_active%3ABoxing%20Stars&aid=194365`
Should fix #14702 and #14871, although the videos used to report are no longer online.

[VTM.be] fix long video_id

---

youtube_dl/extractor/xvideos.py

---
---
Updated the extractor for the XVideos.com website to set the thumbnail image using the embedded html5player data - issue #15978.
Cheers,
Parmjit V.

[XVideos] Correctly set thumbnail image (fixes issue #15978)

---

youtube_dl/extractor/drtuber.py

---
---
Updated the extractor for the DrTuber.com website to properly fetch the video title - issue #16107.
Cheers,
Parmjit V.

[DrTuber] Fix title extraction (fixes issue #16107)

---

youtube_dl/extractor/common.py

---
This modification makes the JSON-LD "@context" field matching more robust by using a Regex. Without this patch, JSON-LD strings are some times not recognized which leads to failure in extractors (e.g. #16006).
Furthermore, this patch will prevent extractors from failing in the future, if the "@context" field gets slightly modified by a website.

Make JSON-LD "@context" parsing more robust (closes #16006)

---

youtube_dl/extractor/openload.py

---
This is a fix for #16137. The previous regexps were doing painful parsing of what is actually an IP network. Thing is, the original author (and Travis CI!) has no IPv6 connectivity, hence forgot to include IPv6 patterns in regexps (hex and `:` eg. `2a01:cb15::`). This breaks URL parsing for people on a IPv6-enabled network.
This PR replaces the two similar regexps with a more generic one, that includes both IPv4 and IPv6.
flake8 reports warnings around my fix, dunno if I am supposed to fix these in the PR, as it is unrelated. Please tell me if that's a requirement.

[openload] Generic IP v4 & v6 stream URL parsing (fixes #16137)

---

youtube_dl/extractor/generic.py

---
---
When downloading from rss feeds, the generic extractor follows the rss links first. This leads to "ERROR: Unsupported URL" messages in a lot of cases. Even though there are enclosures present.
```
$ youtube-dl --playlist-end 1 http://www.hellointernet.fm/podcast?format=rss
[generic] podcast?format=rss: Requesting header
WARNING: Falling back on generic information extractor.
[generic] podcast?format=rss: Downloading webpage
[generic] podcast?format=rss: Extracting information
[download] Downloading playlist: Hello Internet
[generic] …
```

[generic] prefer enclosures over following links in rss feeds

---

youtube_dl/extractor/youtube.py

Rather than just the one that use the _download_webpage helper. The need
for this was made apparent by 0fe7783e, which refactored
_download_json in a way that completely avoids the use of
_download_webpage, thus breaking youtube.
Fixes #16323
---
---

[youtube] Correctly disable polymer on all requests

---

youtube_dl/extractor/indavideo.py

---
It seems that Indavideo has added an extra token to their JSON metadata, and if the token is not used as a URL parameter when requesting the actual video file, the request is denied with a 403 Forbidden response. This pull request extracts the token and appends it to the video URL transparently, using the standard Python 2/3 URL parsing tools to be as future-proof as possible.

Indavideo token

---

youtube_dl/extractor/audiomack.py

Found that _real_extract(...) was not converting id from int to str.
Fixed by wrapping fragment in compat_str()
---
---
I wanted an easy ticket to get my feet wet with, and this one fit the bill.  The issue shows a warning when downloading a track.  Looking at the AudiomackIE._real_extract(), the return …

fix for issue-15310

---

youtube_dl/extractor/dvtv.py

---
---
skip_download does not cut it anymore, m3u8 now returns HTTP 500 with "no_dvr_segments"

[dvtv] remove test of outdated live stream

---

youtube_dl/extractor/cbc.py

---
---
Updated the extractor for the cbc.ca website to properly fetch the video title - issue #16502.
From the page source, the order of extraction should be: 1) OpenGraph title if available, 2) Twitter title if available, 3) Document title otherwise.
Cheers,
Parmjit V.

[CBC] Fix title extraction (fixes issue #16502)

---

.gitignore
setup.cfg

---
This adds support for Virtualenv environments, one of the the default interpreters in use by PyCharm. This changes .gitignore and the flake8 config file to ignore the venv/ directory.

Added support for default Virtualenv environments

---

youtube_dl/extractor/imgur.py

---
This fixes support for Imgur URLs that have digits in filename extension, such as <https://i.imgur.com/crGpqCV.mp4>.

[imgur] Allow digits in filename extension

---

youtube_dl/extractor/dailymotion.py

---
---
Fixes #16984
To prevent display `WARNING: unable to extract OpenGraph description;` use `default` parameter instead `or` statement

Fixes #16984 - Don't display og:metadata Warning

---

README.md

The mentioned Firefox plugin has not been updated in a while - added a new plugin which has a valid export function that can be used for `youtube-dl`

Update to Firefox plugin

---

youtube_dl/utils.py

---
---
The `__init__` method of the `PerRequestProxyHandler` class attempts to return the value within the `__init__` method.
This violates the rule of only using `__init__` to initialize instance members.
So, I removed the return statement in the `__init__` method that is returning a value.

Remove the return statement from the __init__ method

---

youtube_dl/extractor/crunchyroll.py

---
Make `CrunchyrollShowPlaylistIE._VALID_URL` invalid for `media-\d+` urls  (eg.: http://www.crunchyroll.com/media-723735)

(Crunchyroll) Don't match `media-<id>` as playlist

---

youtube_dl/extractor/internazionale.py

---
---
Some videos can have a `data-video-available_abroad` attribute that
can be `"0"` or `"1"` depending if the video is available abroad (if
not present it is available abroad).
For not available abroad videos (all the ones with
`data-video-available_abroad="1"`) `video-ita.internazionale.it` is
used instead of `video.internazionale.it`.
Adjust Internazionale extractor to reflect that and add a test for
a not available abroad video.

[internazionale] Fix extraction of non-available-abroad videos

---

youtube_dl/extractor/bandcamp.py

---
---
Updated the extractor for Bandcamp.com to also include the track number as part of the metadata - issue #17266.
Cheers and thank you!
Parmjit V.

[Bandcamp] Added track number for metadata (fixes issue #17266)

---

youtube_dl/extractor/niconico.py

---
---
As mentioned in issue #17393, certain downloads from niconico would fail with the error "TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str."
This would happen when trying to download the info for various video/audio qualities. Need to encode the data json info in the request to utf-8 bytes.

[niconico] Encode json data in request for formats (closes #17393)

---

youtube_dl/extractor/nbc.py

---
The permalink of the video should be un-escaped before sending via JSON request.
Previous pull was #17442, I've closed it by mistake.

[nbc] unescape url before sending (close #17374)

---

youtube_dl/extractor/rai.py

---
---
In rai extractor there is a (probably leftover) print() that print unexpected
output for URL that uses RaiPlayPlaylistIE extractor or lead to possible
failures (e.g. UnicodeEncodeError exception when the C locale is used).
It was accidentally added after review of #14563.

[rai] Remove a debug leftover print()

---

youtube_dl/extractor/zattoo.py

---
---
Zattoo changed its way to extract the meta information of a video (like title, description, etc.) and therefore stopped working (see #17175). This PR fixes the issue.

[zattoo] Fix video information extraction (closes #17175)

---

test/helper.py
test/test_InfoExtractor.py
test/test_downloader_http.py
test/test_http.py
youtube_dl/extractor/common.py

---
This is a bugfix for #17195, which due to miscommunication, was prematurely closed by @dstftw.
Resolves #17195, closes #17846, resolves #17447.

[extractor/common] Ensure response handle is not prematurely closed before it can be read if it matches expected_status (resolves #17195)

---

youtube_dl/extractor/atvat.py

---
ATV.at did change the HTML structure. They moved the json data into a
variable. Now the extractor looks for the variable instead
Fixes: https://github.com/rg3/youtube-dl/issues/18041

[atv.at] fix initial video extraction

---

youtube_dl/extractor/nzz.py

---
The NZZ information extractor is broken since the redesign of the website. Some NZZ articles still have embedded Kaltura videos, but they are embedded in such a way that the current generic information extractor does not recognize them. This PR adds a regular expression to the Kaltura IE, so that these kinds of Kaltura embeds are recognizes and extracted.
This PR also closes #4407.

[nzz] Extract Kaltura embeds from nzz.ch

---

youtube_dl/utils.py

---
I've stumbled upon the function `random_birthday` in `utils.py` and observed, that this function can return invalid dates, i.e. the struct
```
{
year_field: '1982',
month_field: '4',
day_field: '31',
}
```
representing the date `1982-04-31`, which never existed.
This PR makes sure that only valid dates in the given date range are generated.

[utils] Generate existing dates only

---

youtube_dl/extractor/xvideos.py

---
---
Make the initial request to XVideos using https instead of http.  Closes #18422.

[xvideos] fix webpage downloading (site moved to https)

---

youtube_dl/extractor/ard.py

---
[ARD:mediathek] recently fails for certain videos, because youtube-dl cannot extract the title. This PR adds a new regex for the title extraction and a new regex for the description extraction, which is used e.g. in this (https://www.ardmediathek.de/tv/Dokumentarfilm/Das-Salz-der-Erde-Sebasti%C3%A3o-Salgado-im/SWR-Fernsehen/Video?bcastId=1105036&documentId=57927466) video.
It should close #18349, but I cannot explain that strange behavior which I described there: https://github.com/rg3/youtube-dl/issues/18349#issuecomment-443526330

[ARD:mediathek] Fix title and description extraction

---

youtube_dl/extractor/mediasite.py

---
---
Make the Mediasite download regex slightly more flexible.

More flexible mediasite regex to download public videos

---

youtube_dl/extractor/cammodels.py
youtube_dl/extractor/camtube.py
youtube_dl/extractor/camwithher.py
youtube_dl/extractor/yourporn.py

---
---
I used the script written by @remitamine at https://github.com/rg3/youtube-dl/issues/6497#issuecomment-128993910 to remove all extractors with age limit over 17. I then checked to see if it missed anything with `grep -Rvil age_limit youtube_dl/extractor | grep porn` and `yourporn.py` showed up. I tried every sexy keyword i could think of and also found
camtube.py
cammodels.py
camwithher.py

add missing age limit to a couple of sites

---

youtube_dl/extractor/audiomack.py
youtube_dl/extractor/cnn.py
youtube_dl/extractor/freespeech.py
youtube_dl/extractor/generic.py
youtube_dl/extractor/livestream.py
youtube_dl/extractor/savefrom.py
youtube_dl/extractor/ted.py
youtube_dl/extractor/testurl.py
youtube_dl/extractor/wimp.py

This is code cleanup PR.
Use `url_result` method where possible, rather creating appropriate structure manually.
cc @dstftw

CS: DRY: use url_result

---

youtube_dl/extractor/discovery.py

---
---
This adds support for `--geo-verification-proxy` for the Discovery extractor, since it is unnecessary to proxy the actual download.

[discovery] Add support for --geo-verification-proxy

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/instagram.py

---
This adds an extractor for Instagram videos. It downloads all videos that match a given hashtag as a playlist. It is heavily based on the Instagram user extractor.
I did consider refactoring common methods instead of copy-pasting, but decided it was more important to avoid touching the other code. This way is more difficult to maintain, but I hope is easier to review and avoids the risk of regressions in the other extractors.
If you would prefer a refactor -- either now or in a separate PR -- I would be happy to do it.

[Instagram] Add new [:tag] extractor, refactor [:user]

---

youtube_dl/extractor/radiocanada.py

---
---
Relax the DRM validation as it gives false positive DRM validations. It was the same issue that happened on the toutv extractor. (toutv is a brand of radiocanada) [toutv original commit] (https://github.com/rg3/youtube-dl/commit/8d7a24aff60a57e651bab40f16a81eb7dffb405c#diff-b0b3d3dea05a5c80aca484e9eca2af64)

[radiocanada] Relax DRM check

---

youtube_dl/postprocessor/ffmpeg.py

This is a continuation of #15846 since I no longer can write to that fork/branch.
---
Some files coming from YouTube and probably others come with chapter data (or subtitle?) in a stream seen by ffmpeg as the `bin_data` codec, usually at `0:2`. Without some help, ffmpeg will simply refuse to make an mp4 file containing this. This causes the subtitle post-processor to fail, which also stops any further processing (embed thumbnail, etc).
```
Stream #0:2(eng): Data: bin_data (text / 0x74786574), 0 kb/s
Metadata:
handler_name    : SubtitleHandler
```
This PR adjusts the subtitle post-processor to 'disable' (but not really) all data streams in the ffmpeg command. The resulting files still end up having the bin_data stream, but the SRT subtitle is now properly embedded before it:
```
Stream …
```

[postprocessor/ffmpeg] Do not copy Apple TV chapter tracks

---

youtube_dl/postprocessor/ffmpeg.py

---
---
Normally when ffmpeg outputs 'Last message repeated ...' messages, the exit status becomes non-zero. This will make the preprocessor exit unexpectedly in some cases. Example in the old PR: https://github.com/rg3/youtube-dl/pull/15846#issuecomment-372743101

[postprocessor/ffmpeg] Disable "Last message repeated" messages

---

test/test_YoutubeDLCookieJar.py
test/testdata/cookies/httponly_cookies.txt
youtube_dl/utils.py

---
the code is a modification of [the original code for `load` method](https://github.com/python/cpython/blob/master/Lib/http/cookiejar.py#L1774-L1781), there were multiple similar changes that has been based on the original code of python in `compat.py`.
the code simply removes the `#HttpOnly_` prefix from begining of every line by using an in memory file(`StringIO`), it's the simplest solution that i can think of without using any temporary files or changing the `_really_load` method.

[utils] strip #HttpOnly_ prefix from cookies files

---

youtube_dl/extractor/ciscolive.py

---
---
Cisco Live website changed URL format. Updated _VALID_URL regex to match.

[Ciscolive] - Update _VALID_URL patterns (Fixes issue #20320)

---

youtube_dl/extractor/orf.py

---
Small improvement for the ORF radio extractor. The API provides the series, so we should extract and use it.

[ORF]: Extract series for a stream as well.

---

README.md

---
Lists have to be separated from the previous paragraph by a blank line
in certain variants of Markdown, otherwise they are not interpreted as
lists.
This change ensures that that the youtube-dl.1 man page, which is
generated from README.md with the help of pandoc, is formatted
correctly.
Fixes #20558

Fix formatting issue of lists in README.md

---

youtube_dl/extractor/openload.py

While the .co could be captured directly, I anticipate that there will be more TLD's for openloed in the future.
---
---
Adds support for openloed.co, one of the many domains of openload.co

[openload] add support for openloed.co (fixes #20691)

---

youtube_dl/extractor/twitcasting.py

---
---
Add support for private videos on TwitCasting.
Usage example: `youtube-dl --video-password abc https://en.twitcasting.tv/mttbernardini/movie/3689740`

[twitcasting] Add support for private videos

---

youtube_dl/extractor/francetv.py

---
---
Some francetvinfo URLs, including [those used in tests](http://www.francetvinfo.fr/replay-jt/france-3/soir-3/jt-grand-soir-3-lundi-26-aout-2013_393427.html), would result in a `RegexNotFoundError`.
```ERROR: Unable to extract video id```
The site seems to have changed their player format, and the video id is now contained in javascript.
```player.load({src:'84981923'});```
I added a regex statement to extract the video id: `r'player\.load[^;]+src:[^"\']*["\']([^"\']+)'`
I tried to keep it as open as possible (anything between quotes …

[FranceTVInfo] Fix video id regex extraction (Fix #20619)

---

test/test_utils.py
youtube_dl/utils.py

---
Despite visual similarity *þ* is unrelated to *p*.
It is normally transliterated as *th*:
```console
$ echo þ-Þ | iconv -t ASCII//TRANSLIT
th-TH
```

[utils] Transliterate "þ" as "th"

---

youtube_dl/extractor/streamcloud.py

---
---
Streamcloud has reduced the waiting time from 10 seconds to 5. So youtube-dl does not need to wait 12 seconds to download the video. 6 seconds waiting time is enough.

Streamcloud has reduced the waiting time from 10 seconds to 5

---

youtube_dl/extractor/bitchute.py

---
---
The new design of bitchute uses a channel-banner div to display uploader information, breaking the old regex and causing the following warning: 
WARNING: unable to extract uploader; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
this fixes it.

bitchute - updated uploader regex

---

youtube_dl/extractor/pornhub.py

---
---
ATM, youtube-dl downloads over HTTP, even though HTTPS is specified in the URL (because user wants to download over HTTPS as ISP has blocked HTTP access to the site :disappointed:). So just download over HTTPS.
I have checked https://github.com/ytdl-org/youtube-dl/pull/20314 and tested downloading the mentioned playlist URL in the source code, and seems to work.

[pornhub] Download over HTTPS

---

youtube_dl/extractor/vlive.py

---
---
The failing test for the VLivePlaylist extractor highlighted the fact that when the playlist URL leads to a page without a playlist it does not fall back to downloading the video on that page and instead errors out. This PR addresses that issue.

[vlive:playlist] Redirect to video extractor when no playlist is found

---

index.html

(this isn't a code change) This changes the Support link from https://github.com/ytdl-org/youtube-dl/issues/new to https://github.com/ytdl-org/youtube-dl/issues/new/choose, prompting users to pick a template instead of giving them an empty textbox.

Update link to GitHub issues page

---

youtube_dl/extractor/brightcove.py

---
I added support for [playlist streams](https://support.brightcove.com/implementing-playlists) to BrightcoveNewIE, including an additional test. Only differences between 'playlist' and 'video' streams are the 'xxxId' part of the URL and the format of the JSON response, both of which are covered in this PR.

[BrightcoveNew] Add playlist support

---

youtube_dl/extractor/beampro.py

---
---
Changed the _VALID_URL regex pattern to match new VOD URLs as seen in #21531
e.g. https://mixer.com/Midgalicis?vod=IxFno1rqC0S_XJ1a2yGgNw

[mixer:vod] relax _VALID_URL (fixes #21531)

---

youtube_dl/extractor/vevo.py

---
---
Added support for embed.vevo.com URLs, which are occasionally found embedded as iframes in articles.

[vevo] Add support for embed.vevo.com URLs

---

youtube_dl/extractor/twitch.py

---
Twitch VOD downloads started failing for me recently (the last week or so). My symptoms were as described in #21538. At least 2 other people are having the same problem. Poking around, I discovered that twitch has apparently switched their m3u8 endpoint to include a file extension. This small change allowed me to once again download Twitch VODs.

Fix twitch downloading by tweaking VOD url

---

youtube_dl/extractor/yandexmusic.py

---
---
An album in yandex music can have several volumes. Tracks from all volumes should be extracted.

[yandexmusic] extract tracks from all volumes of an album (closes #21420)

---

youtube_dl/extractor/porn91.py

---
---
The porn91 extractor was broken. This pull request fixes that. Tested with porn91's testcase.

[porn91] fix extractor

---

youtube_dl/extractor/gfycat.py

---
Gfycat urls with ru/ in the path are now properly parsed. This pull request closes issue #21779

[gfycat] Add ru/ to regex

---

youtube_dl/extractor/einthusan.py

---
---
einthusan.tv is having some issues with their normal domain, and have added einthusan.com as an additional domain. My addition extracts the tld and downloads from that tld, specifically.

[einthusan] adding .com tld

---

youtube_dl/extractor/ctsnews.py

---
Fixed the YouTube embedded video URL regex pattern, somehow it was missing the "https" part in the beginning. I have tested this extractor's 3 unit test cases and updated the other 2 description.

[CtsNews] Fix YouTube embed video url regex and test cases

---

youtube_dl/extractor/common.py

---
---
I just spotted this tiny typo while I was reading the description of dictionary fields in Information Extractor.

[common] fix typo in thumbnails resolution description

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/yahoo.py

---
I added an extractor that supports Yahoo Japan News pages which aren't extractable via generic or Yahoo extractors. This extractor specifically supports pages on news.yahoo.co.jp and headlines.yahoo.co.jp. 
Current output:
```
$ youtube-dl -v https://headlines.yahoo.co.jp/videonews/nnn?a=20190531-00000180-nnn-int
[debug] Command-line args: ['-v', 'https://headlines.yahoo.co.jp/videonews/nnn?a=20190531-00000180-nnn-int']
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.3 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, phantomjs 4, rtmpdump 2.4
[generic] …
```

[YahooJapanNews] Add extractor.

---

youtube_dl/extractor/dlive.py

---
---
Some dlive VIDs such as the one found in https://dlive.tv/p/pdpreplay+D-RD-xSZg contain hyphens, so modified _VALID_URL accordingly.

[dlive] extend VALID_URL regex to support VID with hyphens

---

CONTRIBUTING.md

---
I added some coding conventions based on maintainers' reoccurring comments on pull requests. Issues included: inline values, collapsing fallbacks, and trailing parentheses. My hope is that these additions will save contributor's and maintainer's time.

Add coding conventions

---

youtube_dl/downloader/fragment.py

---
---
When resuming a partially downloaded file with fragment (or derived) downloader, the displayed ETA is wildly inaccurate. This is because the call to `calc_eta` doesn't subtract the starting partial file size from `total` and `current` byte counters.
For example: I have 1000MB out of a 2000MB video downloaded (youtube-dl killed for some reason, e.g. I needed to reboot or download something more important quickly). Later I run youtube-dl again to finish the download and the speed is ~1MB/s. After 5 seconds elapsed, ETA shows 5 seconds …

[downloader/fragment] Fix ETA calculation of resumed download

---

youtube_dl/extractor/piksel.py

---
---
Added subtitle feature for `piksel`, e.g. now supporting `youtube-dl --write-sub --sub-lang en --skip-download 'https://player.piksel.com/v/ums2867l'`

[piksel] add subtitle capability (e.g. https://player.piksel.com/v/ums2867l)

---

youtube_dl/extractor/jwplatform.py

---
---
URL 'https://content.jwplatform.com/videos/WbFsN7Kl-WdGqK18o.mp3?exp=1566156755\&sig=e60548f2434c12279baff74cf8327b9bd9ffc7383'
was broken by https://github.com/ytdl-org/youtube-dl/commit/7c072f00d66f3b3f44d301059443480a5c83d3c0 and approach for the fix was introduced here 
https://github.com/ytdl-org/youtube-dl/commit/9c017253e83ac3dfd363566ccbb9fc63f4e2ac07
[JWPlatform] WbFsN7Kl: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on …

[jwplatfom] do not match video URLs(#20596)

---

youtube_dl/extractor/xvideos.py

---
---
ytdl doesn't recognize xvideos urls like the one below : 
https://fr.xvideos.com/video13287221/
Did you notice the 'fr' subdomain before 'xvideos.com' domain ?
This patch addresses this issue and other alternative valid xvideos urls rejected by youtube-dl.
xvideos2.com, xvideos.es, it.xvideos.com, de.xvideos.com.

[xvideos] Add support for alternative urls.

---

youtube_dl/extractor/peertube.py

---
Update the list of PeerTube instances from https://instances.joinpeertube.org/instances. The list was quite stale and a lot more PeerTube instances are now available.
The test domain was updated from `peertube.moe` to `peertube.cpy.re` as `peertube.cpy.re` is the instance run by the group who make PeerTube. `peertube.moe` has since disappeared and thus the new list did not include them, causing the tests to fail.

Update list of peertube instances and test domain

---

youtube_dl/extractor/gfycat.py

---
---
When pasting gfycat URLs copied from the browser, or pasting URLs shared via chat/social media, links are often provided as direct media urls, e.g.
```
https://thumbs.gfycat.com/acceptablehappygoluckyharborporpoise-size_restricted.gif
https://giant.gfycat.com/acceptablehappygoluckyharborporpoise.mp4
```
youtube-dl had downloaded these URLs using the `generic` extractor, though using the `gfycat` extractor would yield the best results (and not simply download the reduced gif preview).
I have verified that my changes work by adding tests and …

[gfycat] support when accidentally prodiving media uri

---

youtube_dl/extractor/twitch.py

---
---
Addresses https://github.com/ytdl-org/youtube-dl/issues/22395 where URL matching wasn't finding Twitch VODs that have IDs without a leading `v`.

[twitch] update VOD URL matching

---

youtube_dl/extractor/bitchute.py

---
---
Adding ability to grab "upload_date" from bitchute. Will probably fix #22990 as well.

[bitchute] add upload_date

---

devscripts/create-github-release.py

---
Without this change `make offlinetest` fails with:
./devscripts/create-github-release.py:4:1: F401 'base64' imported but unused

[devscripts/create-github-release] do not import base64

---

youtube_dl/extractor/safari.py

Please follow the guide below
---
---
Safari website only downloads first 60 seconds of video, and is caused by problem parsing Kaltura session JSON. This JSON was returned in HTML format of Django REST
solved by: add request header to accept only json format

Fix Extractor safari

---

youtube_dl/extractor/orf.py

---
removed if clause for special fm4 show_id handling, as url has been changed to a new format where the station is natively correct.
updated only test url of ORFRadio Extractors. While other extractors are not updated because they worked with a simple test in the console with random current links and the links would get invalid again quickly anyway in a short time.

fixed error when parsing fm4 url

---

youtube_dl/extractor/toggle.py

---
---
Toggle.sg got renamed to meWATCH, I updated the URLs and it works again. I honestly have no idea how that flake8 thing works, though.
The patch itself is just an update to a hostnames:
video.toggle.sg is www.mewatch.sg now.

Toggle was renamed to meWATCH (issue #23895)

---

youtube_dl/extractor/imdb.py

Fix IMDB fallback to generic https://github.com/ytdl-org/youtube-dl/issues/23443
---
---
This pull request fixes an issue with the IMDB extractor not recognizing all valid IMDB URLs, causing it to fall back to the generic extractor. In particular, it didn't parse URLs that had some video/viIDGOESHERE in them.

Fix regex not accepting some IMDB links, falling back to generic without

---

README.md
youtube_dl/options.py

---
---
This resolves conflict of shorthand of `--version` and `--verbose`.    
Because `-v` is widely used for `--verbose`, this PR changes only `--version` and keep others unchanged.

[options] assign -V to --version to resolve conflict with --verbose

---

youtube_dl/extractor/vimeo.py

---
---
I noticed a few Vimeo (VHX) Videos that have absolute URLs to their subtitles. This patch only adds "https://vimeo.com" when required. not always (as before)

[vimeo] fix subtitles url

---

youtube_dl/extractor/pornhub.py

---
---
Ref #18797
Update the pornhub extractor to support pornhubpremium URLs. Throw an extractor error if --cookies is not provided.

Added basic support for pornhubpremium.com when using --cookies.

---

youtube_dl/extractor/twitch.py

---
---
It fixes #24290 by adding support for the mobile links to the regular expression for valid urls to the `twitch:clip` extractor. Also the regex is reformatted to a verbose regex to improve readability.

TwitchClip Extractor: Support mobile links

---

youtube_dl/options.py

---
Clarify docs re: --exec command. As bug says, docs say --exec runs after file download, when actually it runs after download and post-processing (e.g. merging formats).

[README.md] Clarify docs re: --exec command (closes #19087)

---

youtube_dl/extractor/prosiebensat1.py

---
This pull request fixes multiple issues in the prosiebensat1 extractor. I did not create multiple PR for this as every one of those bugs (not really bugs, just things that broke because Pro7 changed things) break the integration-tests.
Hint for reviewing: it is best to review from commit to commit as every commit fixes one bug and the commit-message describes it. The exception is commit https://github.com/ytdl-org/youtube-dl/commit/80ee06ad3abc4c98656cac819567e28eeb027888, which makes the code more resilient (switches to `_html_search_meta`) and https://github.com/ytdl-org/youtube-dl/pull/24948/commits/548b87050bf62dec7dac180d0ed63fd8d9b0b19c which fixes linting.

Fix mutiple issues in prosiebensat1

---

youtube_dl/extractor/redtube.py

---
A site changed the html they use for the "title", so I updated the regex in the extractor to match.

Update redtube extractor (make title regex match current site)

---

youtube_dl/extractor/ard.py

---
---
The ARD extractor expects `/videos/` in the URL path, in the URL of video linked in #25134 that path component is called `/videosextern/`.

[ard] relax _VALID_URL regex (closes #25134)

---

youtube_dl/extractor/giantbomb.py

---
---
A majority of Giantbomb's videos are collected in the form of a "show" so the urls are giantbomb.com/shows/xxxxx rather than the giantbomb.com/videos/xxxxx
The current extractor only supports /videos/ links so I edited the regex to include /shows/ links.
I also edited the existing test that was in the extractor as it was failing due to a bad md5 value, it's possible that some backend changes over at giantbomb caused this to change.

Editing Giantbomb extraction to include /shows/ links

---

youtube_dl/extractor/youtube.py

---
When a YouTube playlist or channel listing has more than one page of videos, the continuation URLs specify `youtube.com` instead of `www.youtube.com`. This causes an **HTTP/1.1 301 Moved Permanently** response, so there is an unnecessary HTTP round-trip for each continuation page that the extractor accesses. This PR adds the `www.` prefix to the following line of code:
https://github.com/ytdl-org/youtube-dl/blob/9a7e5cb88aa3a80f7b4d37424ca7cb3bd144cdc8/youtube_dl/extractor/youtube.py#L306
**Example**
<pre>
youtube-dl  -s --print-traffic  https://www.youtube.com/channel/UCBR8-60-B28hp2BmDPdntcQ
</pre>
**Before**
Notice that the traffic includes three **HTTP/1.1 301** replies so there are a total of 7 `GET` requests.
<pre>
GET /playlist?list=UUBR8-60-B28hp2BmDPdntcQ&disable_polymer=true …

[youtube] Prevent excess HTTP 301 on playlist continuations

---

youtube_dl/extractor/youtube.py

---
Currently youtube extractor uses description in a `<meta>` tag and only if lookup fails tries to get the description from `video_details`.
Description in `<meta>` tag now contains truncated text (see #25937), `video_details.get('shortDescription')` gives full description provided by uploader. So swap the order of operations.

[youtube] Fix description extraction

---

youtube_dl/extractor/xhamster.py

---
New URL scheme with letters instead of numbers for the video_id.
closes #25789

[Xhamster] Updated regex to accommodate new video_id with letters

---

youtube_dl/extractor/xhamster.py

---
---
Closes https://github.com/ytdl-org/youtube-dl/issues/26157, closes https://github.com/ytdl-org/youtube-dl/issues/26214, closes https://github.com/ytdl-org/youtube-dl/issues/26282
Remove newline from xhamster.py initials regex. The problem seems to be that on the page the initials no longer end with a new line. Fix issue discribed https://github.com/ytdl-org/youtube-dl/issues/26157 and https://github.com/ytdl-org/youtube-dl/issues/26214

xhamster.py - remove newline from initials regex

---

youtube_dl/extractor/youtube.py

---
---
YouTube apparently renders errors using javascript now. I used the meta tag for age restriction as a workaround.
Closes #25954

[youtube] Fix age gate detection

---

youtube_dl/extractor/soundcloud.py

---
---
Per the documentation here https://developers.soundcloud.com/blog/offset-pagination-deprecated the maximum limit value is actually 200, however 2000 seems to work fine. The exact upper limit I found experimentally was 2847 (anything above the returns a 502 Bad Gateway error). I figured 2000 would provide some leeway in case the actual limit comes down again.
This limit was previously modified by b334732709a283a3a284e8835f4473c2a2be2827 after many users reported the 502 errors back in May. It seems to have cropped up again, and reducing the …

[soundcloud] Reduce pagination limit to fix 502 Bad Gateway errors when listing a user's tracks.

---

youtube_dl/extractor/youtube.py

---
---
In its current state, the YouTube description extraction logic only checks if `shortDescription` from `video_details` is truthy, which it is not if it's an empty string when there is no description. As a result of that, it uses the `description` meta tag, which has a default value of `Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.`. This PR changes this behaviour to only use the meta tag if `shortDescription` is None (= doesn't exist) and adds a test for it.

[youtube] Fix empty description extraction

---

youtube_dl/extractor/rtlnl.py

---
The rtl.nl extractor does not work with the updated url-scheme anymore. This pull requests fixes the url-pattern. Without touching the old regex. A new testcase is added, old ones are still the same.
See also #25821 
(tried a pull-request before, but #25816 got lost due to a rebase while updating to the most recent code-base).

[rtlnl] update regex for new urlscheme

---

youtube_dl/downloader/http.py

---
When the http downloader's `urlopen` times out, it used to stop the program with the timeout error, disrespecting the user's retry count settings. This fix addresses that, by having a timeout trigger a retry.
I've tested it on Python 2.7.18 and 3.8.2.
While I think the fix is a useful thing to have in general, it addresses a specific issue I have, and described in #25183. That bug, however, was closed as a duplicate without any explanation or reference to a duplicate bug, so I never found out if there was any existing discussion about it.
Many times when the `dash` downloader is used to download youtube videos, my download would time out every 1-3 fragments. This means I would have to re-run the command over and over again.
With the timeout retry fix, the dash fragments that get a …

[downloader/http] Retry download when urlopen times out

---

youtube_dl/downloader/hls.py

---
---
The end of the byte range is the first byte that is NOT part of the to
be downloaded range. So don't include it into the requested HTTP
download range, as this additional byte leads to a broken TS packet and
subsequently to e.g. visible video corruption.
Fixes #14748.

[downloader/hls] fix EXT-X-BYTERANGE off-by-one bug

---

youtube_dl/extractor/pornhub.py

---
Since the UI change of pornhub the 'v' in View count is spelled with a capital 'V'. I rewrote the regex to include both a common 'v' and capital 'v' to fix the view count extraction

[pornhub] Fixed view count extraction

---

youtube_dl/extractor/redtube.py

---
improve the valid_url regex to support international pages in the format: 
https://it.redtube.com/VIDEO_ID

[Redtube] Add support for international videos

---

youtube_dl/extractor/ustream.py

---
---
Looks like this extractor works also with video.ibm.com domain, out of the box, so here I add the domain to the regexes.
Thanks!

[ustream] Add video.ibm.com domain

---

test/test_utils.py
youtube_dl/utils.py

---
The current logic in `js_to_json` tries to rewrite octal/hex numbers to decimal. However, when the logic actually happens the `"` or `'` have already been trimmed off. This causes what were originally strings, that happen to look like octal/hex numbers, to get rewritten to decimal and returned as a number rather than a string.
In practive something like:
```js
{
"0x40": "foo",
"040": "bar",
}
```
would get rewritten as:
```json
{
64: "foo",
32: "bar
}
```
This is problematic since this isn't valid JSON as you cannot have non-string keys.

Don't attempt to coerce to JS string to numbers

---

youtube_dl/extractor/twentythreevideo.py

---
---
I came across bonnier-publications-danmark.23video.com urls and wanted to download them. I presume 23video supports custom subdomains for enterprise users, so I changed the code to accept any subdomain of the known domains.
If this PR is considered useful, I'd be really happy if you could tag it `hacktoberfest-accepted`.

[twentythreevideo] support subdomain urls

---

youtube_dl/extractor/rai.py

---
---
- Introduce _BASE_URL in RaiBaseIE class so it could be reused as base for the
several subextractors.
- Remove first test of RaiPlayIE: it is no longer available
- Make RaiPlayIE extension-agnostic (passing possible `.json' URLs is now
supported too)
- Adjust RaiPlayLiveIE to recent raiplay.it updates.  Passing it as
`url_transparent' is no longer supported (there is no longer an accessible
ContentItem)
- Adjust RaiPlayPlaylistIE to recent raiplay.it updates and instruct it about
ContentSet-s.
- Update a RaiIE test and remove two tests …

[rai] Fix extraction for recent raiplay.it updates

---

youtube_dl/extractor/francetv.py

---
- [ x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [ x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [ x] I am the original author of this code and I am willing to release it under …

[francetv] Update to fix thumbnail URL issue

---

youtube_dl/extractor/youtube.py

---
---
In its current state, the YouTube error reason extraction logic only checks `player_response['playabilityStatus']['reason']`. Recently though, the actual reason started only getting sent as an array in `player_response['playabilityStatus']['errorScreen']['playerErrorMessageRenderer']['subreason']['runs']`. This PR changes the behaviour to check the array first and use the `reason` property as a fallback.

[youtube] Fix error reason extraction

---

youtube_dl/extractor/svt.py

Add timestamp, set to "valid from" which i think could been seen as publish time.
Add thumbnail in more cases, seems to was only done in the embedded data case for some reason.
Switch svtplay test url to an existing video and also one with no expire date.
Also add an additional thumbnail url test regex.
Replace #25184 that is based on my repo that is in takedown mode.
---

[svt] Add timestamp and thumbnail in more cases

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/nytimes.py

---
---
Added NYTimesCookingIE class to download videos from https://cooking.nytimes.com, resolves #27112.
Note: I could not find a fallback that contained the video ID. Thus, no fallback regex is in the code.

[nytimes] Add new cooking.nytimes.com extractor

---

youtube_dl/extractor/pornhub.py

---
Simply relaxed the regex for like and dislike count
closes #27227

[Pornhub] Fixed like and dislike extraction

---

youtube_dl/extractor/drtv.py

---
---
The extractor is currently able to recognize episode URLs such as: `https://www.dr.dk/drtv/episode/her-er-dit-hit_-uden-forsvar-med-marie-key_223696`.  
However, movies are listed as programs with a slightly different url such as `https://www.dr.dk/drtv/program/jagten_220924`.  
This expands the regex to also recognize the latter form.

Recognize drtv program urls

---

youtube_dl/extractor/pornhub.py

---
Most ISPs block the other two TLDs (com and net). The org TLD is the only accessible one.

[pornhub] Add org TLD for Indian users

---

youtube_dl/extractor/generic.py

Add description of RSS feed's items
---
---
Adding the RSS feed items description if it's available in order to get complete information from the feed.

[Generic] RSS adding item description

---

youtube_dl/extractor/tubitv.py

---
Puts the release_year into the extractor data for tubi.

expose release_year for tubi

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/nhk.py

---
---
This change adds an extractor for NHK which handles video program pages. This extractor will allow users to download all available episodes of a video program at once instead of having to download each episode one at a time.

[nhk] Add support for NHK video programs

---

youtube_dl/extractor/reddit.py

---
---
Previously, the Reddit extractor would not provide video duration for post videos served through v.redd.it, though this information is provided by the Reddit post API. This change includes the duration key of the API response in the video's extracted information when present. I also added duration to the existing test's info_dict for coverage.

[reddit] Add duration to extracted information for posts containing a v.redd.it video

---

youtube_dl/extractor/generic.py

The thumbnail url of an item in RSS feed is in "href" attribute (not directly in the itunes:image tag)
---
---
The thumbnail url of an item in RSS feed is in "href" attribute (not directly in the itunes:image tag)

[Generic] Fix RSS item thumbnail URL

---

README.md

---
The [cookies.txt extension](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) doesn't exist anymore on the Chrome Web Store, so I propose to change the link in the _README.md_ to another similar extension called [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/) with the same functions and utility of the old one. I tested the extension personally on my machine and it exports cookies in the Netscape cookie file format which is compatible with youtube-dl, just like the cookies.txt extension did before.
This commit does **NOT change any code**, is just a fix for a link on the _README.md_
This PR close #26885

cookies.txt extension doesn't exist anymore on the Chrome Web Store

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/vvvvid.py

---
Add support for playlist in the VVVVID website.
Solves #18130

[vvvvid] add playlists support

---

youtube_dl/extractor/iheart.py

---
---
(continued from #26394)
Added support for podcasts from https://iheart.com/podcast. Supports individual episodes, as well as entire series of podcasts, using their internal API.
Note that IHeartRadio offers other services besides podcasts, but those seem to be only available in the US and/or Canada. That includes things like music playlists, and actual radio stations. I did not include support for them because these are not available where I live, and frankly, I really don't care about those features.

[iheartradio:podcast] Add new extractor

---

youtube_dl/downloader/hls.py

---
Tests truncate the download to 10241 bytes, which is not divisible by 16 and cannot be decrypted. Tests don't really care about the decrypted content, just that the data they retrieved is the expected data. Therefore, it's fine to just return the encrypted data to tests.
Currently tests that want to do MD5 verification of the download will encounter the error:
```
File "/Users/kevinoconnor/Development/youtube-dl/youtube_dl/downloader/hls.py", line 182, in real_download
decrypt_info['KEY'], AES.MODE_CBC, iv).decrypt(frag_content)
File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```
See: #27621 and #27620

Disable decryption in tests for the native HLS downloader

---

youtube_dl/extractor/rai.py

---
fix for #12652
note: splitted the PR as requested here: https://github.com/ytdl-org/youtube-dl/pull/27657#discussion_r551657747

 [rai] fixes #12652

---

test/test_subtitles.py
youtube_dl/extractor/rai.py

---
improved subtitles extraction, see #27698

[rai] improved subtitles extraction

---

youtube_dl/extractor/mixcloud.py

- This is already covered by the other Mixcloud tests.
---
Mixcloud IDs are generated as `username_slug` when the full ID dict has been downloaded.  When downloading a list (e.g. uploads, favorites, ...), the temporary ID is just the `slug`.  This made e.g. archive file usage require the download of stream metadata before the download can be rejected as already downloaded.
This PR attempts to get the uploader username during the GraphQL query, so the temporary IDs are generated similarly, and archive file checks can occur before the full stream metadata is downloaded.

[Mixcloud] Harmonize ID generation from lists with full ID generation

---

youtube_dl/YoutubeDL.py

---
---
Fix a bug where a video would not be downloaded because creating the destination folder failed due to already existing.  This bug can happen when multiple videos are being downloaded to the same destination folder by concurrent youtube-dl processes (e.g., through GNU parallel).
I did not add tests because the fix is for a heisenbug that, by definition, is not possible to write a deterministic test for.

Ignore failure to create existing directory

---

youtube_dl/extractor/twitch.py

---
---
Twitch recently changed how streams are authenticated. It is now required to send an `Authorization: OAuth` header with the GraphQL request or else the server will always treat the request as anonymous, with the usual consequences of 1. injecting ads 2. no access to subscriber-only content.
The OAuth token is stored in the `auth-token` cookie, so we can simply set the authorization header based on this cookie and everything works again.

[twitch] Set OAuth for GraphQL requests to avoid ads with cookies

---

youtube_dl/extractor/americastestkitchen.py

---
---
Although the API does not appear to have changed between [episode 582](https://www.americastestkitchen.com/api/v6/episodes/582) and [episode 705](https://www.americastestkitchen.com/api/v6/episodes/705), the existing code fails to extract the metadata correctly for episode 705. This PR updates the …

[americastestkitchen] Fix metadata extraction for ATK episodes

---

youtube_dl/extractor/franceculture.py

---
---
- solves #27891
- test timestamp updated since the website changed it by a few hours
Thanks for this wonderful work!

[franceculture] Fix extractor

---

youtube_dl/extractor/adn.py

[ADN] Implement login

---

youtube_dl/extractor/abcnews.py
youtube_dl/extractor/amp.py
youtube_dl/extractor/bleacherreport.py

[AMP] Fix upload_date and timestamp extraction

---

youtube_dl/extractor/vlive.py

---
---
Fixes the decode error error below when trying to access a vlive+ (paid) video without logging in.
```bash
$ youtube-dl --ignore-config -v -F "https://www.vlive.tv/post/1-20877616"
[debug] Command-line args: [u'--ignore-config', u'-v', u'-F', u'https://www.vlive.tv/post/1-20877616']
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 2.7.16 (CPython) - Darwin-18.7.0-x86_64-i386-64bit …
```

[vlive] Fix UnicodeDecodeError when decoding error message

---

youtube_dl/extractor/canvas.py
youtube_dl/extractor/extractors.py

---
---
This PR adds a new extractor for "Dagelijkse kost" to `canvas.py`. The extractor is based on the existing extractor for een and canvas.

Add new extractor for Dagelijkse kost

---

youtube_dl/postprocessor/embedthumbnail.py

---
AtomicParsley (which is required for the `--embed-thumbnail` flag) is installed as `AtomicParsley` on most distributions, but can be found as `atomicparsley` on [Alpine](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/atomicparsley) for example.
This PR allows youtube-dl to check if either `AtomicParsley` or `atomicparsley` named binaries exist on the system.

Fix atomicparsley binary lookup

---

youtube_dl/extractor/youtube.py

---
- [x[ Improvement
---
Add invidious-redirect websites, i.e. websites running [invidious-redirect](https://github.com/iv-org/invidious-redirect), they redirect to all public invidious instances and then are often used to share URLs

[youtube] add invidious-redirect websites

---

youtube_dl/extractor/youporn.py

---
---
Add video duration to output

[youporn] Add duration

---

youtube_dl/extractor/vvvvid.py

---
fixes #27601
the only place where to find the season "title" is to call the same url used in the playlist extractor and scroll the file looking for the season that the current video beloongs end save the season "title" that way.
It's probably not super efficient or elegant
Or I can extract it in the playlist extractor and use url_transparent to pass it, it's a lot easier and cleaner:
```
'_type': 'url_transparent',
'ie_key': VVVVIDIE.ie_key(),
...
'season': str_or_none(season.get('name'))
```
but if you download the single episode you don't have the 'season title' info available.

[vvvvid] fix season title extraction (#27601)

---

youtube_dl/extractor/generic.py
youtube_dl/extractor/mtv.py

---
---
This PR escapes dot in regexes that are not intended to match any characters.

[extractors] escape forgotten dot for hostnames in regular expression

---

youtube_dl/extractor/pluralsight.py

---
---
Improve preventing error 429 by increasing sleep timeout.
The current random function can be detect if its value is 2 second.

[pluralsight] improve preventing error 429

---

youtube_dl/extractor/bbc.py

---
---
Pages with metadata extracted from a JSON object assigned to window.__INITIAL_DATA__ didn't extract timestamp and description. At least for the type where the metadata is in the `media-experience` object, this PR adds those items.
Examples:
* http://www.bbc.co.uk/news/science-environment-33661876 (existing test URL)
* http://www.bbc.com/news/av/10462520 (issue #28746)

[bbc] Extract more metadata for window.__INITIAL_DATA__ pages

---

youtube_dl/extractor/medaltv.py

numeric clip ids are no longer used by medal, and integer user ids are now sent as strings.
---
---
This is a bugfix for MedalTVIE which no longer works.
- Medal no longer uses integers only and migrated to azAZ09

[MedalTV] fix extractor due to site updates

---

youtube_dl/extractor/gdcvault.py
youtube_dl/extractor/kaltura.py

---
---
A few pages on the GDC Vault (https://www.gdcvault.com/play/1025699, https://www.gdcvault.com/play/1025739, possibly more) have a slightly-misformed Kaltura iframe link, where the URL has an unnecessary leading space. The Kaltura extractor isn't durable enough to ignore that so it fails to download the file. Web browsers seem happy to skip it, however.
This allows it to ignore that initial leading space when it exists.
This is a repost of https://github.com/ytdl-org/youtube-dl/pull/21079 which got kinda nuked in the whole DMCA thing.

[Kaltura] Add support for an uncommon typo in a GDC Vault page

---

youtube_dl/YoutubeDL.py

---
`process` must be True for `download` to work, right? maybe we could make that more clear somehow

docs: extract_info(process=False)

---

youtube_dl/extractor/orf.py

---
This is a fix for issue #29012. The streaming server is now only available via HTTPS.

[orf] Stream URL only reachable via HTTPS.

---

youtube_dl/extractor/appleconnect.py

---
---
1. I happened to find that appleconnect extractor fails. I get:
```
$ youtube-dl https://itunes.apple.com/us/post/idsa.4ab17a39-2720-11e5-96c5-a5b38f6c42d3 --ignore-config -v -F
[debug] Command-line args: [u'https://itunes.apple.com/us/post/idsa.4ab17a39-2720-11e5-96c5-a5b38f6c42d3', u'--ignore-config', u'-v', u'-F']
[debug] youtube-dl version 2021.05.16
[debug] Python version 2.7.10 (CPython) - …
```

[appleconnect] fix extractor

---

youtube_dl/postprocessor/ffmpeg.py

---
---
Relates to #22680
Currently, if some error occurs in ffmpeg, only the last line is shown (like `ERROR: Conversion failed!`) and it is a bit troublesome to know what the error reason is. (Users need to pick up ffmpeg command line from debug output and run manually.)
This modification adds ffmpeg output on error to debug output and will make it easier to see the error reason.

[postprocessor/ffmpeg] add ffmpeg output on error

---

youtube_dl/extractor/umg.py

---
---
"api.universal-music.de" no longer resolves, updated to the current URL. Site now also issues a "master" m3u8 which has the audioonly and video quality options instead of different formats. Updated the script to not rely on the "height" as this m3u8 doesn't have it.

Fix umg:de as API site no longer resolves

---

youtube_dl/extractor/peertube.py

---
---
Prevent an useless call to API by checking if the description is shortened and only requesting the full description to the API if necessary.

[peertube] only call description endpoint if necessary

---

youtube_dl/extractor/youtube.py

---
- This is NOT my code. This code is copied from PSlava's merged fix to the same issue (Link to issue: #30363) observed in the yt-dlp repository using the same regexes for signature parsing. Link to analogous yt-dlp bugfix: yt-dlp/yt-dlp#641. (This also doubles as a qualifier that this code is released under Unlicense by the original author)
---
Relevant issue: #30363 
Referring to the discussion in the comments of the aforementioned PR on yt-dlp, along with what is apparent upon scrutinizing Youtube's base.js …

[YoutubeDL] Fix function signature parser (refs ytdl-org/#30363)

---

youtube_dl/extractor/youtube.py

---
---
Simple extension of  `YoutubeIE._VALID_URL` to cover new Shorts format `https://youtube.com/shorts/{id}`.
Resolves #30269
Resolves #30328
Resolves #30525
Resolves #30550

[Youtube] Support Shorts URL format

---

youtube_dl/extractor/youtube.py

---
---
When JSInterp-based n-parameter decoding was implemented to replace the temporary fix from derived from VLC, the descrambling code acquired a `try` block that re-raised any exception during descrambling as an `ExtractorError`. This caused yt-dl to fail if the decoding failed, whereas the program could have continued with a warning and run the download at the throttled rate.
This PR changes the re-raised exception to a warning. The warning may be shown as many times as the n-parameter is found in the item's media URLs, but that should be an incentive to patch the program quickly.

[Youtube] Avoid crashing if n-sig decode fails

---

youtube_dl/extractor/youtube.py

---
---
Code from https://github.com/yt-dlp/yt-dlp/commit/cd684175adbe663bbdf6a6c72d8b99b617b6ff2e
Closes https://github.com/ytdl-org/youtube-dl/issues/29071

[youtube] Support channel search

---

youtube_dl/extractor/tv2dk.py

---
---
#30593 reported a TV2DK page apparently been produced using the Nuxt.js framework from which the required Kaltura ID wasn't being extracted.
This PR adds a second target pattern for the Kaltura ID in line with the pattern used for the Partner ID (PPPPPPP) to extract it (KKKKKKKKKK) from a string like this:
```
"http:\u002F\u002Fcdnapi.kaltura.com\u002Fp\u002FPPPPPPP\u002Fsp\u002F204532100\u002FplayManifest\u002FentryId\u002FKKKKKKKKKK\u002Fformat\u002Furl\u002Fprotocol\u002Fhttp"
```
It also adds logic to return a 1-item playlist as a single video, so getting rid of unwanted playlist-related diagnostics.

[TV2DK] Find TV2DK Kaltura ID in Nuxt.js page format

---

youtube_dl/extractor/zdf.py

---
---
The ZDF extractor looks for a place (`content['mainVideoContent']['http://zdf.de/rels/target']`) to find metadata, using the JSON returned from `api.zdf.de`.
The new format of this JSON is like this:
```
'http://zdf.de/rels/target': {
'title': 'Der mit dem Wolf tanzt',
...
'streams': {
'default': {
'label': 'Normal',
'extId': 'video_artede_097462-000-A',
'http://zdf.de/rels/streams/ptmd-template': '/content/documents/vod-artede-der-mit-dem-wolf-tanzt-100.json?profile=tmd'
}
}
},
```
The PR changes the JSON processing to look in `['streams']['default']` as well as in the root of the JSON to find the items `http://zdf.de/rels/streams/ptmd` and `http://zdf.de/rels/streams/ptmd-template`.
Resolves #29893
Resolves #30509.

[ZDF] Support more deeply nested ptmd_path with test, update tests

---

youtube_dl/extractor/urplay.py

---
---
urplay.se moved its React-ish hydration JSON from an element tagged with `data-react-class` to a typical Next.js structure in a `<script>` with `id` `__NEXT_DATA__`.
This PR makes this the initial page format for extraction, with the previous format as fall-back: fortunately the JSON is much the same
We can also extract an `age_limit` and subtitles that were not previously found by the extractor.
Resolves #30504.

[URPlay] Update extractor for Next.js page format, with subtitles

---

youtube_dl/extractor/wdr.py

---
---
According to issue #30484, support for the WDR children's mini-site 'Die Sendung mit der Maus' was broken.
This PR restores that (and possibly other) functionality and fixes the extractor tests.
A pseudo-URL wdr:id is supported, where id is the 6+ digit suffix in `mdb-nnnnnn`.
The obsolete `WDRMobileIE` is marked as not `_WORKING`.
Resolves #30484.
Also resolves/replaces these open issues/PRs:
* closes #13178
* closes #17989
* closes #16448.

[WDR] Fix WDRMaus and update tests

---

youtube_dl/extractor/applepodcasts.py

---
---
Pages from podcast.apple.com have begun to be served with a different structure, where the podcast metadata is found in JSON in an element with `id` `shoebox-media-api-cache-amp-podcasts` rather than `shoebox-ember-data-store`, and the JSON has a slightly different structure.
This PR adds support for the new format. On the assumption that this format will eventually be used for all podcast pages, the new format is tried first, and then the old format if that doesn't succeed. The block that handles the old format can be removed once it is determined that the old format is no longer served.
* Resolves #30216
* Resolves #30250
* Resolves #30413.
Additionally, the format information returned by the extractor comprised just the media URL, which broke a configuration with, eg, `-f …

[applepodcast] Support new page format

---

test/parameters.json
test/test_download.py
youtube_dl/downloader/__init__.py
youtube_dl/downloader/niconico.py
youtube_dl/extractor/extractors.py
youtube_dl/extractor/niconico.py

---
---
The  Niconico extractor has been broken following site changes, and also served files that couldn't be downloaded in a single yt-dl run because the server cancelled the download in the absence of a regular heartbeat POST.
The corresponding module in yt-dlp has been actively maintained and additional search extractors have been implemented, as well as adding support for the heartbeat function for downloads.
This PR adapts the current version of the yt-dlp module to yt-dl conventions, in particular replacing `f'strings'` and `yield from`. …

[Niconico] Back-port extractor and add new search extractors from yt-dlp

---

youtube_dl/extractor/arte.py
youtube_dl/extractor/extractors.py

---
---
As in issue #30115, ARTE TV has collection playlists, already supported through `ArteTVPlaylistIE`, and also category playlists, not previously supported.
This PR adds the ArteTVCategoryIE to support the latter playlist type. Unlike the collection playlists, the page is not populated from the API, so the extractor scrapes the page. In the initial version it just collects the items on the original page, not any items in continuation links or populated by endless scrolling.
Resolves #30115.

[ARTE] Support category playlists

---

youtube_dl/extractor/uol.py

---
---
- Closes https://github.com/ytdl-org/youtube-dl/issues/30091
In commit https://github.com/ytdl-org/youtube-dl/commit/ce7db64bf1a558759be63e92f34550d7ba0e4052, `format_id = str_or_none(f.get('id'))` line has been replaced with `format_id = format_id`. Because `format_id` is retrieved from `uol_formats.items()`, this line has no meaning.
(I just happened to look this while wandering about https://lgtm.com/projects/g/ytdl-org/youtube-dl/?mode=list)

[uol] Remove redundant assigning `format_id`

---

youtube_dl/extractor/nuvid.py

---
---
Video details aren't in the original HTML any longer. Instead they are populated by async JS.  
The final version is back-ported from yt-dlp (thanks @u-spec-png) onto the version from PR #17890 (thanks @vidaritos) with some elements of the initial version added back.
Fixes #29321
Fixes #29886.
Also closes #17890 (PR) and so also:
* closes  #27578
* closes #15355

[Nuvid] Use site JSON for video details

---

youtube_dl/extractor/rutv.py

---
---
https://smotrim.ru/live/channel/2961
It fails due to returning quality as an empty string

[rutv] fix vbr for empty string value

---

youtube_dl/extractor/myspass.py

- https://github.com/ytdl-org/youtube-dl/issues/30521
---
---
Within the myspass site extractor, there is a short regex for checking for certain substrings in the video url.
```groups()``` was called on ```re.search()``` without first ensuring there were any results to return a regex object. I've added a simple check for this.
Resolves #30521
Closes #30522

Fixed groups() call on potentially empty regex search object

---

test/test_YoutubeDL.py
youtube_dl/YoutubeDL.py
youtube_dl/extractor/vimeo.py

---
When a Vimeo URL ends with '/ID/hash' and both ID and hash are numeric, the `_VALID_URL` pattern match skips over the ID part and assigns the ID from the hash part. One component of the URL pattern needs to be non-greedy: `(?:.*?/)??` instead of `(?:.*?/)?)`.
Closes #29690.

[Vimeo] Avoid skipping ID when unlisted_hash is numeric

---

youtube_dl/extractor/bilibili.py

---
---
need "referer" header when download path such as "/audio/au1003142".
related [issue](https://github.com/ytdl-org/youtube-dl/issues/30768).

[extractor/bilibili] Fix path "/audio/auxxxxx" download return 403

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/kaltura.py
youtube_dl/extractor/kth.py

---
This pull request adds an extractor for the KTH Play website. KTH Play is a website which KTH uses to publish lectures and other videos online. KTH is a university in Stockholm, Sweden.

[KTH] Add new extractor for KTH play

---

youtube_dl/extractor/nhk.py

---
The `NhkVodIE` extractor expects programme IDs to be either 7 decimal digits or longer than 8 characters. The example in issue #29670 has an `a` in the last 3 characters of a 7 character ID. This PR enables the extractor to recognise and process IDs with 7 alphanumeric characters.
A test has been included but should be changed to `'only_matching': True` when merging, as the test URL is probably transient.
Closes #29670

[NHK] Support alphabetic characters in 7-char NhkVod IDs

---

youtube_dl/options.py

https://github.com/ytdl-org/youtube-dl/pull/30809
---
I was confused whether the regex needed to be special when using the `OR` regex operator to list multiple substrings `Like|This`. I had to dig into the code to know what was going on. By moving the adjective in the README to the front it should be clear that both regex and substrings are treated with re.IGNORECASE

readme: make it more clear that regex ignores case

---

youtube_dl/extractor/vvvvid.py

---
---
The video_format of url in  #31030 is video/dash, as it's not present in the if ... if else ... if else ..., it goes to the last else that tries and fails to load the url. This fix should correctly handle video/dash as a m3u8 file.

[VVVVID] Support video/dash types, fixes #31030

---

youtube_dl/extractor/aenetworks.py

---
Per #29300, the HMAC url signatures need a new key and secret, which was recently changed. This updates the values in the extractor and allows downloading videos again.

[aenetworks] Update _THEPLATFORM_KEY and _THEPLATFORM_SECRET (closes ytdl-org/youtube-dl#29300)

---

test/test_jsinterp.py
test/test_utils.py
test/test_youtube_signature.py
youtube_dl/compat.py
youtube_dl/jsinterp.py
youtube_dl/utils.py

<details>
<summary>Boilerplate: mixed code, bug fix</summary>
---
</details>
---
Issue #31164 reported errors with new players served by YouTube. More complex JS constructs confused yt-dl's JSInterp mini-JS interpreter.
Thanks mostly to @pukkandan, this PR fixes the problem code by back-porting from https://github.com/pukkandan/yt-dlp-dev/commit/8f53dc44a0cc1c2d98c35740b9293462c080f5d0 into the existing previously back-ported framework.
Additionally:
* supports `void` used in player 324f67b9
* improves `<<`/`>>` precedence (TODO item in …

[jsinterp] Overhaul JSInterp to handle new YT players 4c3f79c5, 324f67b9

---

test/test_jsinterp.py
test/test_youtube_signature.py
youtube_dl/jsinterp.py

<details>
<summary>Boilerplate: mixed code, improvement/bug fix</summary>
---
</details>
---
This PR continues the upgrade of the mini JS interpreter and also addresses new syntax served in player c81bbb4a served by YouTube.
The PR adds support for:
* operator ??
* operator ?.
* operator **
* accurate operator functions (resolves #31173)
* `undefined` handling
* object literals {a: 1, "b": expr}.

[jsinterp] Improve JS language support

---

test/test_jsinterp.py
test/test_youtube_signature.py
youtube_dl/jsinterp.py

<details>
<summary>Boilerplate: mixed code, bug fix/improvement</summary>
---
</details>
---
This PR adapts the changes from yt-dlp/yt-dlp@f6ca640 (thanks @pukkandan) to handle new player 1f7d5369 served by YT:
* parses regexp literals
* supports throw/catch execution
* adds parse support for regexp flags in case they should appear.
Closes #31173, had it been re-opened.

[jsinterp] Handle regexp literals and throw/catch execution

---

youtube_dl/extractor/motherless.py

Apparently the motherless.com has the "thumb-member-username" item replaced by "media-meta-member", so updating the extractor accordingly.
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.Fix #31273
Current extractor of motherless.com is unable to extract the uploader_id. For example:
```shellsession
$ ./youtube-dl -v …
```

[motherless] Fixed the broken uploader_id in the extractor.

---

test/helper.py
youtube_dl/extractor/zdf.py

<details>
<summary>Boilerplate: mixed code, bug fix</summary>
---
</details>
---
Updates ZDF extractors using some yt-dlp code and test-cases, and fixes and improves `ZDFChannelIE`. For more details, see the commit messages.
Also adds a new expected value for test cases, like this
```js
'info_dict': {
...
'field': 'lambda x: some_expression(x)',
...
```
This test succeeds iff the `some_expression(got)` is true.
The test syntax is used here to test that none of the playlist items is one of the known non-video items on the page that should have been …

[ZDF] Overhaul extractors

---

test/test_aes.py
youtube_dl/aes.py
youtube_dl/extractor/neteasemusic.py

---
---
Netease music downloading was broken for a long time, based on @TianyiShi2001's research https://github.com/ytdl-org/youtube-dl/issues/18051#issuecomment-859964832, I finally get the download url through player api and fixed it.
fixes #11216 
fixes #11365
fixes #18051

[netease] Get netease music download url through player api

---

youtube_dl/extractor/adn.py

[ADN] Rename Anime Digital Network to Animation Digital Network.
~~As adverted on the home page: https://animationdigitalnetwork.fr/~~
Edit: It's not advertised anymore since the 12/10.
---
It's a fix of the extractor. Everything generally work but a few thing need to be updated.
First, to use this extractor, we have to update the URL since ADN rename itself from “Anime” to “Animation”.  
Initially, that wasn't the only goal of that PR. But reading the extractor tutorial and testing my code lead to two other commits.
> Anime Digital Network se transforme en Animation Digital Network !!
> Pensez à mettre à jour votre URL.
That can be translated to :
> Anime Digital Network is changing to Animation Digital Network!
> Remember to update your URL.
It's exactly what I'm doing.
Fix #31273
Then, …

Fix ADN extractor

---

test/test_utils.py
youtube_dl/utils.py

---
---
Backport `traverse_obj` from yt-dlp required for https://github.com/ytdl-org/youtube-dl/pull/31097

[utils] Backport traverse_obj (etc) from yt-dlp

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/pr0gramm.py

---
---
Implement extractor for Pr0gramm social media. Pr0gramm did not work with the generic IE fallback, because page content is loaded dynamically with JS. Basically: it "re-routes" regular urls, encountered by end users, to a compatibility-page served statically (provided by Pr0gramm), which does contain video information. From here, metadata and video information is extracted.
This is primarily meant for urls like `https://pr0gramm.com/new/video/5466437`, `https://pr0gramm.com/new/5466437`, but obviously also provides support for the static …

[pr0gramm] implement InfoExtractor, Resolves #31433

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/fifa.py

<details>
<summary>Boilerplate: mixed code, new extractor</summary>
---
</details>
---
Back-port of yt-dlp FIFA extractor as requested in #31365.

[FIFA] Back-port extractor from yt-dlp

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/rbgtum.py

---
New extractor for https://live.rbg.tum.de/ lecture streaming site.
This supersedes, closes #27362.

[rbgtum] Add new extractor

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/filemoon.py

---
---
Adds support for filemoon.sx
Resolves #31126

[FileMoonIE] Add extractor for filemoon.sx

---

test/test_download.py
youtube_dl/extractor/youtube.py

<details>
<summary>Boilerplate: own code, bug fix</summary>
---
</details>
According to #31530, YouTube has changed its metadata so that the owner URL has the format `.../@ownerslug` rather than `.../user/user_id` or `.../channel/channel_id`. Some, if not all, music videos retain the previous scheme.
This caused several problems:
1. Owing to an extraction bug, failing to match the previous patterns crashed the extractor.
2. After resolving the crash, various metadata items were not being extracted, and some [study was needed to work out what …

[YouTube] Support @owner format in uploader_id etc

---

youtube_dl/YoutubeDL.py

---
This is a follow up to fe7e130 I think which didn't fix everything.
Sample failing command:
```
> youtube-dl --print-json "https://www.youtube.com/watch?v=SrK1yv3g8dI"
File "/home/gabi/.local/bin/youtube-dl", line 8, in <module>
sys.exit(main())
File "/home/gabi/.local/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
_real_main(argv)
File "/home/gabi/.local/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
retcode = ydl.download(all_urls)
File "/home/gabi/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2085, in download
res = self.extract_info(
File "/home/gabi/.local/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in extract_info
return self.__extract_info(url, …
```

Sanitize info dict before dumping JSON

---

.github/workflows/ci.yml
test/helper.py
test/test_YoutubeDL.py
test/test_YoutubeDLCookieJar.py
test/test_downloader_external.py
test/test_execution.py
test/test_http.py
test/test_utils.py
youtube_dl/YoutubeDL.py
youtube_dl/compat.py
youtube_dl/downloader/common.py
youtube_dl/downloader/external.py
youtube_dl/jsinterp.py
youtube_dl/options.py
youtube_dl/utils.py

<details>
<summary>Boilerplate: mixed code, improvement</summary>
---
</details>
---
During file downloads, youtube-dl or the external downloaders that it invokes may leak cookies on HTTP redirects to a different host, or leak them when the host for download fragments differs from their parent manifest's host.
This PR implements various remediations to avoid this behaviour:
* removing the Cookie header upon HTTP redirects
* having native downloaders calculate their own Cookie header from the Cookiejar
* using each external downloader's built-in …

Remediate File Downloader cookie leak

---

.github/workflows/ci.yml
test/test_http.py
test/test_utils.py
youtube_dl/YoutubeDL.py
youtube_dl/compat.py
youtube_dl/utils.py

<details>
<summary>Boilerplate: own/yt-dlp code, bug fix/improvement</summary>
---
</details>
---
This PR encapsulates various under-the-hood fixes, improvements and tests.
* Process `Content-Encoding`s according to [RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110):
- support nested encodings
- support `br` encoding, if _Brotli_ package is installed (`pip install brotli`, ["Only Python 2.7+ is supported."](https://github.com/google/brotli/blob/master/python/README.md) -- Only?)
- support 'compress' encoding, if _ncompress_ package is …

[Misc] Under-the-hood fixes, improvements and tests (pt 2)

---

youtube_dl/compat.py
youtube_dl/swfinterp.py
youtube_dl/utils.py

<details>
<summary>Boilerplate: own/yt-dlp code, bug fix/improvement</summary>
---
</details>
---
After merging #32481, one [further change](https://github.com/ytdl-org/youtube-dl/pull/32481#discussion_r1278527838) was needed. Meanwhile new _flake8_ Linter rules appeared. This PR addresses both.
To pass new Linter rules, direct comparison to `type`s is reworked and at the same time `isinstance()` tests (especially for str/unicode/bytes) are revised, avoiding actual Python version tests as far as possible

[Misc] Under-the-hood fixes, improvements and tests (pt 3)

---

.github/workflows/ci.yml
youtube_dl/extractor/youtube.py
youtube_dl/utils.py

<details>
<summary>Boilerplate: own code/#36238, bug fix/improvement</summary>
---
</details>
---
1. Resubmit youtube consent fix with better log message
2. Ensure _apt_ is updated for Ubuntu runners
3. Fix CI not selecting correct default settings for `push` and `pull_request` events
4. Add 3.12 to standard CPythons and generalise pre-release build steps for a future beta (3.next)
5. Improve filename handling for `--restrict-filenames`: ignore any character in Unicode categories Mark and Other instead of mapping it to `_`.

[CI/cleanup/restrict_strip_Marks] 

---

youtube_dl/extractor/telewebion.py

---
---
This pull request fixes the problem of downloading videos from telewebion and uses its new api.

[telewebion] fix extraction

---

youtube_dl/extractor/epidemicsound.py
youtube_dl/extractor/extractors.py

[Epidemic Sound] Add new extractor

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/gbnews.py

---
---
Issue #29341 identified the need for an extractor for the new GB News channel from the UK, and demonstrated extraction using a shell script.
This PR adds an extractor for the two types of GB News URLs (clips, live) shown in the issue, using the procedure from the issue.
The live stream appears to operate OK with a shell command line piping yt-dl output to `mpv`, but hasn't been extensively exercised.
Closes #29341.

[GBNews]Add new extractor for GB News TV channel

---

youtube_dl/extractor/caffeine.py
youtube_dl/extractor/extractors.py

---
---
Add info extractor to support site [caffeine.tv](https://www.caffeine.tv/)
Closes #31016

[caffeine.tv] Add new extractor

---

youtube_dl/extractor/vimeo.py

---
- N/A Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
---
Vimeo's playerConfig now no longer ends in `;` or `\n`, but can end directly with `</script>`.
A sample video for your testing: https://player.vimeo.com/video/792852679
```
<script>window.playerConfig = {"cdn_url": .................... }</script>
```
This fails the original regex `(?s)\b(?:playerC|c)onfig\s*=\s*({.+?})\s*[;\n]`.
I modified it to `(?s)\b(?:playerC|c)onfig\s*=\s*({.+?})\s*(?:;|\n|\<\/script\>)` so it now works.

[Vimeo]  fix config parser regex

---

youtube_dl/extractor/youtube.py

[Youtube] Fix AttributeError no attribute '_YoutubeIE__ie_msg' if unable to decode n-parameter

---

test/test_downloader_external.py
youtube_dl/compat.py
youtube_dl/downloader/external.py
youtube_dl/postprocessor/ffmpeg.py
youtube_dl/utils.py

<details><summary>Boilerplate: own code/bug fix</summary>
---
---
</details>
The ffmpeg downloader `FFmpegFD` depends on the corresponding post-processor `FFmpegPostProcessor`. The availability of a downloader is a class property, while the availability of a post-processor is an instance property. Due to a combination of code issues, a viable _ffmpeg_ installation might not be found for downloading when a custom location was specified with `--ffmpeg-location ...` or its API equivalent, as in #32735.
This PR fixes the issue by splitting the …

[external/FFmpegFD] Fix ffmpeg detection with `--ffmpeg-location ...` (etc)

---

youtube_dl/extractor/common.py
youtube_dl/utils.py

---
When subs are not available and `_report_ignoring_subs` is called, it crashes because it passes an argument to `bug_reports_message`, which accepts none.
I changed it to be appended to the message, like what's done in other places.
Now the message is like this:
> WARNING: [youtube] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, ; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
The ", ;" is not correct but I don't know if you want to get rid of the semicolon. The important thing is that it doesn't crash, and the file can be downloaded.

[extractor/common] Fix crash in _report_ignoring_subs

---

test/test_download.py
youtube_dl/extractor/extractors.py
youtube_dl/extractor/youporn.py

<details><summary>Boilerplate: own/yt-dlp code, bug fix/improvement</summary>
---
---
</details>
This PR aligns the YouPorn extractor with yt-dlp extractor and fixes the problem reported in https://github.com/yt-dlp/yt-dlp/issues/7967. It also adds playlist extractors.
Summary of changes to the `YouPornIE` ezxtractor:
* extract from webpage instead of API (broken) per https://github.com/yt-dlp/yt-dlp/issues/7967#issuecomment-1695618360, and (thx @The-MAGI) https://github.com/yt-dlp/yt-dlp/pull/8827
* improve extraction with `traverse_obj()` 
* …

[YouPorn] Fix and improve extraction; add playlist extraction

---

youtube_dl/extractor/mixcloud.py

---
---
The mixcloud API address changed from www.mixcloud.com/graphql to app.mixcloud.com/graphql
This PR updates the address to restore functionality.

[mixcloud] updated mixcloud API server address

---

test/helper.py
test/test_download.py
youtube_dl/YoutubeDL.py
youtube_dl/extractor/extractors.py
youtube_dl/extractor/orf.py

<details><summary>Boilerplate: own/yt-dlp code, fix/new extractor</summary>
---
---
</details>
This PR overhauls and brings up-to-date the ORF extractor module.
TV is now handled by the on.orf.at single-page-app, replacing the former TVthek. The PR back-ports the `ORFONIE` recently added to yt-dlp to replace the broken `ORFTVthekIE`: thx @HobbyistDev, @TuxCoder, @seproDev. Resolves #32798.
Some shows (former extended live events?) may be returned as `multi_video` playlists: yt-dl has no support for automatic concatenation of `multi_video` …

[ORF] Extractor overhaul

---

youtube_dl/extractor/vidlii.py

---
---
Adds HD support to VidLii.
This was originally done in #29291, but I deleted that fork a long time ago so I can't make any more edits to it.

[VidLii] Add 720p support (yt-dlp backport-ish)

---

test/test_jsinterp.py
test/test_youtube_signature.py
youtube_dl/extractor/common.py
youtube_dl/extractor/palcomp3.py
youtube_dl/jsinterp.py
youtube_dl/utils.py

<details><summary>Boilerplate: own/yt-dlp code, fix/improvement</summary>
---
---
</details>
YT player `590f65a6` revealed a [bug in arithmetic evaluation](https://github.com/ytdl-org/youtube-dl/issues/32815#issuecomment-2176720409) in the JSInterpreter module. The PR corrects this and also makes a previously failing proposed test work; resolves #32815.
The bug also revealed some incomplete or inadequate back-porting:
* following yt-dlp, `orig_msg` is now set in `ExtractorError`
* an invalid integer format in an error message was changed to `!r` …

[jsinterp] Support YT player 590f65a6

---

youtube_dl/extractor/yandexmusic.py

---
Improved the Yandex Music extractor: if cookies with authorization from a premium account are specified, then the extracted URL refers to **H**igh **Q**uality (320 kbps)

[YandexMusic] downloads music in High Quality (320 Kbit/s)

---

youtube_dl/extractor/palcomp3.py
youtube_dl/extractor/yandexmusic.py

---
YandexMusic stores the track title and its version in sepatate fields.
For example, both of this tracks will be downloaded with the same title "Til The End".
I want to concatenate title and version in a single field and save it as "Til The End (Super Flu Remix)"
Also I would like to merge #31159 here.

[YandexMusic] Save track version in the title field

---

youtube_dl/YoutubeDL.py

<details><summary>Boilerplate: own/yt-dlp code, fix</summary>
---
---
</details>
A small change to core processing was needed for [compatibility with the back-ported security patch](https://github.com/ytdl-org/youtube-dl/issues/32838#issuecomment-2211839595) in #32830. Also, there was a small bug in formatting the exception report for the security mitigation.
Fixes #32838.
Thanks @eyaler for the report.

[core] Fix PR #32830 for fixed extensionless output template

---

test/test_youtube_signature.py
youtube_dl/extractor/youtube.py

---
---
Fixes nsig extraction for youtube 
See #32885

applied @dirkf's patches for nsig extraction on youtube

---

test/test_jsinterp.py
test/test_youtube_signature.py
youtube_dl/casefold.py
youtube_dl/compat.py
youtube_dl/jsinterp.py

<details>
<summary>Boilerplate: own code, bug fix</summary>
---
---
</details>
This PR improves argument coercion for bit-shift (and by extension, other bit-oriented operations) to cater for `float` together with other not-apparently-bit values, some of which were formerly checked individually. Fixes #33048.
Also included is a pending clean-up of an accidentally public `compat` interface.

[YouTube]  Fix bit-shift coercion for player 9c6dfc4a

---

test/test_cache.py
test/test_jsinterp.py
test/test_youtube_signature.py
youtube_dl/YoutubeDL.py
youtube_dl/cache.py
youtube_dl/compat.py
youtube_dl/extractor/common.py
youtube_dl/extractor/youtube.py
youtube_dl/jsinterp.py
youtube_dl/utils.py
youtube_dl/version.py

<details><summary>Boilerplate: own+yt-dlp code/bug fix+improvement</summary>
---
---
</details>
The main object of this PR is to update the Youtube extractor to handle the latest players and improve compatibility with _yt-dlp_:
* [cache] now uses similar logic to yt-dlp, but with the modified `esc_rfc3986()` encoding cache keys, for Py2/3 compat
* [JSInterp]
- various refactoring
- unary operator handling is improved, now supporting `!`
* [JSInterp] Updates from _yt-dlp_
- improve nested attribute support, attribute syntax prioritised over …

[YouTube] Update extractor for 2025-04, etc
