youtube_dl/extractor/__init__.py
youtube_dl/extractor/vier.py

[vier] Add new extractor

---

youtube_dl/extractor/ellentv.py

Added support for EllenTube with EllenTV

Added support for EllenTube along with EllenTV

---

youtube_dl/extractor/tf1.py

fixes #4620
can't get the test to pass though - seems to be looking for the wrong json file? any idea what i am doing wrong?

[tf1] add support for TFOU

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/radiobremen.py

Add support for Radiobremen as asked in Issue #4546

Add support for Radio Bremen

---

.gitignore
youtube_dl/extractor/auengine.py

The way the video download url was been extracted was
not working well so i change it for it to extract the
correct url

[Auengine] corrected extractions logic

---

README.md

<Yourname> changed to <user name>, which is more general.

Change path name to MSDN standard.

---

youtube_dl/downloader/f4m.py

Metadata may be missing, and correctly write the metadata tag length

[downloader/f4m] Improved metadata handling

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/audiomack.py

* Updated the api call to return more JSON info (as opposed to page scraping)
* Caught additional inconsistent error messages
* Added cases to fill in missing metadata with mediocre values, as opposed to failing all together
* Added audiomack album/playlist class to support album downloads

Push API updates to simplify code, better error handling, add support for albums

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/streetvoice.py

tw.streetvoice.com is an online music sharing platform for independent bands in Taiwan.

[StreetVoice] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/xuite.py

vlog.xuite.net, or Xuite影音, is a video and audio sharing platform hosted by Hinet, largest ISP in Taiwan.

[xuite] Add new extractor

---

youtube_dl/extractor/srmediathek.py

fix srmediathek description

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/nextmedia.py

NextMedia is a company publishing Chinese news in Hong Kong and Taiwan. Some news come with fascnating videos or animations.

[NextMedia] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/ctsnews.py

Cts, or Chinese Television System [www.cts.com.tw], is a television channel provider in Taiwan, who provides lots of news videos.

[CtsNews] Add new extractor

---

youtube_dl/extractor/globo.py

I've fixed an error (#4346) on some globo videos. The problem was that some videos have a m3u playlist listed on the format's list. I'm new to python and youtube-dl, so I don't know if my fix is the best possible.

[globo] Fix error on some globo videos #4346

---

youtube_dl/extractor/npo.py

Add NPO.nl subtitles

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/camdemy.py

Camdemy is a teaching video sharing platform in Taiwan.

Add support for camdemy.com

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/nporadio.py

[nporadio] Add extractor for live radio

---

youtube_dl/extractor/nbc.py

This fixes issue #4884 for me. I am not a Python programmer and this is my first code contribution to youtube-dl so please forgive me if my code is not sufficiently Pythonic or not according to your coding style.

Support NBC Nightly News broadcasts

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/yam.py
youtube_dl/utils.py

Yam.com is an audio and video sharing platform in Taiwan [http://mymedia.yam.com]

[Yam] Add new extractor

---

youtube_dl/extractor/ted.py

TED extractor: prefer 'code' to 'uri' if present

---

youtube_dl/extractor/eporner.py

Hi. I updated the eporner extractor to work. That are my first steps at github, I hope that I'm doing this well...

Eporner Fix

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/letv.py

Letv.com is a video publishing platform in China

[Letv] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/puls4.py

[puls4] Add new extractor

---

youtube_dl/YoutubeDL.py
youtube_dl/__init__.py
youtube_dl/extractor/letv.py
youtube_dl/options.py
youtube_dl/utils.py

Needs to be tested; example proxy does not work for me.

[letv] Add --cn-verification-proxy (Closes #5077)

---

youtube_dl/extractor/yam.py

The original test case _1 does not exist anymore.

[Yam] Add an error detection and update test cases

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/douyutv.py

douyutv is a video broadcast platform in China

[douyutv] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/safari.py

Following on from https://github.com/rg3/youtube-dl/issues/5253, I decided to give implementing this a go myself.

Add safaribooksonline extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/dhm.py

Add a new extractor for the video collection of the German historical museum

Add dhm extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/dumpert.py

Add support for the Dutch video site Dumpert. http://www.dumpert.nl/

[Dumpert] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/generic.py
youtube_dl/extractor/nbc.py
youtube_dl/extractor/theplatform.py
youtube_dl/extractor/yahoo.py

This should fix #5226 
I also addd an ```NBCSportsIE```. ```YahooIE``` and ```NBCSportsIE``` are both based on ```NBCSportsVPlayerIE```. I put ```NBCSportsIE``` and ```NBCSportsVPlayerIE``` before ```NBCNewsIE``` because they're more relevant to ```NBCIE```.

[Yahoo/NBCSports] Fix 5226 and add support for NBC sports

---

youtube_dl/extractor/douyutv.py

douyutv.com (斗鱼) has recently changed how urls are calculated. I've posted a working version here. Note that the key ('1231') may change in the future.
I've also improved error handling so that comprensive error messages are shown when API requests failed (due to wrong key, etc.)

[douyutv] Fix extractor and improve error handling

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/varzesh3.py

Adds support for video.varzesh3.com, a famous Iranian sports video sharing website.

[Varzesh3] Add new extractor

---

docs/supportedsites.md
youtube_dl/extractor/__init__.py
youtube_dl/extractor/miomio_tv.py

added entry for high lag video site http://www.miomio.tv
(contains a range of content mostly in asian languages including instructional and promotional videos e.g. http://www.miomio.tv/teach/draw/)

[MiomioTv] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/radiojavan.py

Adds support for Iranian famous music-video sharing website, RadioJavan.

[RadioJavan] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/gamersyde.py

Added support for Gamersyde a resource of unedited high quality (1080p60) video game footage

[Gamersyde] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/pornovoisines.py

Add a new extractor for French porn site [Porno Voisines](http://www.pornovoisines.com/) (a.k.a. Jacquie et Michel).

[pornovoisines] Add extractor

---

youtube_dl/options.py

For consistency and readability

Clean up of --help output

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/crooksandliars.py

And by the way, I wish the generic extractor would simply download the webpage and match all extractors against all the iframe and embed tags in the webpage. Could have saved me a bit of trouble.

crooksandliars.com extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/gfycat.py

Gfycat support for issue #5394
Pull request is similar to #5439 but uses gfycats' built in json api, we discussed this in #5394.
First time coding python so any pointers on what I did wrong (if I did) is appreciated.

[gfycat] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/philharmoniedeparis.py

New extractor: live.philharmoniedeparis.fr

---

youtube_dl/extractor/noco.py

Get the user audio language preference in order to retrieve video with chosen language instead of 'fr'.

[noco] Retrieve video language according to user options

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/southpark.py

I added an extractor for the southpark.nl site. Also fixed a naming inconsistency in the German extractor.

Southparknl

---

youtube_dl/YoutubeDL.py

[YoutubeDL] Do not force bestvideo+bestaudio when outtmpl is stdout

---

youtube_dl/extractor/br.py

The videos for the first 2 test cases no longer exist. Replaced with new videos.

[BRIE] Updated two test cases

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/voicerepublic.py

Hello! Just a little extractor for Voice Republic, which hosts spoken word audio content.

[voicerepublic] Add new extractor

---

youtube_dl/extractor/byutv.py

Test currently fails because thumbnail regex is no longer valid. Have relaxed regex expression to fix this.

[BYUtvIE] Relax thumbnail regex so test does not fail

---

youtube_dl/extractor/canalplus.py

[CanalplusIE] Update tests that were no longer working

---

youtube_dl/YoutubeDL.py
youtube_dl/postprocessor/ffmpeg.py

Fallback to `-f best` when merger is outdated

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/qqmusic.py

Support QQ music charts, for example: http://y.qq.com/#type=toplist&p=top_6 and http://y.qq.com/#type=toplist&p=global_12

[qqmusic] Add support for charts / top lists

---

youtube_dl/extractor/sportbox.py

Sportbox.ru extractor was fixed. HD videos support was added.

Sportbox fix

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/viki.py

Add support for shows, example: http://www.viki.com/tv/50c-boys-over-flowers

[viki] Add support for shows

---

README.md

After installing youtube-dl with this method
sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+x /usr/local/bin/youtube-dl
When i try to use it, i get this error
python: can't open file '/usr/local/bin/youtube-dl': [Errno 13] Permission denied
The correct chmod is a+xr

[README.md] chmod error

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/porn91.py

An extractor for 91porn.com -- A popular Chinese amateur porn site.
[WARN] 91porn.com has a limit for downloading, one ip could download 10 videos among 24h.
-----
This one will be good.

[porn91] Add new extractor for 91porn.com

---

youtube_dl/extractor/qqmusic.py

QQ Music recently changed their page structure for top lists/charts. A json page is now available for extracting top list info and songs.

[qqmusic] Fix toplist extraction

---

youtube_dl/extractor/qqmusic.py

Add support for higher quality downloads.

[qqmusic] Extract additional formats (mp3-128, mp3-320)

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/iqiyi.py

I use the method that @jackyzy823 found at [here](https://github.com/jackyzy823/you-get/blob/iqiyi-key-again/src/you_get/extractors/iqiyi.py) to generate iqiyi video_url.
Also, I got this [permission](https://github.com/soimort/you-get/pull/523) to use his algorithm to code.
If there is a copyright problem, let me know.
@yan12125

[iqiyi] Add new extractor for iqiyi.com

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/ruutu.py

Added an extractor for ruutu.fi

[Ruutu] Add new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/tvc.py

[tvc] Add extractor (Closes #5795)

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/fivetv.py

[fivetv] Add extractor (Closes #5794)

---

youtube_dl/extractor/brightcove.py

found in http://www.americanbar.org/groups/family_law.html and
http://america.aljazeera.com/watch/shows/america-tonight/2015/6/exclusive-hunting-isil-with-the-pkk.html

Brightcove extractor: support customBC.createVideo(...); method (america.aljazeera.com and others)

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/dramafever.py

DramaFever is fairly popular video streaming service, with a large inventory of Asian dramas and movies.

[dramafever] Add new extractor for dramafever.com

---

youtube_dl/YoutubeDL.py

spelling mistake corrected

---

youtube_dl/extractor/youku.py

Now, the old script gets invalid video_urls, because youku changed its algorithm.  
The commit updates algorithm, generating valid video_urls.  
------
Getting video_url directly from api and algorithm, not from m3u8 file which has incomplete video_url.

[youku] update youku

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/pinkbike.py

Solves https://github.com/rg3/youtube-dl/issues/5791.

[pinkbike] new extractor

---

youtube_dl/extractor/planetaplay.py
youtube_dl/extractor/quickvid.py
youtube_dl/extractor/vube.py

Try to solve #5289. In not a long term solution but practical for now.

[planetaplay/quickvid/vube] Skip inaccessible sites

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/moviefap.py

Extractor for http://moviefap.com/.
Checked with flake8.

[moviefap] Add new extractor

---

youtube_dl/extractor/nrk.py

Add s? to regexp to support new urls. Update testcases to use HTTPS.

NRK now supports / requires HTTPS

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/qqmusic.py

For example: http://y.qq.com/#type=taoge&id=3462654915

[qqmusic] Add support for playlists

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/yinyuetai.py

[YinYueTai] (https://en.wikipedia.org/wiki/YinYueTai) is a major Chinese music video streaming site.
Copyright: http://www.yinyuetai.com/article/4 (Chinese)
Pertinent section roughly translated:
> YinYueTai has copyright agreements with famous music companies such as Universal Music, Warner Music, Sony Music, HIM International Music, JVR Music, EEG Music, Rock Records, B'in Music, Ocean Butterflies, Avex Entertainment, Fresh Music, South Korea's SM Entertainment, JYP Entertainment, YG Entertainment, as well as foreign television stations such as MBC and KBS.

[yinyuetai] New extractor for yinyuetai.com

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/neteasemusic.py

http://music.163.com is the music streaming service from [NetEase/网易] (https://en.wikipedia.org/wiki/NetEase).
The site does not geo-restrict AFAIK and has hq downloads available. No login is required.

[neteasemusic] Add new extractor for music.163.com

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/kuwo.py

Kuwo is a legal Chinese music streaming service (similar to qqmusic).

[kuwo] New extractor for kuwo.cn

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/webofstories.py

I've tested this by downloading the entire [Donald Knuth](http://www.webofstories.com/playAll/donald.knuth) playlist :smile_cat:

Added a Playlist Info Extractor for WebOfStories

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/rdsca.py

[rdsca] New extractor

---

youtube_dl/extractor/vice.py

ex: https://news.vice.com/video/experimenting-on-animals-inside-the-monkey-lab

fix/support news.vice.com

---

youtube_dl/extractor/common.py
youtube_dl/extractor/youtube.py

Simpler version of this pull request: https://github.com/rg3/youtube-dl/pull/6389

[youtube] save keywords in info jason when --write-info-json is used

---

youtube_dl/extractor/youtube.py

Adds support for downloading multifeed videos (from multiple cameras) as playlist (e.g. https://www.youtube.com/watch?v=jqWvoWXjCVs)

[youtube] Add support for multifeed videos

---

youtube_dl/extractor/vidme.py

related to this issue https://github.com/rg3/youtube-dl/issues/6403

[vidme] extract the uploader

---

youtube_dl/extractor/facebook.py

related to this issue https://github.com/rg3/youtube-dl/issues/4591.
for the does not provide the resolution for both formats(sd,hd)

[facebook] extract uploader

---

youtube_dl/extractor/clipfish.py

it should solve the problem for this issues:https://github.com/rg3/youtube-dl/issues/4492 https://github.com/rg3/youtube-dl/issues/3362 https://github.com/rg3/youtube-dl/issues/1842

[clipfish] extract mp4 video link

---

youtube_dl/extractor/iqiyi.py

Update the md5 salt for iqiyi's player `MainPlayer_5_2_26_c3_3_7_1.swf` (updated at 2015-08-10).

 [iqiyi] update md5 salt (2015-08-10)

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/rtvnh.py
youtube_dl/extractor/rtvnhnl.py

This resolves #6479.
NOTE: The rtmp-1564 format has the best quality but it's not selected by default since it uses the rtmp protocol.

[rtvnhnl] Added new extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/playtvak.py

Support for videos in articles from idnes.cz, lidovky.cz, metro.cz, as
well as video and live streams from playtvak.cz
Signed-off-by: Ondřej Caletka <ondrej@caletka.cz>

[playtvak] Initial support for videos from Mafra group servers

---

youtube_dl/extractor/nowvideo.py

Added ec extension to nowvideo extractor

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/vlive.py

"V" http://www.vlive.tv is a live broadcasting mobile platform targeted at South Korean celebrities
Similar to Periscope, videos are available for viewing after the live broadcast, but only on the app for now.
Example: http://m.vlive.tv/video/1326

[vlive] New extractor for vlive.tv

---

youtube_dl/extractor/yahoo.py

and about the test with this url:https://ca.sports.yahoo.com/video/program-makes-hockey-more-affordable-013127711.html
it's not available anymore.

[yahoo] change test md5 checksum

---

youtube_dl/extractor/tudou.py

for http://www.tudou.com/albumplay/cJAHGih4yYg.html

[tudou]Fix extraction

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/ndr.py

i can't test it(cannot download extracted videos urls because of geolocation(i get timeout) i can only access the json request) if someone has access to the site and can run the tests and check if they need to be changed(md5,...).

[ndr] fix info extraction

---

README.md

Add the missing tag `EMBEDDING YOUTUBE-DL` in the content table.

---

youtube_dl/extractor/fktv.py

completion of this commit 4866b72eb2bf5747cde4654e75b1c1be0d456456

[fktv] get format_id from video file ext

---

youtube_dl/extractor/nowtv.py

now the download works for me
thx to http://board.gulli.com/thread/1251646-videos-von-webseiten-runterladen-sammelthread-alle-fragen-hier-rein-/?p=14980081#post14980081

FIX: nowtv

---

youtube_dl/YoutubeDL.py
youtube_dl/compat.py
youtube_dl/downloader/hls.py
youtube_dl/extractor/letv.py
youtube_dl/utils.py

This is an enhancement of #6376. This patch also fixes #6192 and #7144.
```compat_urllib_request_DataHandler``` is ported from [cpython hg rev 1733b3bd46db](https://hg.python.org/cpython/file/1733b3bd46db/Lib/urllib/request.py#l1599).
Cc @jaimeMF

[Letv] Fix extraction

---

youtube_dl/extractor/zdf.py

This commit adds thumbnail support to the ZDF Mediathek extractor

adds thumbnail support for ZDF Mediathek extractor

---

youtube_dl/extractor/vidme.py

It seem that vidme does not return "formats" in the API response in some cases, but we can still use the "complete_url" field from there. See e.g. https://vid.me/e5g

[vidme] Stream URL fallback, better error message for suspended videos

---

youtube_dl/extractor/vimeo.py

Example video that fails - https://vimeo.com/109815029

[vimeo] Fix error parsing

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/democracynow.py

Supports downloading clips or entire shows. Subtitle support

Add support for democracynow.org

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/brightcove.py
youtube_dl/extractor/generic.py
youtube_dl/utils.py

the same error happen here again (https://github.com/rg3/youtube-dl/pull/6785#issue-105191077) if someone has access to the site and can run the tests and check if they need to be changed

[brightcove] add support for brightcove in page embed(fixes #6824)(fixes #5946)

---

README.md
youtube_dl/YoutubeDL.py
youtube_dl/options.py

Clarify that automatic means automatically generated.

Clarify that automatic subtitles are generated.

---

youtube_dl/extractor/youtube.py

Fixed downloads for these videos:
- https://www.youtube.com/watch?v=Ms7iBXnlUO8
- https://www.youtube.com/watch?v=lsguqyKfVQg

[youtube] More explicit player config JSON extraction (fixes #7468)

---

youtube_dl/extractor/sohu.py

[sohu]fix 403 forbidden

---

youtube_dl/extractor/youku.py

Fixed the Issue #7627. According the download Json data, changed the video url construct a bit.

Issues # 7627

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/generic.py
youtube_dl/extractor/googledrive.py

it should closes #2231,#1701,#3351

[googledrive] Add new extractor

---

youtube_dl/extractor/comcarcoff.py

This is a trivial tweak to fix the Comedians in Cars Getting Coffee extractor. Fixes issue #7941 for me. 
Please let me know if I've missed anything -- I feel like I have no idea what I'm doing.

[comcarcoff] adjust for json updates

---

youtube_dl/extractor/__init__.py

Extractor got deleted in remitamine/youtube-dl@8af2804

Remove testtube import

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/bigflix.py

Add an IE to support bigflix.com. It uses some sort of silverlight
plugin whose video url is being populated using base64 encoded
flashvars. So it is quite straightforward to extract.

[Bigflix] Add new extractor for bigflix.com

---

youtube_dl/extractor/neteasemusic.py

203.130.59.9 is a reverse proxy for the netease cdn [via https://github.com/Unblocker/Unblock-Youku/issues/488#issuecomment-162314538]

[neteasemusic] Fixes #8239

---

youtube_dl/extractor/daum.py

[daum.net] Fixes #8331

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/npo.py

[schooltv] Add extractor for SchoolTV playlists

---

youtube_dl/extractor/__init__.py
youtube_dl/extractor/daum.py

[daum.net] Support for playlists, user channels

---

youtube_dl/extractor/rte.py

This is useful as
a) RTMP downloads are a good deal faster to download
b) Older items are available only as RTMP streams

[rte:radio] Add support for RTMP downloads, alternate URL style

---

youtube_dl/__init__.py
youtube_dl/extractor/common.py
youtube_dl/extractor/youtube.py
youtube_dl/options.py

Introduces an option to mark videos watched. For that to work user must be authenticated either via credentials or a cookie file.

Add --mark-watched feature (Closes #5054)

---

test/test_utils.py
youtube_dl/extractor/common.py
youtube_dl/utils.py

it a common task to create or update query string params, it will be simpler to use this helper method.

[extractor/common] add update_url_params helper method to add or update query string params

---

youtube_dl/extractor/kaltura.py
youtube_dl/extractor/safari.py

it should also simplify fixing extractor(i think it require only extracting and adding the `flashvars[ks]` to the url).
https://blog.kaltura.com/create-ks-protected-videos-with-free-preview/

[safari] extract free and preview videos(#7491)

---

test/test_utils.py
youtube_dl/compat.py
youtube_dl/utils.py

Optional poster group and greedy matching caused poster="..."
to be dropped. This makes test_Twitter_1 pass.

[twitter] Fix thumbnail matching for Twitter.

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/presstv.py

[presstv] Added extractor for PressTV.

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/mixcloud.py

Implemented support for Mixcloud user uploads, playlists, favorites and listens.
Fixes #3750 and #5272

[mixcloud] Added support for user uploads, playlists, etc.

---

test/test_utils.py
youtube_dl/utils.py

related to the previous work on dash support https://github.com/rg3/youtube-dl/pull/8408#issuecomment-179783768.

[utils] imporove parse_duration to handle more formats

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/mwave.py

Adds support for alternate URLs to the existing mwave.interest.me extractor

[mwave] Add Mwave Meet & Greet extractor

---

test/test_utils.py
youtube_dl/utils.py

Fixed https://github.com/rg3/youtube-dl/issues/9347.

Feature: --restrict-filenames: replace accented characters by their unaccented counterpart instead of "_"

---

youtube_dl/__init__.py

Expand user's home in batch file path.

---

youtube_dl/downloader/hls.py

This PR introduces the delegation feature for native hls downloader: i.e. native hls downloader will delegate extraction to `FFmpegFD` when it realizes that it's not capable of downloading requested stream.
This can be useful when:
- Some extractor forces `entry_protocol='m3u8_native'` in `InfoExtractor._extract_m3u8_formats` but eventually (e.g. due to some change on remote side) incoming manifest start using features hlsnative does not support.
- When one forces `--hls-prefer-native` (e.g. in configuration file) and tries to download stream hlsnative is not capable to.
If we carefully craft the set of unsupported features we can even force `m3u8_native=True` in `InfoExtractor._extract_m3u8_formats` though this will require additional request to download manifest all the time when …

[downloader/hls] Delegate extraction to ffmpeg when unsupported features detected

---

youtube_dl/extractor/bandcamp.py

[bandcamp] raise ExtractorError when track not streamable

---

youtube_dl/extractor/vlive.py

Changes:
* Fix video params extraction
* Don't make status request since status info now available on the page
* Remove unneeded code
* Fix test

[vlive] Address site update

---

.gitignore

Gathered intellij related ignoring patterns into one group

ignored intellij related files

---

README.md

curl normally don't follow redirects.
Use the -L switch.

curl: follow redirect

---

youtube_dl/extractor/vlive.py

Same as common statuses just with "PRODUCT_" prefix:
PRODUCE_LIVE_END, PRODUCT_COMING_SOON, etc.

[vlive] Acknowledge vlive+ streams statuses

---

youtube_dl/utils.py

[utils] Change Firefox 44 to 47

---

youtube_dl/extractor/radiocanada.py
youtube_dl/extractor/toutv.py

there is problem with rtmp download, i don't realy know what's missing.
i created the PR even if it has this problem, so it can be simple for others to modify and test.

[toutv] fix info extraction(closes #1792)(closes #2082)

---

test/test_utils.py
youtube_dl/extractor/common.py
youtube_dl/utils.py

as @dstftw suggested https://github.com/rg3/youtube-dl/pull/6811#issuecomment-139282386, a separate method to extract html5 media entries.

[extractor/common] add helper method to extract html5 media entries

---

youtube_dl/YoutubeDL.py

Fix line endings handling for downloaded web pages #10268

---

youtube_dl/extractor/charlierose.py
youtube_dl/extractor/extractors.py

---
---
This adds an extractor for charlierose.com

[charlierose] Add new extractor (closes #10133)

---

youtube_dl/extractor/douyutv.py

use lapi for flv info, and html5 api for room info
#10153 #10318

[douyutv] Use new api

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/tvnoe.py

Add new extractor for TV Noe (Czech Christian TV).

---

youtube_dl/extractor/bilibili.py

Support episodes of bilibili.com.
e.g.
http://bangumi.bilibili.com/anime/v/40062

[bilibili] Support episodes

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/miaopai.py

---
---
This is an extractor for miaopai (miaopai.com), which is a Chinese video app lets users shoot, edit, and share 10 second videos.

[miaopai] Add new extractor

---

youtube_dl/extractor/abcnews.py
youtube_dl/extractor/dailymotion.py
youtube_dl/extractor/karaoketv.py

---
Now it can download videos from `AbcNewsVideoIE`.

Add support for https for rest of the exctractors.

---

youtube_dl/extractor/abcnews.py
youtube_dl/extractor/ard.py
youtube_dl/extractor/globo.py
youtube_dl/extractor/onet.py
youtube_dl/extractor/rutube.py
youtube_dl/extractor/spiegel.py
youtube_dl/extractor/twitter.py
youtube_dl/extractor/youtube.py

Add missing r prefix for _VALID_URLs

---

youtube_dl/extractor/promptfile.py

[promptfile] fixed

---

youtube_dl/extractor/clubic.py

[clubic] Rely on _match_id and _parse_json

---

youtube_dl/extractor/criterion.py

[criterion] Rely on _match_id, improve regex and add thumbnail to test

---

youtube_dl/extractor/pornoxo.py

[pornoxo] Improve metadata extraction

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/huajiao.py

---
---
This is the extractor for http://www.huajiao.com/ (Huajiao 花椒直播), a live video streaming site.

[huajiao] Add new extractor

---

README.md

---
This should hopefully aid readability a little bit.

Various grammar corrections.

---

youtube_dl/extractor/beatport.py
youtube_dl/extractor/extractors.py

---
---
Beatport have changed their name from Beatport Pro. This PR renames the extractor, fixes `_VALID_URL` and update test URLs.

[Beatport] Update extractor name and tests

---

README.md

Tiny doc change here!
---
Folks at Ubuntu aren't all male so calling them 'guys' is a little odd. This updates the README to change the word 'guys' to 'people'.

Changing 'guys' to 'people'

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/pandatv.py

---
---
panda.tv is a live streaming video platform in China mainly for gamers.

[pandatv] Add new extractor

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/jamendo.py

---
Adding an extractor for [Jamendo](https://www.jamendo.com/)
Fix #10132

[jamendo] Add new extractor

---

youtube_dl/extractor/ard.py

---
---
Corrects a translation mistake.

[ard] Fix time reference

---

test/test_jsinterp.py
youtube_dl/extractor/openload.py
youtube_dl/jsinterp.py

The aadecode part is not mine, but I just restore the version which was removed here c1decda58c812b3d0a3d4dfa998e7d8bd8f99203

[openload] Fix extraction.

---

README.md

---
---
The link text was moved from README.md to CONTRIBUTING.md, but the
target wasn't updated.

[CONTRIBUTING.md] Fix broken link

---

README.md

Typo in line 935: it's --> its
---
The readme.md file contained a typo in line 935. The line had _**it's**_, but the correct word is **_its_**. This is my first ever pull request on github. If I've made an error somewhere in this pull, please let me know. :)
Is it to be expected that any changes to the Readme.md file will have an "errored check":
> ERROR: The Travis CI build could not complete due to error.

Update README.md (fixed a small typo :)

---

youtube_dl/extractor/youtube.py

Seen on video with id 1t24XAntNCY
---

[youtube] Add missing format.

---

youtube_dl/extractor/chirbit.py

---
Get the username of the uploader of chirbit files.
The difference between `uploader`, `creator` and `uploader_id` is unclear to me so maybe it should be one of the others.

[chirbit] Learn to find 'uploader' metadata.

---

youtube_dl/extractor/azmedien.py

---
I adopted the _VALID_URL regular expression in AZMedienShowIE in a similar way like it is done in AZMedienIE. This leads to better readability of the code.
@dstftw: I included this "(?x)" in the first line of the regex like you have done yesterday, but I don't know what it does... Can you explain this to me?

[azmedien] Adopted URL regex AZMedienShowIE

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/vlive.py

---
---
Add support for extracting channels like http://channels.vlive.tv/FD53B

[vlive] Add support for channels

---

youtube_dl/extractor/prosiebensat1.py

---
---
Added new Regex for prosiebensat1 Extractor Description. Fixes #11810

Added new Regex for prosiebensat1 Extractor Description. Fixes #11810

---

youtube_dl/YoutubeDL.py
youtube_dl/__init__.py
youtube_dl/options.py

New parameter --playlist-random to randomize playlist download order. Fixes #11889

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/gaskrank.py

Added extractor for gaskrank.tv, a german-language motorcycle fun video site.

[gaskrank] Add new extractor

---

test/test_utils.py
youtube_dl/utils.py

---
---
As proposed by @yan12125 
> This is my idea:
get_element_by_id is not touched (by HTML standards IDs are unique)
get_element_by_attribute => get_elements_by_attribute
get_element_by_class => get_elements_by_class
The two functions get_element_by_attribute and get_element_by_class are now returning …

Changing get_element_by_attribute() and get_element_by_class() to return a list of results. See PR #11956

---

youtube_dl/extractor/aenetworks.py

Added lifetimemovieclub in AENetwork’s support list.

Added lifetime movie club

---

.travis.yml
devscripts/run_tests.sh

---
This PR separates travis builds into:
- fast core build containing only core functionality
- slow downloads build containing everything that needs network I/O (extractors, subtitles, etc.)
The next step is to parallelize downloads build (#7267).

[travis] Separate builds for core and download

---

youtube_dl/extractor/thescene.py

[TheScene] Fixed Extraction

---

youtube_dl/extractor/cda.py

---
Fix information extractor cda (#12255).

[cda] Decode url (fixes #12255)

---

youtube_dl/extractor/vier.py

---
vier.be and vijf.be run the same CMS and are property of the same company (SBS Belgium),
so the same extractor can be used for both of them.
Is this way of adding support for another (but closely related) site to an existing extractor acceptable, or is it preferred to create a separate extractor for this site? In that case it would be a lot of unnecessary code duplication.

[vier] Add support for vijf.be

---

youtube_dl/extractor/openload.py

---
---
Fixes openload extraction

Openload fix extraction

---

youtube_dl/extractor/prosiebensat1.py

[prosiebensat1] Fixed Title Extraction. Issue #12318

---

youtube_dl/extractor/crunchyroll.py

---
In addition to extracting the `series`, we should also extract the `season` name as well. See the test I added for an example.

[crunchyroll] Extract season name as well as the series

---

youtube_dl/extractor/openload.py

Just notice openload extractor ain't working they did this minor change in the code. here's a fix for openload
---
---

[Openload] Fixed Extraction

---

youtube_dl/extractor/openload.py

They did it again, just a minor change though since the last one
---
---

[Openload] Fixed Extraction Again

---

youtube_dl/extractor/openload.py

They did it again. just a minor change though. here's quick fix
---
---

[Openload.co] Fixed Extraction

---

youtube_dl/extractor/senateisvp.py

[SenateISVP] iframes can be https

---

youtube_dl/extractor/generic.py

Sorry, I should have included a test in #12512, and you were too fast for me.
Also, there was no preexisting iframe embed test at all, not to mention no https test.

[generic] Test for Senate ISVP iframe

---

youtube_dl/extractor/fox.py

---
---
Adding series, season number, episode number and episode. Fixes #12219.

[Fox] Add metadata extraction

---

youtube_dl/extractor/allocine.py

---
---
There was a bug in the allocine extractor that made the tests fail and this small modification make them pass. The json returned by the website simply had a couple more fields to it.
To test just this extractor:
`python test/test_download.py TestDownload.test_Allocine TestDownload.test_Allocine_1 TestDownload.test_Allocine_2 TestDownload.test_Allocine_3`

[allocine] Fix extraction

---

youtube_dl/extractor/adobepass.py

---
---
I was unable to use this project with my Verizon credentials. I noticed open [issue #10803](https://github.com/rg3/youtube-dl/issues/10803) to add Verizon as a supported MSO. I have tested Auto-Login and Manual Login.

[adobepass] Add Verizon support (#10803)

---

youtube_dl/extractor/youku.py

youku change the json metadata from http://play.youku.com/.... so we need to change the code to get fileid
---
---

youku change the JSON metadata

---

youtube_dl/extractor/go90.py

---
---
- add metadata for 'series', 'episode', 'season_number', and 'episode_number'
- integrate series title into the title (based off code from commit b68e00b08ae60e60d9f5c2654884f3c58595075f [rtl2])
- extract subtitles (based off code from commit b0f7f21cb92ca3af1795f68737ffa25196968dc6 [channel9])

[go90] Improve extraction

---

youtube_dl/downloader/common.py
youtube_dl/downloader/dash.py
youtube_dl/downloader/f4m.py
youtube_dl/downloader/fragment.py
youtube_dl/downloader/hls.py
youtube_dl/downloader/http.py
youtube_dl/downloader/ism.py

- resume immediately
- no need to concatenate segments and decrypt them on every resume
- no need to save temp files for segments
and for hls downloader:
- no need to download keys for segments that already downloaded

[fragment,hls,f4m,dash,ism] improve fragment downloading

---

youtube_dl/extractor/streamable.py

---
###Before submitting a *pull request* make sure you have:
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x ] Bug fix
---
New streamable embedded url format is now supported.

Add new streamable embedded url format

---

test/test_download.py

---
---
Output before fix:
```
AssertionError: '0869000b4ce265e8ca62738b336b268a' != 'bad_md5'
- 0869000b4ce265e8ca62738b336b268a
+ bad_md5
```
and after:
```
AssertionError: 'bad_md5' != '0869000b4ce265e8ca62738b336b268a'
- bad_md5
+ 0869000b4ce265e8ca62738b336b268a
```

[test_download] Fix order when testing file's md5

---

youtube_dl/extractor/clipfish.py

[clipfish] update test cases

---

youtube_dl/extractor/br.py

[br] update test cases

---

youtube_dl/extractor/canalc2.py

[canalc2] update test cases

---

youtube_dl/extractor/bandcamp.py

[bandcamp] update test cases

---

youtube_dl/extractor/beeg.py

[beeg] update test cases

---

youtube_dl/extractor/bleacherreport.py

[bleacherreport] update test cases

---

youtube_dl/extractor/atresplayer.py

[atresplayer] update test cases

---

youtube_dl/extractor/audioboom.py

[audioboom] update test cases

---

youtube_dl/extractor/appleconnect.py

[appleconnect] update test cases

---

youtube_dl/extractor/archiveorg.py

[archiveorg] update test cases

---

youtube_dl/extractor/afreecatv.py

[afreecatv] fix extractor

---

youtube_dl/extractor/cbslocal.py

[cbslocal] update test cases

---

youtube_dl/extractor/appletrailers.py

[appletrailers] update test cases

---

youtube_dl/extractor/cbc.py

[cbc] update test cases

---

youtube_dl/extractor/vevo.py

---
---
Created this before I saw #12847 
In comparison, this change uses the same (old) APIs to download, so the change only affects how the token is generated.
_client_id_ value is from https://www.vevo.com/nucleus/browser.7a7cc4c0ad3d8034ba16.js and could change at any time.
Fixes #12678 .

[vevo] Fix extraction (using config.token.key)

---

youtube_dl/extractor/coub.py

---
Coub no longer have comments, removed them from extractor and updated test.

[coub] update test, remove unnecessary code

---

youtube_dl/extractor/crunchyroll.py

[crunchyroll] Update test

---

youtube_dl/extractor/dailymotion.py

---
Added new test because the only one left was gone.

[dailymotion] Update test

---

youtube_dl/extractor/democracynow.py

[democracynow] Update test

---

youtube_dl/extractor/dotsub.py

[dotsub] Update test

---

youtube_dl/extractor/common.py
youtube_dl/extractor/pbs.py
youtube_dl/postprocessor/ffmpeg.py

---
continuation of #9409, it should work now in both unix and windows systems.

introduce chapters field(2)

---

youtube_dl/extractor/bandcamp.py

[bandcamp] fix thumbnail extraction

---

youtube_dl/extractor/crackle.py

[crackle] update test case

---

youtube_dl/extractor/vier.py

Full episodes now require authentication.
---
---
Since today or yesterday, vier.be requires users to log in before they can watch complete episodes. Short clips can still be watched without authentication.
This PR adds support for authentication.

[vier] Support authentication

---

youtube_dl/extractor/mitele.py

---
---
Updates the regex as the appkey is now stored as a constant.

[MiTele] Update regex due to site redesign

---

youtube_dl/extractor/toypics.py

---
---
Toypics support was no longer working, this commit makes the unit tests pass again

[toypics] fix extractor

---

youtube_dl/extractor/streamcz.py

---
This adds subtitle support for Stream.cz. Also tests are fixed (they probably somehow changed the video files).

[Stream.cz] add subtitle support

---

youtube_dl/extractor/cbs.py
youtube_dl/extractor/cbsinteractive.py

[cbsinteractive] update extractor and test cases

---

youtube_dl/extractor/disney.py

[disney] add disneychannel.de

---

youtube_dl/extractor/xfileshare.py

Added support for fastvideo.me

[xfileshare] Add support for fastvideo.me

---

youtube_dl/extractor/polskieradio.py

The page structure has slightly changed recently.
This fixes the tests which have until now been failing.

[polskieradio] Fix the extractor.

---

youtube_dl/extractor/abcotvs.py

[abcotvs] fix test md5

---

youtube_dl/extractor/drtuber.py

---
- [x ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x ] Bug fix
---
Updated the [DrTuber.com] extractor to fetch the …

[DrTuber] Fetch video URL from JSON stream (fixes issue #12058)

---

youtube_dl/extractor/ign.py

Update ign.py fix issue #13328

---

youtube_dl/extractor/niconico.py

---
Some links start with "sp":
http://sp.nicovideo.jp/watch/sm28964488?ss_pos=1&cp_in=wt_tg

[niconico] fix sp subdomain links

---

youtube_dl/extractor/pandatv.py

---
---
Add https support for PandaTV InfoExtractor also with tests update.

PandaTV https support.

---

youtube_dl/extractor/soundcloud.py

use HTTPS for SoundCloud endpoints

---

youtube_dl/extractor/fivetv.py

---
---
The site uses flowplayer for most videos now. There was also a bad test which always failed if a new episode got released.
Fixes #13354

[FiveTV] Add new regex and fix bad test

---

youtube_dl/extractor/slideshare.py

---
---
Fixed slideshare extraction since markup was changed.

[slideshare] fix extraction

---

youtube_dl/downloader/ism.py
youtube_dl/extractor/audioboom.py
youtube_dl/extractor/generic.py
youtube_dl/extractor/karrierevideos.py

---
---
Hi, I'm one of the developers on www.lgtm.com, and as I'm a fan of this project I was looking at the alerts for [youtube-dl](https://lgtm.com/projects/g/rg3/youtube-dl/alerts/) on the site. I've fixed some of the simple local problems here. I hope they're useful! if you think that these kinds of alerts would be handy to have on pull requests to stop more possible bugs going in, you can enable PR integration as well at https://lgtm.com/projects/g/rg3/youtube-dl/ci/.

Lgtm fixes

---

youtube_dl/extractor/npo.py

---
Some NPO videos are also available at npo3.nl, I've added support for that URL and wrote a test for it. The videos at npo3.nl can be downloaded exactly the same way as on npo.nl, so I only had to add a regex. npo3.nl is an official site of NPO.

[npo] added npo3 support

---

.github/ISSUE_TEMPLATE_tmpl.md

---
---
* Updated the issue template to collapse logs with HTML5 `<details>` and `<summary>`. This may make it easier to scroll through issues with long logs.
* Moved the command line input part from the logs to above, since it doesn't need to be included as it will be output with `-v` anyway, and it may contain sensitive information that is automatically redacted in the logs (hopefully people are smart enough to redact any sensitive information, but who knows).
* Made other minor grammar/formatting corrections.

Minor improvements to issue template

---

youtube_dl/extractor/generic.py

---
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ x] Bug fix
- [ x] Improvement
---
Explanation of your *pull …

[generic] Add regexp for ooyala embedded player (#13727)

---

youtube_dl/extractor/mlb.py

---
---
Adjust `_VALID_URL` in mlb.py to fix #13740

Fix for #13740

---

youtube_dl/extractor/generic.py
youtube_dl/extractor/vzaar.py

---
---
It now supports vzaar embedded urls. Check `python test/test_download.py TestDownload.test_Generic_126` for the test case.

[vzaar] update to generic extractor for embedded urls

---

youtube_dl/extractor/qqmusic.py

---
---
Fix the url of `QQ Music`. like #13363

Fix QQ Music url changed

---

youtube_dl/extractor/bandcamp.py

---
---
Extract titles of playlist entries. Fixes #13927.

[bandcamp] extract titles in playlists

---

README.md

And minor url cleanups
---
---
Explicit HTTPS calls make the world a safer place, and urls should not have leading slashes for style reasons and that they are unnecessarily lengthen the url.

[README.md] Made explicit HTTPS calls

---

youtube_dl/extractor/mixcloud.py

Just a minor change but keeping all the cases incase they changed it back.
---
---

[Fixed] Mixcloud.com

---

youtube_dl/extractor/mixcloud.py

They keep doing this minor changes so i quess this one fits the best for now
---
---

[Update] Mixcloud.com

---

youtube_dl/extractor/morningstar.py

---
---
Extended _VALID_URL regex so it recognizes the 'news' subdomain too. [Example video](http://news.morningstar.com/cover/videocenter.aspx?id=825556)

[morningstar] improved url

---

youtube_dl/extractor/viki.py

Just a minor fix, tested this
---
---

Viki [Updated App Secret & AppId]

---

youtube_dl/extractor/twitter.py

---
---
The duration of Twitter Videos was not in seconds, for example this Video:
https://twitter.com/SophiePassmann/status/903676793860829184
Old
```
python -m youtube_dl --get-duration https://twitter.com/SophiePassmann/status/903676793860829184
29:50:00
```
After fix:
```
python -m youtube_dl --get-duration https://twitter.com/SophiePassmann/status/903676793860829184
1:47
```

[twitter] fixed duration

---

youtube_dl/extractor/nbc.py

---
---
Updated the extractor to use the correct video URL and replaced the broken tests - issue #13873.
Cheers and thank you!
Parmjit V.

[nbc:NBCSportsVPlayer] Corrected video URL (fixes issue #13873)

---

youtube_dl/extractor/beeg.py

[beeg] Fix extraction

---

youtube_dl/extractor/twitter.py

[twitter] Fix extraction

---

youtube_dl/extractor/gfycat.py

---
Add support to new path like https://gfycat.com/gifs/detail/UnconsciousLankyIvorygull 
See issue #14322

[gfycat] add support for /gifs/detail path

---

youtube_dl/extractor/rtve.py

[rtve] Fix extraction (closes 14290)

---

youtube_dl/extractor/tvp.py

[tvp] Fix extraction for vod.tvp.pl (closes #14368)

---

youtube_dl/extractor/lnkgo.py

---
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x ] Improvement
---
Explanation of your *pull request* in arbitrary …

Handling lnkgo url without .alfa part

---

youtube_dl/extractor/vvvvid.py

---
Fixes a typo, "epidode" -> "episode". Reported by danieleg on Freenode

fix typo in vvvvid extractor

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/slideslive.py

---
Thanks to @pabs3 for a hint on how to implement this.

[slideslive] Add extractor (closes #2680)

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/youtube.py

Remove YoutubeSharedVideoIE  

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/unity.py

---
---
Added a new extractor for the Unity platform [https://unity3d.com/] - issue #14528.
This site provides a number of free video tutorials for Unity, a popular content creator for 3D games and apps.
Cheers and thank you!
Parmjit V.

[Unity] Add new extractor (fixes issue #14528)

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/servus.py

---
---
I have added an information extractor for [Servus](https://www.servus.com). This was requested in #14362.

[Servus] Add new extractor

---

ChangeLog

Fix a typo in ChangeLog

---

youtube_dl/extractor/parliamentliveuk.py

---
---
Fixed the issue, that `ParliamentLiveUKIE` was not working anymore. Closes #14524.

[ParliamentLiveUK] Fixed extractor

---

youtube_dl/extractor/azmedien.py

---
---
Fixed a corrupt test in `azmedien.py`.

[azmedien] Fix test.

---

youtube_dl/extractor/nick.py

---
---
Fulfilled the request posted in #14553.

[nick] Add support for nickelodeon.(dk|no|se) (closes #14553)

---

youtube_dl/extractor/ndtv.py

---
---
Current extractor regex does not match sub-sites (gadgets.ndtv.com, khabar.ndtv.com etc.).  Added support and tests for them.

[NDTV] Added support for sub-sites (gadgets,khabar,profit)

---

youtube_dl/extractor/canvas.py
youtube_dl/extractor/extractors.py
youtube_dl/extractor/gigya.py
youtube_dl/extractor/medialaan.py

---
---
This PR address #11829 by adding a new extractor for VrtNU to `vrt.py`. The extractor is based on the existing extractor for canvas. As all videos require authentication the sole test is skipped. I have successfully used this extractor for a number of different videos (using `--cookies` for authentication).
I welcome all feedback.

Add extractor for VrtNU

---

youtube_dl/extractor/cartoonnetwork.py

Hopefully fixes #14666
---
---
Replacing tokenizer_src

[Cartoon Network] Update tokenizer_src

---

youtube_dl/extractor/ccma.py

---
---
The ccma extractor uses "thumnails" as the key when it means "thumbnails" in the json response on extracts.

thumbnails, not thumnails

---

youtube_dl/extractor/spankbang.py

---
---
Extended _VALID_URL so that it recognizes the mobile version of SpankBang. Also fixed a description in a test.

[spankbang] Recognize mobile site and fixed tests

---

youtube_dl/extractor/drtuber.py

---
---
Extended _VALID_URL so that it recognizes the mobile version of DrTuber.

[drtuber] Recognize mobile site URL

---

youtube_dl/extractor/youku.py

[youku] Fix list extraction.(close #15065)

---

youtube_dl/extractor/slutload.py

---
---
Support mobile site by effectively downloading from the desktop site.

[slutload] Support mobile site

---

youtube_dl/extractor/acast.py

[acast] Fix broken episode extractor

---

youtube_dl/extractor/youku.py

Change-Id: I2e9c920143f4f16012252625943a8f18b8ff40eb
---
---

[youku] Fix list extraction.(close #15135)

---

youtube_dl/extractor/bilibili.py

---
Fix #15171 by sending http referer

fix bilibili extraction (closes #15171)

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/ximalaya.py

---
---
Add a new extractor for podcast site http://www.ximalaya.com. Single audio and album of audios  can be handled.

[ximalaya_extractor] Add new extractor ximalaya 

---

youtube_dl/extractor/soundcloud.py

---
- [x ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [ x] I am the original author of this code and I am willing to release it under …

[soundcloud] Update clientId to prevent 401 errors

---

youtube_dl/extractor/soundcloud.py

---
---
`_IPHONE_CLIENT_ID` was not being used anywhere else

Removed IPHONE_CLIENT_ID

---

youtube_dl/extractor/gameinformer.py

---
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [ x] I am the original author of this code and I am willing to release it under …

[GameInformer] Fix brightcove_id regex.

---

youtube_dl/extractor/la7.py

Fix "Unable to extract player data" regex error

---

youtube_dl/extractor/veoh.py

---
This adds support for veoh embed links, for example: http://www.veoh.com/embed/v56314296nk7Zdmz3

[veoh] Support embed urls

---

youtube_dl/extractor/fusion.py

---
---
Fusion website have changed from fusion.com to fusion.tv, updated regex to use .tv

[fusion] updated regex to use .tv

---

youtube_dl/extractor/vimeo.py

---
Fixed test case for Vimeo. Updated expected md5 hash value

[Vimeo] fixed vimeo test case

---

youtube_dl/extractor/vk.py

---
Fixed vk extractor test case. fixed file format and hash

[VK] fixed vk extractor test case. fixed file format and hash

---

youtube_dl/extractor/ninegag.py

---
Fixes ninegag test case id

[NineGag] fixes NineGag test case id

---

youtube_dl/extractor/reddit.py

---
Fixes reddit test case md5

[Reddit] fixes reddit test case md5

---

youtube_dl/extractor/redtube.py

---
Fixes test case for redtube. Updated md5, upload date and duration.

[RedTube] fixed redtube test case md5,upload date and duration

---

youtube_dl/extractor/zdf.py

---
Other tests were no longer available (404) so I added a new/current one

[ZDF] added current test case

---

youtube_dl/extractor/ard.py

---
All other test cases were no longer availabe (404). I added a new one.

[ARDMediathek] Added a new test case that is still available

---

youtube_dl/extractor/ruutu.py

Use `continue` instead of `return` to loop through all possible sources.
Added test case for episode where `<SourceFile>` element has `[NOT-USED]` in URL, but other `<*Files>` elements have working URLs.
---
---

[ruutu] Don't stop processing URLs

---

youtube_dl/extractor/pornhub.py

---
einstein95's patch from https://github.com/rg3/youtube-dl/issues/15697#issuecomment-370133788
Closes #15697

fix Pornhub cookie issue

---

youtube_dl/extractor/youku.py

[Youku] Update ccode

---

youtube_dl/extractor/videa.py

It seems that `videakid.hu` is just an alternative domain for `videa.hu`
serving up the same videos, supporting the same download procedure.
---
---

Add videakid as an alias for videa

---

youtube_dl/extractor/abc.py

---
---
Currently, the `title` and `series` properties for the ABC iview extractor include HTML escaped characters due to them being sourced from the HTML. This pull request changes these properties to use `unescapeHTML`. I've also changed the test case to [a video which uses HTML encoded characters](https://iview.abc.net.au/programs/ben-and-hollys-little-kingdom/ZY9247A021S00) in both its `title` and `series` properties, and verified the test passed.

[abc:iview] Unescape HTML for 'title' and 'series' properties

---

youtube_dl/options.py

---
---
Document ability to have comment lines in --batch-file files.
See also #4307 and #8315.

Document comments in --batch-file

---

youtube_dl/extractor/odnoklassniki.py

---
Support for another format of m.ok.ru links as described in https://github.com/rg3/youtube-dl/issues/16081

[extractors/odnoklassniki] Add support for mobile URLs (closes #16081)

---

youtube_dl/extractor/fxnetworks.py

---
---
FXNetworks now uses https URLs for ThePlatform. This PR just update the regex to find those URLs and allows for http or https to match.

[fxnetworks] Allows for https URL (closes #16125)

---

youtube_dl/extractor/reddit.py

---
---
Add support for old.reddit.com URLs. As far as youtube-dl is concerned, they work the same way as www.reddit.com URLs.

Add support for old.reddit.com URLs.

---

youtube_dl/extractor/reddit.py

[reddit] ignore subdomains

---

youtube_dl/extractor/imgur.py

---
Fixes:
ExtractorError: No sources found for video A61SaA1. Maybe an image?

[imgur] Fix extraction

---

youtube_dl/extractor/openload.py

Example link: https://oload.win/f/kUEfGclsU9o
---
- [] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
---

[openload] Add support for oload.win and oload.download

---

youtube_dl/extractor/vidzi.py

[vidzi.tv] Fix #16678

---

youtube_dl/extractor/vlive.py

---
---
Before this commit the extractor failed with a 500 internal server error when attempting to extract a **live** video URL. VOD videos work both with and without this PR.
Current master:
```
bash-4.3# python3 -m youtube_dl -v -g https://www.vlive.tv/video/78088                                  
[debug] Command-line args: ['-v', '-g', 'https://www.vlive.tv/video/78088']
[debug] youtube-dl version …
```

[vlive] Update extractor to use https

---

README.md

---
---
OS X was renamed macOS on September 20, 2016. This PR updates the readme to use the newer name to avoid confusing developers who don't have this historical knowledge.

Rename OS X to macOS in README

---

youtube_dl/extractor/iwara.py

---
---
Since the API of "Iwara.tv" has been updated, we need to update the Extractor.

[Iwara] Update extractor

---

youtube_dl/extractor/ceskatelevize.py

(and probably: --no-check-certificate)
---
---

Fixes #16997 now require https

---

youtube_dl/extractor/theplatform.py

---
---
Fix ThePlatformFeed's _VALID_URL regex ( fix #16181 issue )

[theplatform] Fix valid_url regex

---

youtube_dl/extractor/sixplay.py

---
---
Add support for play.rtl.hr in 6play [sixplay.py] extractor. Just add support in _VALID_URL and service, consumer_name .
Best regards.
H.

[6play] Add support for play.rtl.hr

---

youtube_dl/extractor/bitchute.py

---
---
BitChute will not show the `addWebSeed()` lines without a modern user agent string given.

[bitchute] Needs user agent to get formats

---

youtube_dl/extractor/openload.py

[openload] add support for oload.cloud

---

youtube_dl/extractor/openload.py

Add support for oload.cc, other of many domains of openload

Add support for oload.cc

---

youtube_dl/extractor/openload.py

Other of the many domains of openload.co...

[Openload] Add new support to new domain oload.icu

---

youtube_dl/extractor/openload.py

Other of the many domains of openload.

[Openload] Add support to oload.fun

---

youtube_dl/extractor/joj.py

---
---
Thsi PR fixes the issue described in #18280.

[joj] Fix extraction (closes #18280)

---

youtube_dl/extractor/azmedien.py

---
`AZMedien` is currently broken, because the API path is not present anymore in the downloaded web page. This PR manually sets the API path from the given URL to fix that issue.

[azmedien] Fix information extractor (closes #18334)

---

youtube_dl/extractor/gfycat.py

---
---
Based on the suggestions on the issue page, I changed the URL for the JSON api, and now, the Gfycat tests are passing:
```
youtube-dl$ python test/test_download.py TestDownload.test_Gfycat
[Gfycat] DeadlyDecisiveGermanpinscher: Downloading video info
[info] Writing video description metadata as …
```

[Gfycat] update json api endpoint

---

youtube_dl/extractor/lynda.py

---
---
Fixes lynda.com signin. The signin page previously used by the extractor has been moved to https://www.lynda.com/signin/lynda because Lynda supports a few ways to signin and has made it clear via the previous signin page update by prompting users to first choose one of the below signin methods:
https://www.lynda.com/portal/linkedin
https://www.lynda.com/signin/lynda
https://www.lynda.com/signin/organization
closes #18158

fix lynda.com signin

---

youtube_dl/extractor/yourporn.py

---
---
Fixes the issue of #18424

Fix video_url in yourporn (closes #18424)

---

youtube_dl/extractor/iprima.py

Fix URL regex (Support more subdomains) in iprima.

[Iprima] Fix URL regex (#18515)

---

youtube_dl/extractor/acast.py

---
---
Should fix (#18587). The old style URLs without `play` in them should work as well as the new style URLs.

[acast] Update channel extractor to support play.* urls

---

youtube_dl/extractor/dtube.py

thx to @GianlucaFicarelli
---
closes #18741 

fix download issue

---

README.md

---
---
Simple grammatical fix in the readme file, none of the source code has been changed.

Fixed typo in the readme file

---

youtube_dl/extractor/odnoklassniki.py

---
- [x ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [ x ] I am not the original author of this code but it is in public domain or released under …

[OK.RU] Raise error in case of paid videos.

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/zattoo.py

---
There is a new Zattoo reseller available: tv.salt.ch
This PR adds support for it to youtube-dl.

[zattoo] Add new Zattoo reseller: Salt

---

youtube_dl/extractor/openload.py

---
Added support for [oload.info](https://oload.info)

Support openload.info

---

youtube_dl/extractor/drtuber.py

---
---
pull duration from video info json

[drtuber] Added duration to info dict

---

youtube_dl/extractor/pornhd.py

[pornhd] added like count to info dict

---

youtube_dl/extractor/imgur.py

[imgur] Don't fail on missing OpenGraph title

---

youtube_dl/extractor/openload.py

[Openload] Add support to new domain, oload.live

---

youtube_dl/extractor/youtube.py

---
See [Invidious-Instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances) for the reference.

Add more Invidious instances

---

youtube_dl/extractor/openload.py

Other of the many domains of Openload...

[Openload] New domain, oload.space

---

youtube_dl/extractor/urplay.py

---
---
Extracts timestamp from `uploadDate` meta tag.

[urplay] Extract timestamp

---

youtube_dl/extractor/youtube.py

---
---
See [Invidious-Instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances) and for the reference.

[youtube] Add invidiou.sh instance

---

youtube_dl/extractor/cbc.py

---
---
Per Issue #20251 CBC altered their web player to use a different domain. The new domain behaves like the old domain with respect to youtube-dl so only the regex needs to be updated (and a test case added).

[cbc] Support new domain name (closes #20251)

---

youtube_dl/extractor/corus.py

---
---
Adds the domain https://www.bigbrothercanada.ca/ to the corus extractor. Tested working.
~~Notes: Original form of url is probably something like this: https://www.bigbrothercanada.ca/video/big-brother-canada-704/1457812035894/. In order for youtube-dl to pick up the proper video, the middle part (big-brother-canada-704) needs to be removed to form https://www.bigbrothercanada.ca/video/1457812035894/~~ **Support for the whole URL was added as requested**

[corus] Add support for bigbrothercanada.ca

---

youtube_dl/__init__.py

---
---
Throw error when user uses --max-sleep-interval, but doesn't set --sleep-interval.

Fix --max-sleep-interval bug

---

youtube_dl/extractor/weibo.py

It’s a tiny fix so I thought I’d just make a PR instead of going through filing an issue and all that.

Added optional www prefix to pattern in weibo extractor

---

youtube_dl/extractor/yourporn.py

---
yourporn.sexy has a new domain sxyprn.com

[yourporn] Added support for new domain

---

youtube_dl/extractor/streamango.py

---
---
Add support for the streamcherry.com domain (another frontend for streamango.com)

[streamango] add support for streamcherry.com

---

youtube_dl/extractor/openload.py

[openload] add support for oladblock.services and oladblock.xyz domains

---

youtube_dl/extractor/twitcasting.py

---
---
Fix extractor test of TwitCasting.
The title format of TwitCasting is modified, so test failed.

[twitcasting] Fix test: video title

---

youtube_dl/extractor/youtube.py

---
---
Fixed to get channel_id from video_details.
This fixes #20982

fix warning (channel id)

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/generic.py
youtube_dl/extractor/openload.py

---
---
This pull request adds support for verystream.com into the Openload extractor, closing #20701 (and making #20738 obsolete).

[openload] add support for verystream.com

---

youtube_dl/extractor/gfycat.py

---
---
Support gfycat links with tags in the URL.

[gfycat] Support URLs with tags (closes #20696)

---

youtube_dl/extractor/cloudflarestream.py

Another resubmission of https://github.com/ytdl-org/youtube-dl/pull/21045, without code duplication.

Cloudflare can use videodelivery.net subdomains

---

youtube_dl/extractor/openload.py

- `https://oload.press/embed/drTBl1aOTvk`
Support request of `oload.press` (mirror of `openload.co`)

[openload] Add support for oload.press

---

youtube_dl/extractor/liveleak.py

---
---
A small addition for fixing #21206: Check ~~for HTTPErrors~~ `_is_valid_url` before accepting the stripped urls.

[LiveLeak] Check if the original videos exist (closes #21206)

---

youtube_dl/extractor/openload.py

[openload] add support for oload.website

---

youtube_dl/extractor/openload.py

- `https://oload.life/embed/oOzZjNPw9Dc`
Support request of `oload.life` (mirror of `openload.co`)

[openload] Add support for oload.life (#21495)

---

youtube_dl/extractor/xiami.py

---
---
Xiami API URL has been changed.
- not working: `curl 'http://www.xiami.com/song/playlist/cat/json/id/1773334416' -H 'Referer: https://emumo.xiami.com/'`
- working: `curl 'https://emumo.xiami.com/song/playlist/cat/json/id/1773334416' -H 'Referer: https://emumo.xiami.com/'`

[xiami] Update API base URL

---

youtube_dl/extractor/openload.py

- `https://oload.biz/f/bEk3Gp8ARr4/`
Support request of `oload.biz` (mirror of `openload.co`)

[openload] Add support for oload.biz

---

youtube_dl/extractor/beampro.py

Fix VOD parsing for mixer.com

---

youtube_dl/extractor/youtube.py

See [Invidious-Instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances) for the reference.

[youtube] Add more Invidious instances

---

youtube_dl/extractor/youtube.py

[youtube] Add support for invidious.mastodon.host

---

youtube_dl/downloader/dash.py
youtube_dl/downloader/ism.py
youtube_dl/extractor/leeco.py
youtube_dl/extractor/picarto.py
youtube_dl/extractor/rtlnl.py
youtube_dl/extractor/soundcloud.py

---
:blue_heart: Fix typos across **youtube-dl** repository
<details><summary>See all fixed files</summary>
<p>
```
youtube-dl/youtube_dl/downloader/dash.py:56:84: "attemps" is a misspelling of "attempts"
youtube-dl/youtube_dl/downloader/ism.py:149:101: "represenation" is a misspelling of "representation"
youtube-dl/youtube_dl/extractor/leeco.py:329:61: "unknwon" is a misspelling of "unknown"
youtube-dl/youtube_dl/extractor/picarto.py:58:8: "prefered" is a misspelling of "preferred"
youtube-dl/youtube_dl/extractor/picarto.py:70:30: "prefered" is a misspelling of "preferred"
youtube-dl/youtube_dl/extractor/rtlnl.py:35:22: "avaialble" is a misspelling of "available"
youtube-dl/youtube_dl/extractor/soundcloud.py:61:45: "untill" is a misspelling of "until" …
```

Fix typos across youtube-dl repository

---

youtube_dl/extractor/openload.py

- `https://oload.best/embed/kkz9JgVZeWc/`
Support request of `oload.best` (mirror of `openload.co`)

[openload] Add support for oload.best (#21913)

---

youtube_dl/extractor/mgtv.py

---
---
`format_note` should now show 标清, 高清, 超清, 蓝光, etc.
```
youtube-dl -F --cookies cookies.txt https://www.mgtv.com/b/328982/5397284.html
[MGTV] 5397284: Downloading JSON metadata
[MGTV] 5397284: Downloading JSON metadata
[MGTV] 5397284: Download video info for format #0
[MGTV] 5397284: Download video info for format #1
[MGTV] 5397284: Download video info for format #2
[MGTV] 5397284: Download video info for format #3
[info] Available formats for 5397284:
format code  extension  resolution note
531          mp4        unknown    标清  531k
877 …
```

[mgtv] Add format_note.

---

youtube_dl/__init__.py

Adding the name of the file which couldn't be read & a brief description of the option.
Just "ERROR: batch file could not be read" can be confusing for users who are inexperienced (and likely using Windows).
eg. https://www.reddit.com/r/Piracy/comments/cfl0ap/youtubedl_error_batch_file_could_not_be_read_how/
(The user specified option -audio-file, instead of --audio-file)
---
---
Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well …

Clarify batch file ERROR: message

---

youtube_dl/extractor/einthusan.py

---
---
Einthusan website changes it's host address. For example einthusan**.tv**, einthusan**.com**, einthusan**.ca**
The current version of extractor supports .tv and .com. I have added .ca support in regex.  
Please merge the code.

Add support for ca

---

youtube_dl/extractor/safari.py

Fix issue #22161
---
---
Fix issue #22161 because missing cookies.

 [safari] Fix authentication

---

youtube_dl/extractor/youtube.py

---
Added new instances: yt.elukerio.org and invidious.nixnet.xyz 
Removed invidious.mastodon.host, since admin of this instance removed it from from the list.

Update Invidious instances

---

youtube_dl/extractor/youtube.py

---
---
Adding onion links since facebook has one too.

[youtube] Add invidious tor instances

---

youtube_dl/extractor/youtube.py

[youtube] Add invidious.drycat.fr

---

youtube_dl/extractor/openload.py

- `https://oload.online/f/W8o2UfN1vNY/`
Support request of `oload.online` (mirror of `openload.co`)

[openload] Add support for oload.online (#22304)

---

youtube_dl/extractor/youtube.py

---
---
Since .onions URLs are supported, it's makes sense to support .i2p too.

[youtube] Adding invidious eepsite instance

---

youtube_dl/extractor/youtube.py

[youtube] Add yt.lelux.fi

---

youtube_dl/extractor/nrk.py

---
---
NRK has made a minor change to their site and downloading series no longer works. This change fixes it and `TestDownload.test_NRKTVSeason` now passes.

[nrktv:series] Fix extraction

---

youtube_dl/extractor/openload.py

[openload] Add support for oload.monster

---

youtube_dl/extractor/youtube.py

---
---
It's redirects to invidious.snopyta.org now.

[youtube] Remove invidious.enkirton.net

---

youtube_dl/extractor/telequebec.py

The zonevideo.telequebec.tv code works on coucou.telequebec.tv, so just
ensure those coucou URLs are recognized.
---
---

[telequebec] Support coucou subdomain URLs

---

youtube_dl/extractor/chaturbate.py

---
---
There are alternative Chaturbate URLs such as https://chaturbate.com/fullvideo/?b=caylin, which were previously not supported; this PR adds support for /fullvideo/ URLs.

[chaturbate] Allow alternative URLs at /fullvideo/

---

README.md

If only executing rights are added, one still gets "permission denied" when trying to execute the binary.
---
---
If only executing rights are added, one still gets "permission denied" when trying to execute the binary.

Also add "read" permission to the installed binary

---

youtube_dl/extractor/nrk.py

Added new error message
Fixed tests, some of the existing ones were removed from the site
---
---
Fixes a bug i noticed when trying to fetch a full series, rather than each individual episode.
NRK introduced malformed json to their site, creating values like `"subtitle":undefined`, using `.replace("undefined", "'undefined'")` as i fail to see a function in utils.py to solve this.
I also updated the tests to not use content which has expired, and which should not expire, at least for a while. Also added the error message expired items gives.

[nrk:series] fix and update extractor

---

.travis.yml

- Put an `x` into all the boxes [x] relevant to your *pull request* (like that [x])
---
---
enforce `flake8` test in travis

[travis] add flake8 to travis

---

youtube_dl/extractor/businessinsider.py

---
---
This PR updates the regex used in the `businessinsider` extractor. Fixes #22929.

[businessinsider] update regex (fixes #22929)

---

youtube_dl/extractor/abc.py

---
---
Add support for 720p streams on iview

[abc:iview] Support 720p (fixes #22907)

---

youtube_dl/extractor/tv2dk.py

---
---
Use https instead of http for tv2 dk extractor

[tv2dk] Need to use https

---

youtube_dl/extractor/youtube.py

---
---
fix #23872 by
- remove non-existing 'ytdl test PL' https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re
- change 'YDL_Empty_List' https://www.youtube.com/playlist?list=PLtPgu7CB4gbZDA7i_euNxn75ISqxwZPYx to existing playlist
- fix incorrect playlist_count for https://www.youtube.com/playlist?list=PLwP_SiAcdui0KVebT0mU9Apz359a4ubsC

Fix playlist tests (fix #23872)

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/orf.py

---
---
This adds support for the various ORF radio stations. Tested with the following links:
- https://noe.orf.at/player/20200423/NGM/1587610800000
- https://wien.orf.at/player/20200423/WGUM/1587610793000
- https://burgenland.orf.at/player/20200423/BGM/1587611000000
- https://ooe.orf.at/player/20200423/OGMO
- https://steiermark.orf.at/player/20200423/STGMS
- https://kaernten.orf.at/player/20200423/KGUMO
- https://salzburg.orf.at/player/20200423/SGUM
- https://tirol.orf.at/player/20200423/TGUMO
- https://vorarlberg.orf.at/player/20200423/VGUM …

Add ORF Radio Stations

---

youtube_dl/extractor/mailru.py

[mailru] Fix extraction (closes #24530)

---

youtube_dl/extractor/youtube.py

[youtube] Add support for yewtu.be (Invidious)

---

youtube_dl/extractor/indavideo.py

[indavideo] enable TLS/SSL for metadata

---

youtube_dl/extractor/youtube.py

---
---
The vast majority of invidious instance supported by youtube-dl where IP banned or closed so I updated the instance regex with the newest info on [invidious wiki instance list](https://github.com/omarroth/invidious/wiki/Invidious-Instances)

[invidious] add new instances

---

youtube_dl/extractor/malltv.py

www.mall.tv and sk.mall.tv may share same video, but few of them are
accessible only on sk subdomain.
Signed-off-by: Matej Dujava <mdujava@kocurkovo.cz>
---

malltv: some new videos are hosted on sk.mall.tv domain

---

youtube_dl/extractor/iprima.py

[iprima.cz] fix extractor

---

youtube_dl/extractor/iqiyi.py

---
---
Correct a simple typo.

[iqiyi] Correct a typo in iqiyi.py

---

youtube_dl/extractor/afreecatv.py

---
---
Remove a repeated word.

[afreecatv] Remove a repeated word in afreecatv.py

---

youtube_dl/extractor/francetv.py

---
---
Fallback on another API endpoint when no video formats are found.
Closes ytdl-org#22561
```
$ youtube-dl -v 'https://www.france.tv/france-3/lego-ninjago/ninjago-saison-11/1894793-premiere-attaque.html'
[debug] Command-line args: ['-v', 'https://www.france.tv/france-3/lego-ninjago/ninjago-saison-11/1894793-premiere-attaque.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.06
[debug] Python version 3.8.5 …
```

[francetv] Add fallback video url extraction

---

youtube_dl/extractor/amara.py
youtube_dl/extractor/extractors.py

---
---
This PR adds support for videos on the amara.org website. Amara allows users to add subtitles to Youtube and Vimeo videos, even though they might not be the uploader of that video on Youtube or Vimeo. Amara is often used in educational settings where teachers need to make an existing video accessible for hearing-impaired students.

[Amara] Add new extractor

---

youtube_dl/extractor/viki.py

---
---
This fixes a bug in parsing the streams json, where instead of downloading the video, it would only download the mpd file instead.

[viki] fix stream extraction from mpd

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/medaltv.py

---
---
Medal TV is a platform for gamers to record and share clips and videos. This is quite a popular site, so it was surprising that there is not an extractor for it yet. Although there is another pull request for Medal TV (https://github.com/ytdl-org/youtube-dl/pull/27118), this extractor provides all available formats (including source). The other pull request only supports 1080p or 720p. This extractor also provides error checking (in case a video does not exist for example). Furthermore, this extractor was tested on 1400 medal clips and …

[MedalTV] Add new extractor

---

youtube_dl/extractor/videa.py

Closes #26288, closes #25973, closes #25650.

[videa] Adapt to updates

---

youtube_dl/extractor/ina.py

[ina] support mobile links

---

youtube_dl/extractor/nhk.py

---
---
I am working on a separate pull request for NHK, [here](https://github.com/ytdl-org/youtube-dl/pull/27230). The changes in that PR will have an effect on both the downloading of video and audio clips from NHK. Since there is not currently a test case for audio clips though, it is hard to tell if the changes are breaking audio downloading. I am therefore adding an audio clip specific test case in this PR to make sure we understand the current expected values for downloading an audio clip. Once this is merged, I can then use this test to …

[nhk] Add audio clip test to NHK extractor

---

youtube_dl/extractor/youtube.py

---
---
Nothing fancy just a trivial change.

Remove unused headers

---

README.md

---
---
Travis has been migrating `.org` to `.com`

[Readme] travis-ci.org -> .com

---

youtube_dl/YoutubeDL.py

---
---
Proposed bug fix for issue #26010

Fix filename truncation after period for thumbnails

---

youtube_dl/extractor/youtube.py

---
---
This pull request adds some online invidious instances listed at invidio.us to the youtube extractor.

[Invidious] Added online invidious instances listed in invidio.us

---

youtube_dl/extractor/eporner.py

[eporner] Fix regex (Closes #26197)

---

youtube_dl/extractor/peertube.py

Another pull request in continuation of #26302. Re-requested due to DMCA take-down.

[peertube] Extract files also from `streamingPlaylists`

---

youtube_dl/extractor/aenetworks.py

---
Apparently AENetworks only returns 150 episodes in their playlists.

[aenetworks] Fix test

---

youtube_dl/extractor/ard.py

---
---
This updates and replaces a few failing tests and relaxes the ARD valid url regex.

Fix aenetworks and ARD tests

---

youtube_dl/extractor/ninegag.py

---
---
The website has changed in the past 4 years and the original extractor stopped working. I rewrote it to be able to handle this.

[9gag] Adjusted for current website

---

youtube_dl/extractor/americastestkitchen.py
youtube_dl/extractor/extractors.py

---
---
This PR adds the ability to download entire seasons of ATK as `youtube-dl` playlists.

[americastestkitchen] Add support for downloading entire seasons

---

youtube_dl/extractor/njpwworld.py

---
---
Player code changed. Old extractor no longer works.

[njpwworld] new extraction

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/tv2.py

---
Extracts videos from articles / web pages in mtvuutiset.fi. The videos share the backend with mtv.fi / katsomo.fi / tv2.no.
An improved resubmission of #26658 with a live branch.

[tv2] Add support for mtvuutiset.fi

---

youtube_dl/extractor/awaan.py

---
This fixes the test for me. See also 93933c9819fa1282081a5f0761cbeabc9fbea336 and #10773.

[AWAAN] Extract uploader

---

youtube_dl/extractor/cda.py

---
---
This commit fix problem when video from cda.pl need confirm user age. Bug #14022

[CDA] fix birth validate regex

---

youtube_dl/extractor/vvvvid.py

---
Some videos on the website are youtube embeds.
So I added the support for this kind of videos maintaining the infos extractions for consistency with playlist extraction

[vvvvid] added youtube support + test

---

youtube_dl/extractor/aenetworks.py

---
Test result changed … again.

[AENetworks] Fix test again

---

youtube_dl/extractor/azmedien.py

[AZMedien] Fix extraction

---

youtube_dl/extractor/urplay.py

[URPlay] Fix extractor

---

youtube_dl/extractor/peertube.py

---
i simply added support for https://canard.tube a peertube instance

[peertube] adding support for canard.tube

---

youtube_dl/extractor/vgtv.py

---
---
Aftonbladet.se (which uses the VGTC extractor) updated their URLs. This PR updates the URL and adds a test to verify it.

[vgtv] updated for new aftonbladet.se url

---

youtube_dl/extractor/youku.py

* You will be asked some questions, please read them **carefully** and answer honestly
* Put an `x` into all the boxes [ ] relevant to your _pull request_ (like that [x])
* Use _Preview_ tab to see how your _pull request_ will actually look like
Variable ccode changed from '0590' to '0532' in youtube_dl/extractor/youku.py
Tested on command:
youtube-dl -g 'https://v.youku.com/v_show/id_XNDk5MTEwNDczNg==.html'
Fixed issues #28460 and #28447

[Youku] fix download, issues #28460 and #28447

---

youtube_dl/extractor/xfileshare.py

---
---
aparat.cam now redirects to wolfstream.tv

[xfileshare] Add wolfstream.tv support

---

youtube_dl/extractor/medaltv.py

---
---
medal added some more characters to new upload URL structure, added along with addl tests coverage for them

[medaltv] Add additional characters to URLs and more tests for those characters

---

youtube_dl/extractor/shared.py

---
- [x ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x ] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [x ] I am the original author of this code and I am willing to release it under …

[vivo] Update regex

---

youtube_dl/extractor/orf.py

[orf:tvthek] fix mpd extraction

---

youtube_dl/extractor/egghead.py

---
---
Resolves #28404
Changed `_VALID_URL` in `EggheadLessonIE` to accept urls from `EggheadCourseIE`.

[egghead] fix extractor

---

youtube_dl/extractor/bilibili.py

---
---
A minor fix. Remove the spaces that occur constantly before and after the uploader name extracted using the existing method.
The figure below shows the json metadata produced when downloading [this video](https://www.bilibili.com/video/BV1Ex411E7gA) using the latest version of youtube-dl . These spaces are not part of usernames and they occur constantly.

[Bilibili] strip the uploader name 

---

youtube_dl/extractor/viki.py

---
---
This PR back-ports the Viki extractor from yt-dlp. Apart from necessary Py 2.7 and yt-dl API compatibility changes, some of the code was reorganised to match the existing extractor more closely.
Fixes #29224
Fixes #29459 
Fixes #29502
Fixes #29891
Fixes #30592
Partially resolves #28756, resolves #29243, blaming the site instead of the extractor.
Expected to resolve #29227, but account needed.

[Viki] Back-port extractor from yt-dlp

---

youtube_dl/extractor/tele5.py

---
---
According to #30499, tele5.de is (now) just another Discovery Networks site and no longer uses JWPlatform.
This PR reimplements the extractor based on the DPlayIE extractor class, and fixes the tests.
Certain shows give `ERROR: Missing deviceId in context`, which [appears to show DRM](https://github.com/yt-dlp/yt-dlp/issues/2364): see also #26186, https://github.com/yt-dlp/yt-dlp/issues/2303#issuecomment-1010225932. As this is a provider-level issue, it would better be handled in the DPlay module; for the moment the error is trapped and translated.
Resolves #30499
Resolves #30514
Resolves #30557.

[Tele5] Support Tele5 pages with Discovery Networks format instead of JWPlatform

---

youtube_dl/extractor/ndr.py

---
---
In issue #30512, a new URL format was found. This PR adds support for that format. It also fixes issues with the extractor classes in the module that caused tests with valid URLs to fail and marks invalid tests appropriately.
Resolves #26563
Resolves #30512.

[NDR] Overhaul NDR and NJoy extractors

---

youtube_dl/extractor/xvideos.py

---
- [] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
---

xvideos: Fix for #30271

---

youtube_dl/extractor/bbc.py

---
---
A couple of changes to keep up with BBC [React-ified pages](https://charlespeters.net/writing/server-side-react) where the static HTML contains a script assignment of the initial page structure as JSON to `window.__INITIAL_DATA__`:
* support stringified JSON in `__INITIAL_DATA__` (thanks https://github.com/ytdl-org/youtube-dl/issues/29926#issuecomment-952978220)
* support [media entries in `['data']['content']['model']['blocks']`](https://github.com/ytdl-org/youtube-dl/issues/29926#issuecomment-915517254) as well as `['data']['blocks']`
* also add initial work-around for randomly 403-ed m3u8 links
* also fix test for `bbcthreeConfig` pages.
Resolves #29926
Resolves #30291

[BBC] Support new features in pages with __INITIAL_DATA__

---

youtube_dl/extractor/videa.py

---
---
This PR updates the `VideaIE` extractor in two parts:
1. Revive PR #30418 from deleted user @kikuyan as below (line numbers from original).
>Fix problems when running under Python 2.7.
Line 94 resolves #30416.
Line 124 is for `FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead`.
2. Back-port fixes and tests from yt-dlp PRs https://github.com/yt-dlp/yt-dlp/pull/463 and https://github.com/yt-dlp/yt-dlp/pull/1028 (thanks @nyuszika7h), with a change matching that at original l.124.

[Videa] Overhaul extractor

---

youtube_dl/extractor/streamcz.py

---
---
This extractor originally started as https://github.com/ytdl-org/youtube-dl/pull/21774 PR that later evolved to https://github.com/yt-dlp/yt-dlp/pull/1616 which was merged to `yt-dlp`. This is attempt to backport it to `youtube-dl` with minimal changes as I suggested in https://github.com/ytdl-org/youtube-dl/pull/30462#issuecomment-1032477326. Tests are synchronized with PR https://github.com/yt-dlp/yt-dlp/pull/2747.
Fixes: #30160
Fixes: #29689
Fixes: #20900
Fixes: #22114

[streamcz] backport from yt-dlp

---

youtube_dl/extractor/bigo.py
youtube_dl/extractor/extractors.py

---
---
This adds support for bigo.tv.
Some of the code is from yt-dlp/yt-dlp#933 .
Closes #18357

[bigo] add support for bigo.tv

---

youtube_dl/extractor/aliexpress.py

[aliexpress] Fix test case

---

youtube_dl/extractor/cpac.py
youtube_dl/extractor/extractors.py

---
---
Adds support for CPAC (Canadian Parliament) through new extractors:
* CPACIE: single episode
* CPACPlaylistIE: playlists and searches.
Resolves #18148
Resolves #30668
Closes #18265 (superseded)

[CPAC] Add extractor for Canadian Parliament

---

youtube_dl/extractor/alsace20tv.py
youtube_dl/extractor/extractors.py

---
---
This PR adds support for extraction from two page types in the alsace20.tv site.
Requested in and resolves #30603. Thanks to OP @Shnoulle for additional testing documented there.

[Alsace20TV] Add new extractors Alsace20TVIE, Alsace20TVEmbedIE

---

README.md

<details>
<summary>Boilerplate: own code, improvement</summary>
---
---
</details>
Clarify how test cases are named in `TestDownload`.
Resolves #30898.

[doc] Clarify test naming

---

CONTRIBUTING.md

---
---
Just a little explanation for avoiding mistakes

Added little explanation in description

---

test/test_download.py
youtube_dl/aes.py
youtube_dl/extractor/minds.py

<details>
<summary>Boilerplate: own code, improvement/bug fix</summary>
---
</details>
---
Improve download test logs (add test case name).
Also clean up some new _flake8_ issues (space after keyword).

[test, etc] Improve download test logs; also clean up some new flake8 issues

---

youtube_dl/extractor/infoq.py

---
Implement the proposed fix at issue #31131 for the infoq extractor
Resolves #31131.

Implement the proposed fix at issue #31131 for the infoq extractor

---

youtube_dl/extractor/manyvids.py

<details>
<summary>Boilerplate: own code, improvement</summary>
---
</details>
---
This PR provides an improved version of the ManyVids extractor, which
* extracts all formats from page
* extracts description (see https://github.com/yt-dlp/yt-dlp/issues/4634), uploader, views, likes
* downrates previews.
Please comment if this fixes the issue #28758, where a user could not download a paid video using cookies from a logged-in browser session. The extractor doesn't support username/password authentication.

[manyvids] Improve extraction

---

youtube_dl/extractor/neteasemusic.py

---
---
Add warnings for users outside of China, add more diagnostic information, and give suggested advice.

[netease] Add warnings for users outside of China

---

youtube_dl/extractor/neteasemusic.py

---
---
Support song url shared from mobile app.

[netease] Support urls shared from mobile app

---

youtube_dl/extractor/americastestkitchen.py

---
---
This PR adds the ability to download entire series of ATK as youtube-dl playlists.

[americastestkitchen] Add support for downloading entire series

---

README.md

---
---
This is a change to the Readme file where the sentence ends in a colon but should really end on a full stop. 
I thought it would probably be better to make use of an example as stated on [here](https://github.com/ytdl-org/youtube-dl/issues/31425)

missing example in documentation on github. Resolves #31425

---

youtube_dl/extractor/cammodels.py

---
This PR fixes the broken extractor as described in #22734 by adding the url to the manifest server as it no longer exists in the html. Additionally the jpeg formats are added as thumbnails.
Closes #22734

[cammodels] fix and improve extractor

---

youtube_dl/extractor/youtube.py

---
---
Fixed a bug related to youtube-dl not being able to find and download videos listed under a channel's "shorts" subpage with help and guidance from @dirkf. Also tried to improve upon the solution by having the playlist data allow a title to be proposed in the list of playlist items. When running youtube-dl with the --flat-playlist and --dump-json option, the returned JSON data now has the title for each video.

[YouTube] Fix not finding videos listed under a channel's "shorts" subpage. 

---

youtube_dl/extractor/blerp.py
youtube_dl/extractor/extractors.py

---
---
Adds a new extractor for Blerp. Uses Blerp's GraphQL API to query the file in the CDN required for download.
Resolves #31340.

[Blerp] Add new extractor

---

youtube_dl/extractor/xhamster.py

---
support for new xhamster domain xhvid.com
example: https://xhvid.com/videos/lk-mm-xhc6wn6

add support for xhamster new domain xhvid.com

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/kommunetv.py

---
---
Adds support for kommunetv.no
Fixes #30801

[KommunetvIE] Add extractor for kommunetv.no

---

youtube_dl/extractor/extractors.py
youtube_dl/extractor/streamsb.py

---
---
add support for streamsb.com
Resolves #30607.

[StreamsbIE] Add extractor for streamsb.com (viewsb.com)

---

README.md

---
---
The "Get cookies.txt" extension (which used to be okay) has now turned malicious and is no longer suitable for recommending to others, so this pull request edits README.md to remove the link to it.
This PR does **not** alter any code, so I have not run any tests as they are not applicable.
Fixes #31465.

Remove "Get cookies.txt" extension from README.md

---

youtube_dl/extractor/youtube.py

---
This change is part of yt-dlp (https://github.com/yt-dlp/yt-dlp/commit/378ae9f9fb8e8c86e6ac89c4c5b815b48ce93620)
---
This fixes the issue where videos/playlists could not be extracted in certain situations (EU users).
Thought I would throw up a PR to help out. …

fix(youtube): update extractor handling consent

---

.github/workflows/ci.yml
youtube_dl/extractor/imgur.py

<details><summary>Boilerplate: own code, bug fix+improvement</summary>
---
</details>
---
* introduce base classes
* revise and refactor `ImgurIE` using `posts/v1/media` API for more accurate extraction
* add `imgur:` pseudo-URL-scheme
* revise and refactor `ImgurIE` using `posts/v1/albums` API, replacing [defunct `gallery` API](https://github.com/ytdl-org/youtube-dl/issues/29552#issuecomment-1771717731)
* include valid tests from old PRs #16674 and #21693.
Closes #25351.
Closes (replaces) #21693.

[Imgur] Overhaul extractor module

---

test/test_jsinterp.py
test/test_youtube_signature.py
youtube_dl/casefold.py
youtube_dl/compat.py
youtube_dl/extractor/youtube.py
youtube_dl/jsinterp.py

<details><summary>Boilerplate: yt-dlp code/bug fix</summary>
---
---
</details>
Back-port _yt-dlp_ code for lockup view model channel playlist extraction.

[YouTube] Fix channel playlist extraction
